### ISSUE TITLE
SoundCloud streaming source component

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#111]

**Comment by tizonia** [comment]
- A SoundClient Python proxy and associated C/C++ wrapper library have been implemented.
- Wrapper integrated as a SoundCloud role into the OMX.Aratelia.audio_source.http component.
- SoundCloud support has also been added to the tizonia player app.

Last commit in the series:
0495f99ac8ed186e928505b1cf2e0c3cc20e81ae
