### ISSUE TITLE
libtizonia: support for OMX_UseEGLImage

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#118]
OMX_UseEGLImage is an optional feature in OpenMAX IL. At present there is not enough infrastructure in  libtizonia to fully enable components that need to use EGL buffers.

A couple of things are requried:
- A means for the component implementation to validate the EGL buffer handle during the loaded->idle transition (e.g. by registering an alloc hook with 'tiz_comp_register_alloc_hooks').
- A means for the component's "processor" to retrieve the EGL buffer handle when buffer header arrivals are signalled with 'tiz_prc_buffers_ready'.

**Comment by juanrubio** [comment]
OK, I think this is done.

There are two new apis:

In tizscheduler.h:
```
OMX_ERRORTYPE tiz_comp_register_eglimage_hook (
    const OMX_HANDLETYPE ap_hdl, const tiz_eglimage_hook_t *ap_hook);
```
This hook is optional, and can be used to register a validation function that will be called when the component processes the OMX_UseEGLImage calls. Validation of the EGL image is implementation dependent, hence optional.

See here for an example of use:
https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/test_component/tiztc.c

In tizkernel.h:
```
OMX_ERRORTYPE tiz_krn_claim_eglimage (const void *ap_obj, const OMX_U32 a_pid,
                                      const OMX_BUFFERHEADERTYPE *p_hdr,
                                      OMX_PTR *app_eglimage);
```
This API is used to retrieve the egl image when the event that signals that the corresponding header has arrived is received at the component's 'processor'.

An example of use here:
https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/test_component/tiztcproc.c

**Comment by juanrubio** [comment]
There is also some (WIP) documentation 

here:
http://docs.tizonia.org/en/master/devel/openmaxil/libtizonia/tizscheduler.html

and here:
http://docs.tizonia.org/en/master/devel/openmaxil/libtizonia/tizkernel.html

**Comment by CapOM** [comment]
Great I'll try that, thx.
