### ISSUE TITLE
various graphs : add rewind, fast-forward functionality

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#125]

**Comment by marcusorjames** [comment]
Is this not being considered for 0.8?

**Comment by tizonia** [comment]
Hi @marcusorjames. Thanks for getting in touch.

I don't have immediate plans to get this implemented. The reason is that there is a non-trivial amount of work until the various internal graphs are migrated to support seek functionality. 

You can find here a list of items that are currently in my radar:
https://github.com/tizonia/tizonia-openmax-il#roadmap

Having said that, I'd be more than happy to provide guidance and accept contributions if anybody wants to help. 

There is another issue (#438) which covers this and has a bit more context. So I will be closing #125 in favor of #438.

**Comment by marcusorjames** [comment]
Thank you for the response. I missed that other thread and thought this was hanging. I think this is more clear now.
