### ISSUE TITLE
docs: update Sphinx config to integrate 'breathe' and allow Doxygen output in Read the Docs 

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#127]
- https://breathe.readthedocs.org/en/latest/

**Comment by tizonia** [comment]
Since a544214c1c9052c4345688d9d7044fd74f82cedc, doxygen is integrated into sphinx output using 'breathe' and the Read the Docs configuration is now building both. New documentation is now online.
