### ISSUE TITLE
Coverity Scan (CID 1352327) [/player/src/tizplayapp.cpp:getch_] : Truncated stdio return value

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#162]
- CID : 1352327
- Type : Truncated stdio return value
- Impact : Medium
- Status : New
- First Detected : 02/29/16
- Classification : Unclassified
- Severity : Unspecified
- Component : player
- Category : API usage errors
- File : /player/src/tizplayapp.cpp
- Function : getch_

**Comment by juanrubio** [comment]
Already fixed by #198.
