### ISSUE TITLE
Coverity Scan (CID 1352340) [/plugins/http_renderer/src/httprsrv.c:srv_accept_connection] : Logically dead code

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#167]
- CID : 1352340 \* Type : Logically dead code \* Impact : Medium \* Status : New \* First Detected : 02/29/16 \* Classification : Unclassified \* Severity : Unspecified \* Component : http_renderer \* Category : Control flow issues \* File : /plugins/http_renderer/src/httprsrv.c \* Function : srv_accept_connection

**Comment by juanrubio** [comment]
False positive
