### ISSUE TITLE
Coverity Scan (CID 1352330) [/plugins/http_renderer/src/httprsrv.c:srv_create_server_socket] : Unchecked return value from library

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#172]
- CID : 1352330 \* Type : Unchecked return value from library \* Impact : Medium \* Status : New \* First Detected : 02/29/16 \* Classification : Unclassified \* Severity : Unspecified \* Component : http_renderer \* Category : Error handling issues \* File : /plugins/http_renderer/src/httprsrv.c \* Function : srv_create_server_socket

**Comment by juanrubio** [comment]
Fixed by de321f9caad582471b71162fd412f18e7cedd470
