### ISSUE TITLE
Coverity Scan (CID 1087266) [/libtizonia/src/tizutils.c:tiz_fsm_state_to_str] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#175]
* CID : 1087266 
* Type : Mixing enum types 
* Impact : Medium 
* Status : New 
* First Detected : 09/11/13 
* Classification : Unclassified 
* Severity : Unspecified 
* Component : libtizonia 
* Category : Incorrect expression 
* File : /libtizonia/src/tizutils.c 
* Function : tiz_fsm_state_to_str

**Comment by juanrubio** [comment]
Will not fix (not an issue).
