### ISSUE TITLE
Coverity Scan (CID 1087267) [/libtizonia/src/tizpausetoidle.c:pausetoidle_trans_complete] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#176]
- CID : 1087267 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 09/11/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizpausetoidle.c \* Function : pausetoidle_trans_complete

**Comment by juanrubio** [comment]
This has been fixed already.
