### ISSUE TITLE
Coverity Scan (CID 1087269) [/libtizonia/src/tizexecuting.c:executing_trans_complete] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#178]
- CID : 1087269 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 09/11/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizexecuting.c \* Function : executing_trans_complete

**Comment by juanrubio** [comment]
This has been fixed already.
