### ISSUE TITLE
Coverity Scan (CID 1087272) [/libtizonia/src/tizstate.c:state_trans_complete] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#181]
- CID : 1087272 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 09/11/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizstate.c \* Function : state_trans_complete

**Comment by juanrubio** [comment]
This has been fixed already.
