### ISSUE TITLE
Coverity Scan (CID 1087274) [/libtizonia/src/tizwaitforresources.c:waitforresources_trans_complete] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#182]
- CID : 1087274 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 09/11/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizwaitforresources.c \* Function : waitforresources_trans_complete

**Comment by juanrubio** [comment]
This has been fixed already.
