### ISSUE TITLE
Coverity Scan (CID 1087279) [/libtizonia/src/tizfsm.c:fsm_complete_transition] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#186]
- CID : 1087279 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 09/11/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizfsm.c \* Function : fsm_complete_transition

**Comment by juanrubio** [comment]
This has been fixed already.
