### ISSUE TITLE
Coverity Scan (CID 1352354) [/libtizonia/src/tizservant.c:srv_issue_trans_event] : Mixing enum types

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#190]
- CID : 1352354 \* Type : Mixing enum types \* Impact : Medium \* Status : New \* First Detected : 02/29/16 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizservant.c \* Function : srv_issue_trans_event

**Comment by juanrubio** [comment]
This issue has been fixed already
