### ISSUE TITLE
Coverity Scan (CID 1352358) [/libtizonia/src/tizuricfgport.c:uri_cfgport_GetParameter] : Array compared against 0

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#192]
- CID : 1352358 \* Type : Array compared against 0 \* Impact : Medium \* Status : New \* First Detected : 02/29/16 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizonia \* Category : Incorrect expression \* File : /libtizonia/src/tizuricfgport.c \* Function : uri_cfgport_GetParameter

**Comment by juanrubio** [comment]
This has been fixed at some point but the issue was never closed. So closing now.
