### ISSUE TITLE
Coverity Scan (CID 993663) [/libtizplatform/src/ev/ev.c:infy_cb] : Untrusted array index read

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#197]
- CID : 993663 \* Type : Untrusted array index read \* Impact : Medium \* Status : New \* First Detected : 03/27/13 \* Classification : Unclassified \* Severity : Unspecified \* Component : libtizplatform \* Category : Insecure data handling \* File : /libtizplatform/src/ev/ev.c \* Function : infy_cb

**Comment by juanrubio** [comment]
Will not fix (third party code)
