### ISSUE TITLE
Coverity Scan (CID 1087260) [/libtizplatform/src/avl/avl.c:avl_iterate_index_range] : Dereference null return value

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#205]
* CID : 1087260 
* Type : Dereference null return value 
* Impact : Medium 
* Status : New 
* First Detected : 09/11/13 
* Classification : Unclassified 
* Severity : Unspecified 
* Component : libtizplatform 
* Category : Null pointer dereferences 
* File : /libtizplatform/src/avl/avl.c 
* Function : avl_iterate_index_range

**Comment by juanrubio** [comment]
Won't fix (found in third party lib)
