### ISSUE TITLE
Coverity Scan (CID 1352364) [/libtizplatform/src/tizrc.c:get_node] : Resource leak

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#232]
- CID : 1352364
- Type : Resource leak
- Impact : High
- Status : New
- First Detected : 02/29/16
- Classification : Unclassified
- Severity : Unspecified
- Component : libtizplatform
- Category : Resource leaks
- File : /libtizplatform/src/tizrc.c
- Function : get_node

```
290
    18. Condition -1 != ret, taking true branch
291  if (-1 != ret)
292    {
293      *app_kv = p_kv;
294    }
295

CID 1352364 (#1 of 1): Resource leak (RESOURCE_LEAK)
19. leaked_storage: Variable value going out of scope leaks the storage it points to.
296  return ret;
297}
```

**Comment by juanrubio** [comment]
This can be closed now.
