### ISSUE TITLE
Coverity Scan (CID 1352368) [/usr/include/boost/msm/back/state_machine.hpp:state_machine] : Uninitialized scalar field

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#235]
* CID : 1352368 
* Type : Uninitialized scalar field 
* Impact : Medium 
* Status : New 
* First Detected : 02/29/16 
* Classification : Unclassified 
* Severity : Unspecified 
* Component : Other 
* Category : Uninitialized members 
* File : /usr/include/boost/msm/back/state_machine.hpp 
* Function : state_machine

**Comment by juanrubio** [comment]
Closing as this file is not part of Tizonia
