### ISSUE TITLE
Coverity Scan (CID 1352370) [/usr/include/boost/msm/back/dispatch_table.hpp:dispatch_table] : Uninitialized pointer field

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#237]
- CID : 1352370 \* Type : Uninitialized pointer field \* Impact : Medium \* Status : New \* First Detected : 02/29/16 \* Classification : Unclassified \* Severity : Unspecified \* Component : Other \* Category : Uninitialized members \* File : /usr/include/boost/msm/back/dispatch_table.hpp \* Function : dispatch_table

**Comment by juanrubio** [comment]
Closing as this file is not part of Tizonia
