### ISSUE TITLE
No pluginsdir variable in pkg-config file.

### ISSUE THREAD

**Issue by gpalsingh** [tizonia/tizonia-openmax-il#248]
Hi,
I am working on switching the mesa/gallium OpenMAX state tracker from bellagio to Tizonia as a potential X.Org EVoC student.
I noticed that mesa uses the pluginsdir variable to set the install location of libomx_mesa.so file. But Tizonia does not provide this variable which is necessary to make any further progress.
I have installed tizonia using apt because compiling from source crashes my PC halfway through.
Thanks

**Comment by juanrubio** [comment]
Hi!

I was wondering if you would be able to elaborate a bit. Maybe you could point me to the mesa sources that make pluginsdir a requirement?.

Wrt compilation, compiling Tizonia from top-level involves the compilation of the  'player' application (C++, boost, etc, i.e. difficult to compile). You don't need to build this for your work in Mesa. I've created #249 for this, but in the meantime you can simply remove this sub-project from the top-level configure.ac and Makefile.am files.

**Comment by gpalsingh** [comment]
The variable is used in configure.ac at line 2252:
https://cgit.freedesktop.org/mesa/mesa/tree/configure.ac#n2252

For now I am using the libdir variable as I saw that tizonia installs the plugins in libdir only.

**Comment by juanrubio** [comment]
I see. It looks like this is specific to Bellagio.  See here:

https://bugs.freedesktop.org/show_bug.cgi?id=80615

And this patch:
https://patchwork.freedesktop.org/patch/33916/

So mesa seems to be adapted to whatever Bellagio used at the time (in this case 'pluginsdir') to identify the location of the OMX components.

So I wonder if it would actually make more sense to add a separate option for Tizonia, to allow that to co-exist with the existing "with-omx-libdir"... 

....but not sure though. 

I need to look more into this.

**Comment by juanrubio** [comment]
IL Components are now installed under ${libdir}/tizonia0-plugins12

```
+# Define location of plugin directory
 +AS_AC_EXPAND(PLUGINDIR, ${libdir}/tizonia0-plugins12)
 +AC_DEFINE_UNQUOTED(PLUGINDIR, "$PLUGINDIR",
 +  [Directory where Tizonia plugins are located])
 +AC_MSG_NOTICE([Using $PLUGINDIR as the components install location])
 +# Define plugin directory configure-time variable
 +AC_SUBST([plugindir], ['${libdir}/tizonia0-plugins12'])
 ```

Also the il core pkgconfig file has been updated to include a "pluginsdir" variable:

```
 exec_prefix=@exec_prefix@
  libdir=@libdir@		  libdir=@libdir@
  includedir=@includedir@		  includedir=@includedir@
 -pluginsdir=@libdir@		 +pluginsdir=@libdir@/tizonia0-plugins12
  		  
  Name: libtizcore		  Name: libtizcore
  Description: Tizonia OpenMAX IL 1.2 Core		  Description: Tizonia OpenMAX IL 1.2 Core
```

**Comment by juanrubio** [comment]
I believe this can be closed now.
