### ISSUE TITLE
build system : top-level 'configure' option to enable/disable 'player' compilation

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#249]
The 'player' sub-folder contains the C++-based command-line app. There may be users that are only interested in building the OMX framework, without the command-line application.

Having a top-level 'configure' option to disable the compilation of the 'player' sub-project would allow compilation of all the supporting libraries, without the overhead of the compilation of the player app.

**Comment by CapOM** [comment]
Indeed that would be really nice to do something like that  tools/tizonia-dev-build --no-player --release --install .  But I think the underlying problem is also that it is really slow to build the player.

**Comment by tizonia** [comment]
Added `--disable-player / --enable-player` configure option. Default: player is enabled

E.g.: to disable
```
./configure --disable-player

or 

tools/tizonia-dev-build --no-player --debug --install

```
