### ISSUE TITLE
clients: youtube audio streaming proxy Python module

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#253]
Based on mps-youtube/pafy

**Comment by juanrubio** [comment]
tizyoutubeproxy.py already implemented. Closing this issue now.

**Comment by xuelvming** [comment]
But ,is there a doc where I can learn how to set the proxy for audio from Youtube or google?

**Comment by juanrubio** [comment]
This "proxy" is simply a Python shim to allow an easy use of the mps-youtube/pafy apis, and to wrap that functionality in a C/C++ module that can be used by the OpenMAX IL framework.

So the goal is to be able to access YouTube audio URLs and their various pieces of metadata. I.e. this "proxy" is meant to be used used to provide the implementation of the C APIs in this module:
https://github.com/tizonia/tizonia-openmax-il/blob/master/clients/youtube/libtizyoutube/src/tizyoutube_c.h
