### ISSUE TITLE
Spotify connection problem. Error 410

### ISSUE THREAD

**Issue by aldanopolis** [tizonia/tizonia-openmax-il#272]
![tizonia](https://cloud.githubusercontent.com/assets/22052109/20243297/73ec53c6-a917-11e6-9fb2-5d5e4fac6e3a.jpg)

**Comment by juanrubio** [comment]
Hi!,

Sorry to hear that you are having problems to connect. Spotify seems to be working fine at my end (I'm running head or the master branch as well as 0.5.0 in several raspberry pis). 

Interestingly, Spotify is reporting that your user is logged in, to later report the connection error 410.

Google returns a few hits from the Spotify forums for the 410 error:
https://community.spotify.com/t5/Accounts-and-Subscriptions/Error-Code-410/td-p/6969
https://community.spotify.com/t5/Accounts-and-Subscriptions/How-do-you-fix-error-410/td-p/485506
https://community.spotify.com/t5/Accounts-and-Subscriptions/Need-help-in-resolving-error-code-410/td-p/773667

Some people reported that changing the password fixed their 410 issue. 

Another option would be to see if wiping the Spotify files under /var/tmp/tizonia fixes anything.

Let me know how it goes

**Comment by aldanopolis** [comment]
Thank you for the answer, I looked the posts and I found the problem, is because two-step verification. I added an application password in my FB and now works. Thanks :D
