### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#296]
The option --cast allows the selection of a chromecast device for audio rendering.

**Comment by tizonia** [comment]
Version 0.12.0 which is about to be released includes Chromecast support

**Comment by tizonia** [comment]
NOTE: in addition to #298 and #297, this Chromecast support also includes two new sub-modules:
- 'tizcastd': a D-Bus-based daemon for Chromecast interfacing
- 'libtizcastclient': a client library to access the Tizonia's Chromecast daemon process.
