### ISSUE TITLE
Registering new ports

### ISSUE THREAD

**Issue by gpalsingh** [tizonia/tizonia-openmax-il#319]
Hi, I was looking at how the tizonia plugins register their ports since I would need to register one for the AVC decoder in mesa.
I found the way the existing plugins do is to add them in libtizonia
https://github.com/tizonia/tizonia-openmax-il/tree/1e28798ff116574bf0f29de960afd1230310eb92/libtizonia/src
and register them in tizobjsys.c

So what I wanted to know: is there a way to register new ports without having to make changes to tizonia-openmax-il?

**Comment by juanrubio** [comment]
Hi Gurkirpal,

Very good question. Yes, there is a way for plugins to register new ports without having to explicitly add them in libtizonia.

The simple rule I follow when adding new ports is:
- if the port is general purpose (e.g. ports that are defined in the spec) or ports that are likely to be used by more than one component, then it makes sense for libtizonia to own this port. So I add it to libtizonia following the process you mentioned above.
- if the port is specific to a component, not standard, or not likely to be used in more than one component, then I define and register the port in the plugin itself.

See the 'http_source' component for examples of how to "register" new object classes (ports and processors). Examples of registration of new object classes can be seen at the bottom of   https://github.com/tizonia/tizonia-openmax-il/blob/master/plugins/http_source/src/httpsrc.c:

Simply you need to define a number of "factories" (i.e. one per port or processor) and the pass the list to libtizonia, initialise the factories, and then pass the list to libtizonia once the component infrastructure has been initialized:

```
  /* Initialize the component infrastructure */
  tiz_check_omx (
    tiz_comp_init (ap_hdl, ARATELIA_HTTP_SOURCE_COMPONENT_NAME));

  /* Register the various classes */
  tiz_check_omx (tiz_comp_register_types (ap_hdl, tf_list, 10));
```

I hope it helps

**Comment by juanrubio** [comment]
Regarding the AVC port, this port is defined in the spec, so it would make sense to add it to libtizonia (for example, if you are happy to contribute it), or alternatively, you can add it privately to your plugin in the way I outlined before.
