### ISSUE TITLE
Issues with Google Music : --gmusic-unlimited-tracks

### ISSUE THREAD

**Issue by zolij** [tizonia/tizonia-openmax-il#325]
Hello,

First of all, this software is awesome, thanks for it.

However I have some issues with Google Music. While --gmusic-unlimited-artist and some other stuff are working well, I have problems with --gmusic-playlist and --gmusic-unlimited-tracks

```
tizonia --gmusic-unlimited-tracks 'We will rock you'
[Google Play Music] [Tracks in queue] '10'.
[Google Play Music] (CallFailure) : GetStreamUrl: 404 Client Error: Not Found for url: https://mclients.googleapis.com/music/mplay?opt=hi&songid=tgr5k6r7ukucady5yru4fnyvxa&pt=e&slt=1496607327442&tier=fr&sig=P7vGDgMs9_U0jwDHX1Pd2CXLzUg&hl=en_US&dv=0&net=mob
(response was: u'<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')
tizonia exiting (OMX_ErrorInsufficientResources).
```

The playlist error:
```
[Google Play Music] (KeyError) : 'Playlist not found : Vad Fruttik'
tizonia exiting (OMX_ErrorInsufficientResources).
 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

Any ideas?

Thanks

**Comment by juanrubio** [comment]
Hi Zoltan

Thanks for the feedback. The playlist search is working for me (I have yet to try the --gmusic-unlimited-tracks option).

Have you recently upgraded Tizonia's Python dependencies?. There are frequent changes in these packages that Tizonia relies on and sometimes issues like this get resolved for free (without requiring upgrades to Tizonia). So I type the following command on terminal almost on a daily basis.

```
sudo -H pip install --upgrade gmusicapi soundcloud pafy youtube-dl
```
Could you please try that and let me know if it makes any difference?

**Comment by zolij** [comment]
I tried that but unfortunatly there is no difference.

Python packages (and versions) on my system:
```
appdirs==1.4.3
asn1crypto==0.22.0
backports-abc==0.5
beautifulsoup4==4.6.0
cachetools==2.0.0
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.3
colorama==0.3.9
configobj==5.0.6
cryptography==1.9
decorator==4.0.11
Django==1.11.2
enum34==1.1.6
fudge==1.1.0
funcsigs==1.0.2
future==0.16.0
gmusicapi==10.1.2
gpsoauth==0.4.1
html5lib==0.999999999
httplib2==0.10.3
idna==2.5
ipaddress==1.0.18
MechanicalSoup==0.7.0
mock==2.0.0
mutagen==1.38
MySQL-python==1.2.3
ndg-httpsclient==0.4.2
oauth2client==4.1.0
pafy==0.5.3.1
pbkdf2==1.3
pbr==3.0.1
proboscis==1.2.6.0
protobuf==3.3.0
pyasn1==0.2.3
pyasn1-modules==0.0.9
pycparser==2.17
pycrypto==2.6.1
pycryptodomex==3.4.6
pycurl==7.19.5
pygobject==3.14.0
Pykka==1.2.1
pylast==1.8.0
pyOpenSSL==17.0.0
pyserial==3.3
python-apt==0.9.3.12
python-dateutil==2.6.0
python-mpd2==0.5.5
pytz==2017.2
requests==2.17.3
RPi.GPIO==0.6.3
rsa==3.4.2
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
soundcloud==0.5.0
spotipy==2.4.4
tizdirbleproxy==0.7.0
tizgmusicproxy==0.7.0
tizsoundcloudproxy==0.7.0
tizyoutubeproxy==0.7.0
tornado==4.5.1
uritools==2.0.0
urllib3==1.21.1
validictory==1.1.1
virtualenv==15.1.0
webencodings==0.5.1
WebIOPi==0.7.22
wifi==0.3.8
youtube-dl==2017.6.5
```

**Comment by juanrubio** [comment]
Uhm.. I believe the issue with the unlimited track search appears to be the same 404 that people are discussing in simon-weber/gmusicapi#474

Sounds like we need to wait and see how that resolves. There is no fix in sight and it appears to affect certain accounts only. Google Music API issues like this sometimes come and go.

As for the ' --gmusic-playlist' issue, this sounds different. I'll investigate some more.

**Comment by juanrubio** [comment]
OK, I found that the issue with the unlimited track search is not related to the 404, instead it is another issue that has been documented here:
simon-weber/gmusicapi#530

So I've created a separate issue to deal with the playlist search problem: #328 , and I'll leave the current one to push a patch for the track id issue in track search.
