### ISSUE TITLE
arch pl0x

### ISSUE THREAD

**Issue by Chinggis6** [tizonia/tizonia-openmax-il#335]
Can't find a supported Debian or Ubuntu-based distribution.

:(

Any consideration to release in the [AUR](https://aur.archlinux.org/)?

For [Arch](https://www.archlinux.org/) and [Manjaro](https://manjaro.org/) Linux'es.

**Comment by juanrubio** [comment]
Hi!

I would love to release Tizonia for Arch-like distros. Unfortunately I'm not very familiar with Arch in general, so releasing in the AUR is at the moment a bit out of my reach.

I will leave this issue open in case I have some time for this in the near future (or someone wants to step in and do it! :-) )

**Comment by Hans-Maulwurf** [comment]
+1 for an arch aur build :)

**Comment by charlesmilette** [comment]
[This might be of assistance](https://wiki.archlinux.org/index.php/Creating_packages)

**Comment by juanrubio** [comment]
Indeed!, here is a first stab at a PKGBUILD for tizonia, 2fa3772d2ffc85ed969c3cdddf127d35e1ba3a2e
Still work in progress, but thanks!

**Comment by juanrubio** [comment]
I'm adding two PKGBUILD files, for 'release' and 'git' versions. Still WIP. (0cd1fd325f05e7f7e6444200a0ed1588cf0ecaa0)

**Comment by tizonia** [comment]
@Chinggis6 , @Hans-Maulwurf , @charlesmilette 

FYI, I believe the two PKGBUILD files in 

https://github.com/tizonia/tizonia-openmax-il/tree/master/pkgbuild

are pretty much done (at least they both work on my Manjaro installation). 

However, there is a question about use of Python 2 vs Python 3, since Tizonia still depends on Python 2.

I've raised that question in Arch forums (in case you want to have a look)
https://bbs.archlinux.org/viewtopic.php?id=229325

**Comment by charlesmilette** [comment]
I tried it when submitting my PR, and it took it's sweet time to compile. However (probably unrelated), I experience the following error when trying to play music:

![image](https://user-images.githubusercontent.com/6440374/29574854-c6f9148a-8730-11e7-8746-41c57da5aac6.png)

**Comment by tizonia** [comment]
Yes, compiling Tizonia is no small feat, mostly because of the player state machines. But that is another kind of problem.

Regarding the FATAL error, sounds like the installation is not complete. I have done a number of fixes in both PKGBUILD files after you submitted your PR. Would you be able to remove the package and reinstall it again this time using one the latest PKGBUILDs, it does not matter which one. Both packages currently build and run OK at my end  (also make sure you have installed all the AUR dependencies).

After, the /usr/lib should contain among other things. the Tizonia IL Core, like this:
```
libtizcore.so -> libtizcore.so.0.0.9
etc
```

Also, your $HOME/config/tizonia/tizonia.conf should contain this line:

```
component-paths = /usr/lib/tizonia0-plugins12
```

**Comment by tizonia** [comment]
Also, it is necessary to trick the environment to use Python 2 as default. Doing something along these lines:

First create a dummy folder:
```
$ mkdir ~/bin
```
Then add a symlink python to python2 and the config scripts in it:
```
$ ln -s /usr/bin/python2 ~/bin/python
$ ln -s /usr/bin/python2-config ~/bin/python-config
```
Finally put the new folder at the beginning of your PATH variable:
```
$ export PATH=~/bin:$PATH
```

**Comment by charlesmilette** [comment]
I have built and reinstalled the package from master, applied the changes to my config and did the PATH trick, but I now get the following:

![image](https://user-images.githubusercontent.com/6440374/29577308-ecf4fcf0-8738-11e7-9621-196bd298e237.png)

Also when it fails like this my terminal does not registers any keypresses afterwards.

**Comment by tizonia** [comment]
OK, this is now looking a bit better. The OpenMAX IL Core library is now being located correctly, but the plugin dlls are not found it seems. 

This error is typical when the component-paths is pointing to the wrong location:

In my Manjaro system, $HOME/.config/tizonia/tizonia.conf contains this line:
```
component-paths = /usr/lib/tizonia0-plugins12
```
and in that location, I can see the OpenMAX IL plugin dlls:
![tizonia-component-paths](https://user-images.githubusercontent.com/3161606/29587965-02d0390c-8790-11e7-87a7-c66fdfa0ec82.png)

Do you see the same content in your system?

**Comment by charlesmilette** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/6440374/29588535-e7740010-875f-11e7-81a0-b656a5480f8b.png)

**Comment by juanrubio** [comment]
Possibly your tizonia.conf is still missing some important configuration items, most notably:

```
# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.pulseaudio.pcm
```

I would probably copy the default config from /etc/tizonia/tizonia.conf to your $HOME/.config/tizonia folder and then I would edit in there the gmusic credentials etc.

**Comment by charlesmilette** [comment]
Same thing happens.

Doesn't it reads the system-wide config in /etc/tizonia and then read the user config? That' what I would have expected.

**Comment by juanrubio** [comment]
At this point I'm pretty sure there is something specific to your environment. 

The --gmusic-album command requires three plugins:

"OMX.Aratelia.audio_source.http"
"OMX.Aratelia.audio_decoder.mp3"
And the default pcm renderer

Do you have a working pulseadio server on your system?. In system without pulseaudio, you can resort to the alsa renderer by configuring:

default-audio-renderer = OMX.Aratelia.audio_renderer.alsa.pcm

**Comment by juanrubio** [comment]
By the way, there is no need to apply the Python environment trick manually anymore. Since this commit, ee2765aa4021c79c1f051d3257f347da0b0a306d, the PKGBUILD will do the magic by itself, without requiring any action from the user.

**Comment by juanrubio** [comment]
Both PKGBUILD file are now in the AUR:

https://aur.archlinux.org/packages/tizonia-all/

https://aur.archlinux.org/packages/tizonia-all-git

**Comment by juanrubio** [comment]
@sylveon, I've created an issue to document the use of the configuration files in Tizonia, see #368

> Doesn't it reads the system-wide config in /etc/tizonia and then read the user config? 
At the moment, the application only reads one of them, giving priority to the one in the user's home, if it exists.

**Comment by juanrubio** [comment]
@sylveon I've created another issue for the wrong terminal state, see #369

> when it fails like this my terminal does not registers any keypresses afterwards.

**Comment by juanrubio** [comment]
AUR packages are available and I believe they should work in most Arch-like environments. So I'm closing this issue for now, feel free to re-open if any of you guys think there is a problem with the packaging.

**Comment by sylveon** [comment]
Actually, I think there is one last blocker:

The `python-soundcloud-git` package is for python3 and not python2, which results in a build failure:

```
<thousands of configure.ac and libtoolize lines>
configure: error: failed to find required module soundcloud
configure: error: ./configure failed for libtizsoundcloud
configure: error: ./configure failed for soundcloud
configure: error: ./configure failed for clients
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build tizonia-all-git package(s)
```

As for my OMX issue, I think it might be fixed by setting the python2 path before building rather than after ;)

**Comment by juanrubio** [comment]
Uhm, interesting. the actual Python code is both Python 2 and Python 3 compatible. But sounds like since the PKGBUILD has no explicit dependency on Python 2, it gets installed using the default Python 3 run-time. 

I had it installed as a Python 2 package while I had the environment trick in place, and that is probably why it hasn't failed for me since, even after I removed the trick.

Any idea on how to workaround this issue?

**Comment by juanrubio** [comment]
I guess, one obvious solution is to create a python2-soundcloud-git package... I should probably ask the original python-soundcloud-git maintainer in case he/she might be interested in providing that as well.

**Comment by sylveon** [comment]
I have noticed you pushed an update to the AUR adding the python2-soundcloud-git package as a dependency and tried installing it.

Now it builds, runs and plays music fine!

**Comment by tizonia** [comment]
Awesome! And thanks a lot for your feedback!
