### ISSUE TITLE
Error compiling libtizplatform from source

### ISSUE THREAD

**Issue by gpalsingh** [tizonia/tizonia-openmax-il#341]
Hi,

I was trying to compile latest tizonia from the master branch on https://github.com/tizonia/tizonia-openmax-il/commit/c9c2322fd95f42d7c4c9a16f47c0ffdaba9ef763

Running
autoreconf -ifs
./configure
make
I get this error

make[5]: Entering directory '/home/gpalsingh/gsoc/tizonia-openmax-il/libtizplatform/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -I/usr/include/tizonia -I/usr/include -g -O0 -MT libtizplatform_la-tizomxutils.lo -MD -MP -MF .deps/libtizplatform_la-tizomxutils.Tpo -c -o libtizplatform_la-tizomxutils.lo `test -f 'tizomxutils.c' || echo './'`tizomxutils.c
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -I/usr/include/tizonia -I/usr/include -g -O0 -MT libtizplatform_la-tizrc.lo -MD -MP -MF .deps/libtizplatform_la-tizrc.Tpo -c -o libtizplatform_la-tizrc.lo `test -f 'tizrc.c' || echo './'`tizrc.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/tizonia -I/usr/include -g -O0 -MT libtizplatform_la-tizomxutils.lo -MD -MP -MF .deps/libtizplatform_la-tizomxutils.Tpo -c tizomxutils.c  -fPIC -DPIC -o .libs/libtizplatform_la-tizomxutils.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/tizonia -I/usr/include -g -O0 -MT libtizplatform_la-tizrc.lo -MD -MP -MF .deps/libtizplatform_la-tizrc.Tpo -c tizrc.c  -fPIC -DPIC -o .libs/libtizplatform_la-tizrc.o
tizomxutils.c:652:4: error: ‘OMX_TizoniaIndexParamAudioDeezerSession’ undeclared here (not in a function)
   {OMX_TizoniaIndexParamAudioDeezerSession,
    ^
tizomxutils.c:654:4: error: ‘OMX_TizoniaIndexParamAudioDeezerPlaylist’ undeclared here (not in a function)
   {OMX_TizoniaIndexParamAudioDeezerPlaylist,
    ^
Makefile:659: recipe for target 'libtizplatform_la-tizomxutils.lo' failed

**Comment by juanrubio** [comment]
Hi Gurkirpal,

I've just tried the same commands on this commit and I can't see any issues:
c9c2322fd95f42d7c4c9a16f47c0ffdaba9ef763

Have you uninstalled a previous build?

**Comment by gpalsingh** [comment]
Ah I found some older headers that weren't uninstalled somehow. Thanks for checking.
