### ISSUE TITLE
Google Music: track downloading is interrupted seemingly randomly

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#349]
This issue is related to #337, which essentially delivered a workaround.

It looks like some Google servers may be closing down the connection after 90 seconds. I.e. if the track has not been fully downloaded within 90 seconds, libcurl will find the connection closed. #377 introduced an EOS event when this occurs, which will make the player jump to the next song,  as a workaround to the stalling situation in #337.

It looks like a more appropriate solution would be to make the http_source component buffer the whole track before the 90 second period is over.

This Google Play Music peculiarity has been recently documented in simon-weber/gmusicapi#548 and balloob/pychromecast#175

**Comment by tizonia** [comment]
Closing this issue. This problem does not seem to be occurring anymore.
