### ISSUE TITLE
OMX_IndexParamVideoQuantization not supported

### ISSUE THREAD

**Issue by gpalsingh** [tizonia/tizonia-openmax-il#351]
While testing out the H.264 video encoder I got this error:
```
[ERROR] [OMX.mesa.video_encoder.avc] [tizkernel.c:krn_GetParameter:349] --- [OMX_ErrorUnsupportedIndex] : [0x06000002] = [OMX_IndexParamVideoQuantization]
```
IL 1.2.0 specs 4.3.6 OMX_VIDEO_PARAM_QUANTIZATIONTYPE: "This generic structure is shared between several video standards." so tizvideoport or tizavcport should support it?

**Comment by juanrubio** [comment]
Hi Gurkirpal,

yes, I think the best place for now is to add this struct/index in tizavcport since apparently not all video standards support independent quantization factors for different frame types.

So let me go ahead and merge your pull request.
