### ISSUE TITLE
libtizonia: nBufferSize is not updated on video output port

### ISSUE THREAD

**Issue by CapOM** [tizonia/tizonia-openmax-il#358]
When vp8dprc.c::update_output_port_params calls "tiz_krn_SetParameter_internal" it results that the video output port does not get its nBufferSize updated. Instead only the input port has its nBufferSize recomputed.
Here is the possible cause:

In https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/src/tizkernel.c#L224 there is A) tiz_port_apply_slaving_behaviour (p_mos_port, ap_port).
I wonder if it should be B) iz_port_apply_slaving_behaviour (ap_port, p_mos_port) instead of above.

Indeed here https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/src/tizvideoport.c#L457 it is defined like this:
videoport_apply_slaving_behaviour (void * ap_obj, void * ap_mos_port)
So the order of the param is not the same. 

The exact issue is that https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/src/tizvideoport.c#L485
nBufferSize gets updated on the input port see "p_base->portdef_.nBufferSize = new_buf_sz;" here https://github.com/tizonia/tizonia-openmax-il/blob/master/libtizonia/src/tizvideoport.c#L528
But this value is not reflected back to the output port.

Changing A to B fixes the issue but I guess this is wrong since this is to forward changes from one port to another. But here the nBufferSize is not copied from on port to another. It is computed: "const OMX_U32 new_buf_sz = y_sz + u_sz + v_sz; " so I am confused. Also I am confused because this is done on the bitstream port (ex: input port of a decoder).

Thx in advance for your clarifications !

**Comment by CapOM** [comment]
So in the end we only need:

--- a/libtizonia/src/tizvideoport.c
+++ b/libtizonia/src/tizvideoport.c
@@ -523,7 +523,7 @@ videoport_apply_slaving_behaviour (void * ap_obj, void * ap_mos_port,
         }
 
       /* Also update the port's minimum buffer size, if needed */
-      if (new_buf_sz != p_base->portdef_.nBufferSize)
+      if (new_buf_sz != p_base->portdef_.nBufferSize && OMX_VIDEO_CodingUnused == p_base->portdef_.format.video.eCompressionFormat)

I tested that changed and it worked but I do not have the fork at the moment so please submit the change, thx a lot!

**Comment by juanrubio** [comment]
@CapOM : THe changes are committed here 4ef0f666ae21033107efdc578e1bc75ea42a5a22

Could you please review and close this issue if everything looks ok?

**Comment by CapOM** [comment]
Works. Thx
