### ISSUE TITLE
player: the terminal is occasionally left in an inconsistent state when the application fails

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#369]
As reported by @sylveon in https://github.com/tizonia/tizonia-openmax-il/issues/335#issuecomment-324087385 

> when it fails like this my terminal does not registers any keypresses afterwards.

**Comment by sylveon** [comment]
Also happens when an invalid google play music device id is given.

**Comment by juanrubio** [comment]
Fixed by 5067986cdfd06ec51d8d17e2acb9e162a69bcd58
