### ISSUE TITLE
docs: Google Play Music authentication methods

### ISSUE THREAD

**Issue by globetrotterdk** [tizonia/tizonia-openmax-il#394]
How does one authenticate Tizonia for Google Play Music?

**Comment by juanrubio** [comment]
Hi!,

This is a good question. I don't think it is properly documented.

Tizonia supports Google Music via the great work done in simon-weber/gmusicapi. Unfortunately, there is no OAuth method currently implemented in gmusiapi. See:
https://github.com/simon-weber/gmusicapi/issues/426

In absence of that, I would suggest perhaps to use an app-specific password. See
https://support.google.com/accounts/answer/185833?hl=en

This method is known to work with gmusicapi and Tizonia.

**Comment by tizonia** [comment]
The documentation site has been updated and contains full details on the current authentication options.
