### ISSUE TITLE
[news] gst-omx now makes use of non-pre-announce buffer mode for OMX_UseBuffer

### ISSUE THREAD

**Issue by CapOM** [tizonia/tizonia-openmax-il#416]
Hi Juan, this is not a bug so you can close it. It is just to mention that gstreamer omx now makes use of non-pre-announce mode for OMX_UseBuffer. This has been developed by Guillaume Desmottes from Collabora for Zynqultrascaleplus SoC (it is not 1.2.0 but support it as an extension).

Then I just tested his work on Tizonia and it worked without any change so I wanted to let you know that :)

As you well know, this avoid to pre-announce buffers when using OMX_UseBuffer (which one save buffer copies).
Currently we use it only on input port for video decoder and encoder. On output port we still use the pre-announce way for now.

Also see https://bugzilla.gnome.org/show_bug.cgi?id=787093

--
Julien

**Comment by juanrubio** [comment]
Hi Julien!

Thanks for sharing this piece of information. Really interesting. The "no pre-announcement" mode in 1.2 was probably the most useful of all the additions to the spec. This fact that Guillaume's implementation in gst and Tizonia work using this mode really validates the implementation. So really nice to see!
