### ISSUE TITLE
Spotify playlist fails

### ISSUE THREAD

**Issue by gunlof** [tizonia/tizonia-openmax-il#435]
The first time I try to play somethging from Spotify this happens:

The command 
tizonia --spotify-playlist richter
finds the playlist and tries to play the first song but then exits with 
[OMX_ErrorInsufficientResources]
[OMX.Aratelia.audio_renderer.pulseaudio.pcm:port  0]

Do I need to change some configuration ?

**Comment by gunlof** [comment]
Sorry for

**Comment by gunlof** [comment]
Sorry for unnecessary posting, I had not set up the USB headset properly.

**Comment by juanrubio** [comment]
No issues!. Great to hear that you were able to work out the issue.

**Comment by juanrubio** [comment]
Hi @gunlof ,

Could you please provide more details? 

Are you running on a Raspberry Pi? USB audio perhaps?. If so, with a reasonably recent version of Tizonia, on Raspbian, you should be able to get USB audio going with this in your tizonia.conf:

```
[plugins]
# ALSA Audio Renderer
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = default
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Master

[tizonia]
# Tizonia player section
default-audio-renderer = OMX.Aratelia.audio_renderer.alsa.pcm
```

And in your $HOME/.asoundrc, an ALSA config like this one:
```
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}
```
