### ISSUE TITLE
Installer script doesn't copy tizonia.conf file

### ISSUE THREAD

**Issue by metalelf0** [tizonia/tizonia-openmax-il#441]
I tried installing tizonia on ubuntu xenial by running the installer script, it installed all packages and python deps successfully, but there is no `/etc/tizonia/tizonia.conf` file, to the cp to `$HOME/.config/tizonia/tizonia.conf` fails.

[EDIT]: `dpkg query -L tizonia-config` shows the file is at this path: `/etc/xdg/tizonia/tizonia.conf`.

**Comment by tizonia** [comment]
@metalelf0 : thanks for reporting!.

Should be fixed now.
