### ISSUE TITLE
Lots of ChannelError messages during Spotify playback

### ISSUE THREAD

**Issue by metalelf0** [tizonia/tizonia-openmax-il#443]
After succesfully authenticating to spotify and starting the playback of a playlist I see a lot of error messages like the following:

```
[Spotify] : 14:00:12.583 E [ap:4172] ChannelError(0, 1, playlist)
[Spotify] : 14:00:47.669 E [ap:4172] ChannelError(0, 1, playlist)
[Spotify] : 14:01:02.698 E [ap:4172] ChannelError(0, 1, playlist)
   Crossfit‏‏   ‍ : 62 tracks, 0 subscribers
     Artist : P!nk
     Album : What About Us (The Remixes)
     Track : What About Us - Cash Cash Remix (6 of 62)
     Duration :  3m:54s
     Bit rate : 320 kbps
     2 Ch, 44.1 KHz, 16:s:l
[Spotify] : 14:01:38.243 E [ap:4172] ChannelError(0, 1, playlist)
[Spotify] : 14:02:09.182 E [ap:4172] ChannelError(0, 1, playlist)
[Spotify] : 14:02:53.616 E [ap:4172] ChannelError(0, 1, playlist)
   Crossfit‏‏   ‍ : 62 tracks, 0 subscribers
     Artist : The Chainsmokers
     Album : Something Just Like This (Remix Pack)
     Track : Something Just Like This - Alesso Remix (7 of 62)
     Duration :  4m:13s
     Bit rate : 320 kbps
     2 Ch, 44.1 KHz, 16:s:l
```
Are these supposed to be here? If so, is there any way to hide them, like a log level setting? They don't cause any hiccups in music playback.

Thanks, let me know if I can provide any additional info.

**Comment by tizonia** [comment]
Yes, it is true. These simply log messages coming from the Spotify hose. Right now they can't be removed via configuration. They could be silenced or thrown to the tizonia log, with a small change in the tizonia code. That would make sense definitely.
