### ISSUE TITLE
google music: improve the matching of search results

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#445]
The idea is to use a fuzzy matching library to help with the matching of the query results with the user-provided string.

**Comment by tizonia** [comment]
This has been implemented in the 'plex' branch. It is now in master. Closing

**Comment by luislobo** [comment]
@tizonia How does the plex feature handle google music for fuzzy searching?

**Comment by tizonia** [comment]
Sorry, my message was perhaps a bit misleading. In Tizonia, the plex commands (as well as all the other commands, i.e google music, youtube, spotify, etc) internally implement fuzzy matching. That means your search strings don't need to be very precise in order to provide the 'expected' results.

e.g. 
```
--spotify-artist "quen"  (instead of 'queen')
```

The plex commands also support this.

**Comment by luislobo** [comment]
@tizonia I see, great, thank you! Yeah I was reading the code and found out after my message what you mention. Thank you for the quick response, too!
