### ISSUE TITLE
There is no tizonia.conf file

### ISSUE THREAD

**Issue by KontoruNoZakaru** [tizonia/tizonia-openmax-il#447]
After installed Tizonia on Ubuntu 17.10, I want to play some music on SoundCloud. But, after I follow the instruction on (http://tizonia.org/docs/soundcloud/). The tizonia.conf is doesn't exist on HOME/.config/tizonia/ directory.
Plz respond, I wanna feel play some music on Ubuntu Terminal....

Thanks.

**Comment by tizonia** [comment]
Hi!, thanks for getting in touch.

If you have installed Tizonia's snap, then should be able to do something like this:
```
mkdir -p $HOME/.config/tizonia
cp /snap/tizonia/15/etc/xdg/tizonia/tizonia.conf $HOME/.config/tizonia
```

**Comment by tizonia** [comment]
The tizonia.conf file will now be created on first run. The fix was in the 'plex' branch, which has now been merged to master. The new snap will be available in a few days (0.13.0). So closing this issue for now,

**Comment by breucker** [comment]
Hi
I just installed the app on ubuntu 18.04 and had the same problem : no .config/tizonia folder has been created... Is it the same bug ?

$ tizonia --version
 tizonia 0.16.0. Copyright (C) 2018 Juan A. Rubio

Thanks
Philippe

**Comment by juanrubio** [comment]
Hi Phillipe

Is this the snap or the Deb install?.

**Comment by breucker** [comment]
Hi,
It's the snap version, sorry I forget to mention it ;)

If I create the file manually in  `$HOME/.config/tizonia/tizonia.conf`,  and I launch tizonia it does not read the file either.
I actually figured it out (after re-reading the [README](https://github.com/tizonia/tizonia-openmax-il#configuration) more carefully... and some [github](https://github.com/tizonia/tizonia-openmax-il/issues/521) issues on that) :
Basically the snap configuration file is not in the same place that the deb version... 
This is confusing ! But it's snap fault I guess, not tizonia's ? In that case, snap is confusing...it's basically ignoring the basic unix file system organisation...

So I edited the `$HOME/snap/tizonia/current/.config/tizonia/tizonia.conf` and it works perfectly now ;)
Can we provide tizonia with alternate configuration files ?

Thanks anyway, tizonia is a great tool ;)

**Comment by juanrubio** [comment]
Phillipe (@breucker), sorry I forgot to reply.

Yes, you are correct. The confusion comes from the way Snap's confinement system works. Processes are run with a different value in the $HOME environment variable. See https://forum.snapcraft.io/t/accessing-home-directory-with-home-interface/6672 for some discussion about this.

Wrt alternate config files, there is a mostly undocumented environment variable that was used for this purpose: TIZONIA_RC_FILE. You could try and set it to point to an alternate config file. It has not been tested with Snaps, though. But it used to work with the regular deb-based install.
