### ISSUE TITLE
Bionic install from repository: libspotify12 missing

### ISSUE THREAD

**Issue by emk2203** [tizonia/tizonia-openmax-il#465]
When trying to install from the bintray repo for Ubuntu Bionic, `apt install tizonia-all` cannot install `libtizspotifysrc0`. This is because `libspotify12`, on which `libtizspotifysrc0` depends, is missing from the repo.

If the repo for mopidy is installed per instructions here: https://github.com/mopidy/libspotify-deb, libspotify12 is supplied and the install works as expected.

**Comment by tizonia** [comment]
Hi!, thanks for stopping by.

yes, this is expected. I.e. if you install Tizonia directly using the Bintray repo without the assistance of the 'install.sh' script. Please have a look the README.md file:

```
Please note that the recommended way to install Tizonia on a Debian-compatible system is by running the following command:

    $ curl -kL https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh | bash

    # Or its shortened version:

    $ curl -kL https://goo.gl/Vu8qGR | bash
```

If you have not made use of install.sh, then you probably will be missing the Python PIP dependencies. If in doubt, please have a look inside 'install.sh'

So I'm closing the issue, but please reopen in my understanding of you problem is incorrect.

**Comment by tizonia** [comment]
These are the Python dependencies that are needed for v0.13.0 (they are listed in the 'Upgrade' section in README.md)

```
sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet
```

**Comment by Kwaadpepper** [comment]
I had this issue, i used the curl script from the instalation page. I do had to install the libspotify from the repo manually looking at this  https://github.com/mopidy/libspotify-deb

**Comment by juanrubio** [comment]
Were you running Ubuntu Bionic or some other distro?

**Comment by Kwaadpepper** [comment]
Sorry, running Ubuntu 20.04

    No LSB m    odules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04 LTS
    Release:	20.04
    Codename:	focal

**Comment by juanrubio** [comment]
There have been some issues with the Focal packages that have been fixed today. See this issue for the details 
https://github.com/tizonia/tizonia-openmax-il/issues/743#issuecomment-634662733

I'm mentioning in case it might help

**Comment by Kwaadpepper** [comment]
Ok i juste purge ```libspotify12``` and ```libspotify-dev```, then remove https://apt.mopidy.com/buster.list which provides ```libspotify-12``` => https://docs.mopidy.com/en/latest/installation/debian/

And the installation is falling :

using this command ```curl -kL https://goo.gl/Vu8qGR | bash```

![Capture d’écran de 2020-05-28 11-21-56](https://user-images.githubusercontent.com/6019313/83123986-df1e3b00-a0d5-11ea-818f-251c91bdf5fc.png)

This is because ```libspotify``` is not provided by default Ubuntu repo or Tizonia.

I don't see how #743 would be related to this. 
Finally, this means any one wanting to install Tizonia using Focal would fail using this provided methods in the doc.

**Comment by juanrubio** [comment]
Hi @Kwaadpepper 

> I saw your installation succeed on a fresh Ubuntu install (Focal), but which repo is providing libspotify ?

libspotify's binaries are hosted in Mopidy's own APT repository (libspotify is proprietary code, so it can't be hosted in Debian's repos). Tizonia's installation script adds Mopidy APT archive during the installation. See the script's logic for that here:
https://github.com/tizonia/tizonia-openmax-il/blob/c563b79bb4b7cb2eea7dbef137d3a51936bfc79d/tools/install.sh#L98

The portion of the log in your screenshot does not display this part of the installation, so I can't tell what happened in your case.

The installation of Tizonia on Bionic has worked well for years now, and the Focal issues (that were related to arguably a bug in Ubuntu) are now resolved. 

I hope this answers your questions.

**Comment by Kwaadpepper** [comment]
Thank you for the feedback here is the full log

    DISTRIB_CODENAME=focal
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal
    Lecture des listes de paquets…
    Construction de l'arbre des dépendances…
    Lecture des informations d'état…
    build-essential est déjà la version la plus récente (12.8ubuntu1).
    curl est déjà la version la plus récente (7.68.0-1ubuntu2).
    git est déjà la version la plus récente (1:2.25.1-1ubuntu3).
    libffi-dev est déjà la version la plus récente (3.3-4).
    libssl-dev est déjà la version la plus récente (1.1.1f-1ubuntu2).
    libxml2-dev est déjà la version la plus récente (2.9.10+dfsg-5).
    libxslt1-dev est déjà la version la plus récente (1.1.34-4).
    apt-transport-https est déjà la version la plus récente (2.0.2ubuntu0.1).
    0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
    W: --force-yes est obsolète, veuillez plutôt utiliser l'une des options commençant par --allow.
    Atteint :1 http://archive.canonical.com/ubuntu focal InRelease
    Atteint :2 http://fr.archive.ubuntu.com/ubuntu focal InRelease
    Atteint :3 http://fr.archive.ubuntu.com/ubuntu focal-updates InRelease
    Atteint :4 http://download.virtualbox.org/virtualbox/debian focal InRelease
    Atteint :5 http://packages.azlux.fr/debian buster InRelease
    Atteint :6 http://fr.archive.ubuntu.com/ubuntu focal-backports InRelease
    Atteint :7 http://ppa.launchpad.net/atareao/atareao/ubuntu focal InRelease
    Atteint :8 http://packages.microsoft.com/repos/vscode stable InRelease
    Atteint :9 https://dl.winehq.org/wine-builds/ubuntu focal InRelease
    Atteint :10 https://dl.yarnpkg.com/debian stable InRelease
    Atteint :11 http://ppa.launchpad.net/costales/yaru-colors-folder-color/ubuntu focal InRelease
    Ign :12 https://dl.bintray.com/tizonia/ubuntu focal InRelease
    Atteint :13 http://ppa.launchpad.net/cybermax-dexter/sdl2-backport/ubuntu focal InRelease
    Ign :14 https://dl.bintray.com/sbt/debian  InRelease
    Atteint :15 http://ppa.launchpad.net/teejee2008/ppa/ubuntu focal InRelease
    Réception de :16 https://dl.bintray.com/tizonia/ubuntu focal Release [1 838 B]
    Réception de :17 https://dl.bintray.com/sbt/debian  Release [815 B]
    Atteint :18 http://security.ubuntu.com/ubuntu focal-security InRelease
    2 653 o réceptionnés en 2s (1 106 o/s)
    Lecture des listes de paquets…
    Lecture des listes de paquets…
    Construction de l'arbre des dépendances…
    Lecture des informations d'état…
    python3-dev est déjà la version la plus récente (3.8.2-0ubuntu2).
    python3-pip est déjà la version la plus récente (20.0.2-5ubuntu1).
    0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
    Requirement already up-to-date: gmusicapi in /usr/local/lib/python3.8/dist-packages (13.0.0)
    Requirement already up-to-date: soundcloud in /usr/local/lib/python3.8/dist-packages (0.5.0)
    Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.8/dist-packages (2020.5.8)
    Requirement already up-to-date: pafy in /usr/local/lib/python3.8/dist-packages (0.5.5)
    Requirement already up-to-date: pycountry in /usr/local/lib/python3.8/dist-packages (19.8.18)
    Requirement already up-to-date: titlecase in /usr/local/lib/python3.8/dist-packages (0.12.0)
    Requirement already up-to-date: pychromecast in /usr/local/lib/python3.8/dist-packages (5.3.0)
    Requirement already up-to-date: plexapi in /usr/local/lib/python3.8/dist-packages (3.6.0)
    Requirement already up-to-date: spotipy in /usr/local/lib/python3.8/dist-packages (2.12.0)
    Requirement already up-to-date: fuzzywuzzy in /usr/local/lib/python3.8/dist-packages (0.18.0)
    Requirement already up-to-date: eventlet in /usr/local/lib/python3.8/dist-packages (0.25.2)
    Requirement already up-to-date: python-Levenshtein in /usr/local/lib/python3.8/dist-packages (0.12.0)
    Requirement already up-to-date: joblib in /usr/local/lib/python3.8/dist-packages (0.15.1)
    Requirement already satisfied, skipping upgrade: requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0 in /usr/lib/python3/dist-packages (from gmusicapi) (2.22.0)
    Requirement already satisfied, skipping upgrade: protobuf>=3.0.0 in /usr/lib/python3/dist-packages (from gmusicapi) (3.6.1)
    Requirement already satisfied, skipping upgrade: appdirs>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (1.4.3)
    Requirement already satisfied, skipping upgrade: oauth2client>=1.1 in /usr/lib/python3/dist-packages (from gmusicapi) (4.1.2)
    Requirement already satisfied, skipping upgrade: proboscis>=1.2.5.1 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (1.2.6.0)
    Requirement already satisfied, skipping upgrade: python-dateutil!=2.0,>=1.3 in /usr/lib/python3/dist-packages (from gmusicapi) (2.7.3)
    Requirement already satisfied, skipping upgrade: mutagen>=1.34 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (1.44.0)
    Requirement already satisfied, skipping upgrade: validictory!=0.9.2,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (1.1.2)
    Requirement already satisfied, skipping upgrade: MechanicalSoup>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (0.12.0)
    Requirement already satisfied, skipping upgrade: gpsoauth>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (0.4.1)
    Requirement already satisfied, skipping upgrade: decorator>=3.3.1 in /usr/local/lib/python3.8/dist-packages (from gmusicapi) (4.4.2)
    Requirement already satisfied, skipping upgrade: simplejson>=2.0 in /usr/lib/python3/dist-packages (from soundcloud) (3.16.0)
    Requirement already satisfied, skipping upgrade: fudge>=1.0.3 in /usr/local/lib/python3.8/dist-packages (from soundcloud) (1.1.1)
    Requirement already satisfied, skipping upgrade: casttube>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from pychromecast) (0.2.1)
    Requirement already satisfied, skipping upgrade: zeroconf>=0.25.1 in /usr/local/lib/python3.8/dist-packages (from pychromecast) (0.26.2)
    Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from spotipy) (1.14.0)
    Requirement already satisfied, skipping upgrade: dnspython>=1.15.0 in /usr/local/lib/python3.8/dist-packages (from eventlet) (1.16.0)
    Requirement already satisfied, skipping upgrade: greenlet>=0.3 in /usr/local/lib/python3.8/dist-packages (from eventlet) (0.4.15)
    Requirement already satisfied, skipping upgrade: monotonic>=1.4 in /usr/lib/python3/dist-packages (from eventlet) (1.5)
    Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3/dist-packages (from python-Levenshtein) (45.2.0)
    Requirement already satisfied, skipping upgrade: lxml in /usr/lib/python3/dist-packages (from MechanicalSoup>=0.4.0->gmusicapi) (4.5.0)
    Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.4 in /usr/lib/python3/dist-packages (from MechanicalSoup>=0.4.0->gmusicapi) (4.8.2)
    Requirement already satisfied, skipping upgrade: pycryptodomex>=3.0 in /usr/local/lib/python3.8/dist-packages (from gpsoauth>=0.2.0->gmusicapi) (3.9.7)
    Requirement already satisfied, skipping upgrade: ifaddr in /usr/local/lib/python3.8/dist-packages (from zeroconf>=0.25.1->pychromecast) (0.1.6)
    Lecture des listes de paquets…
    Construction de l'arbre des dépendances…
    Lecture des informations d'état…
    Aucune version du paquet libspotify12 n'est disponible, mais il existe dans la base
    de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
    ou qu'il n'est disponible que sur une autre source

    E: Le paquet « libspotify12 » n'a pas de version susceptible d'être installée
    Oops. Something went wrong!

Your link makes it clear to me now, it tests that ```/etc/apt/sources.list.d/mopidy.list```, but even i had it (I did not rember a that time) on was disabled, so it just skipped this part and failed of course.

This is because when a repo is disabled it coments lines : 

    # Mopidy APT archive
    # Built on Debian 9 (stretch), compatible with Ubuntu 18.04 LTS
    # deb http://apt.mopidy.com/ buster main contrib non-free
    # deb-src http://apt.mopidy.com/ buster main contrib non-free

I suggest the script would force overwrite the repo or force to add it. Or just check it is uncommented. Or even simpler print a warning message to the user. This was confusing to me. It may help others.

Thank you again :+1:
