### ISSUE TITLE
how to fix "FATAL. Could not init OpenMAX IL : OMX_ErrorInsufficientResources"

### ISSUE THREAD

**Issue by systmrrr** [tizonia/tizonia-openmax-il#466]
my error ;

mstf@beko:~/İndirilenler$ tizonia --spotify-playlist PLAYLIST
tizonia 0.4.0. Copyright (C) 2016 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

FATAL. Could not init OpenMAX IL : OMX_ErrorInsufficientResources

**Comment by tizonia** [comment]
Hi!. Would you be able to upgrade? The version of tizonia that you are running is very old. Current version is v0.13.0.

Thanks

**Comment by systmrrr** [comment]
oh no :D

**Comment by tizonia** [comment]
Oops. Unfortunately, I stopped releasing i386 debs long time ago, since most distros are discontinuing i386. 

However, if you are in a position to install 'snapd' (https://docs.snapcraft.io/core/install), then you will be able to download the i386 snap on the latest version of Tizonia.

**Comment by tizonia** [comment]
I think I can close this for now.

**Comment by pulmo** [comment]
I had same issue on v0.13.0 (Arch Linux, install tizonia-all-git from AUR)

**Comment by tizonia** [comment]
@pulmo: It is interesting that you are running v0.13.0. The last time I tried I had problems to build the non-git package (tizonia-all), so this is still on v0.12.0. The problems were with some of Tizonia's AUR dependencies.

I assume your Arch installation is 64-bit. Would you be able to provide other details, like the contents of the component paths in your $HOME/.config/tizonia/tizonia.conf:

```
[ilcore]
component-paths = ...
```

**Comment by pulmo** [comment]
@tizonia Sorry, my bad ‒ in my tizonia.conf was only `soundloud.oauth_token`. App works after I copied `/etc/xdg/tizonia/tizonia.conf`.

Thanks for awesome app!

**Comment by tizonia** [comment]
@pulmo : great to hear that you got this figured out!
