### ISSUE TITLE
tizonia: cannot handle whitespaces in its config file

### ISSUE THREAD

**Issue by inecho** [tizonia/tizonia-openmax-il#468]
### Description

Setting up the OAuth token was not that easy. After retrieving the token using the tutorial, tizonia was not able to recognize it. The problem was that i had a whitespace in the beginning and at the end of the line.
not working: `_soundcloud.oauth_token = X-XXXXXX-XXXXXX-XXXXXXXXXX_`
working: `soundcloud.oauth_token = X-XXXXXX-XXXXXX-XXXXXXXXXX`

the underlines are indicating the whitespaces.

### Versions

```
$ tizonia --version 
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>
-------
$ tizonia --debug
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v0.7.82]
```

### Installation Method Used

`sudo apt install tizonia-player`

### Additional Information

this issue can be easly handled using the .strip() function of python on a string

**Comment by tizonia** [comment]
Hi, thanks for trying the software!

Yes, this looks like a genuine issue the config file parser that needs to be fixed

**Comment by tizonia** [comment]
A fix has committed to 'develop'. It will be merged into 'master' right before the next release of Tizonia.
