### ISSUE TITLE
Debian Testing/Buster (10) not available

### ISSUE THREAD

**Issue by seantdg** [tizonia/tizonia-openmax-il#474]
### Description

No repository available for Debian Testing/10 - Buster.

### Steps to Reproduce

On update - 

1) edit /etc/apt/sources.list to contain:

```
deb https://dl.bintray.com/tizonia/debian buster main
```

2) apt-get update

Observe:

```
W: The repository 'https://dl.bintray.com/tizonia/debian buster Release' does not have a Release file.                                                                                     
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.                                                                                        
N: See apt-secure(8) manpage for repository creation and user configuration details.                                                                                                        
E: Failed to fetch https://dl.bintray.com/tizonia/debian/dists/buster/main/binary-i386/Packages  404  Not Found                                                                             
E: Some index files failed to download. They have been ignored, or old ones used instead.                       
```

On install - 

1) Ensure you are running Debian Buster

2) Follow installation instructions

Observe (based on validation in ./tools/install.sh):

```
Can't find a supported Debian or Ubuntu-based distribution.
```

Version: 0.13.0

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to write this.

I agree. I think for v0.14.0 we will add Buster to the list of Bintray repos. This also means, we will stop supporting Jessie, to keep constant the number Debian releases supported at any time (currently: Jessie and Stretch,  from v0.14.0, Stretch and Buster).

**Comment by tizonia** [comment]
Closing this now. The release of 0.14.0 is in progress and packages will be ready soon.

**Comment by JukoLife** [comment]
Kali/linux user here, also waiting for Kali support ;_; @tizonia

**Comment by tizonia** [comment]
@KebabLord : I've created a new issue for Kali. Would you be able to test if the solution outlined in #510 works?.
