### ISSUE TITLE
google music: Playlist shows 0 tracks in Tizonia, has tracks on Google Play web interface

### ISSUE THREAD

**Issue by dimonic** [tizonia/tizonia-openmax-il#478]
Attempting to play a saved playlist on Google Play Music.

Tizonia selects another random playlist to play. The desired playlist shows as "0 tracks", but on the web Google Play Music shows a number of tracks, all of which play normally.

### Steps to Reproduce

1. $ tizonia --gmusic-playlist "Island music"
/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[Google Play Music] [Authenticating] : 'with cached auth token'
[Google Play Music] [Retrieving library] : 'dominic.amann@gmail.com'. 
[Google Play Music] [Playlist] 'Thumbs Up' (16 tracks).
[Google Play Music] [Playlist] 'step of montreal' (0 tracks).
[Google Play Music] [Playlist] 'steph 11 May 2014 Queue' (0 tracks).
[Google Play Music] [Playlist] 'Classic Indie rock ' (9 tracks).
[Google Play Music] [Playlist] 'New stuff I like' (0 tracks).
[Google Play Music] [Playlist] 'Classic/Prog Rock' (0 tracks).
[Google Play Music] [Playlist] 'Punk Classics' (0 tracks).
[Google Play Music] [Playlist] 'Dance' (0 tracks).
[Google Play Music] [Playlist] 'My 60s' (0 tracks).
[Google Play Music] [Playlist] '11 November 2016 Queue' (0 tracks).
[Google Play Music] [Playlist] 'Psyche Rock' (0 tracks).
[Google Play Music] [Playlist] 'Best Singles' (0 tracks).
[Google Play Music] [Playlist] 'Rock and Roll History' (0 tracks).
[Google Play Music] [Playlist] 'Island music' (0 tracks).
[Google Play Music] [Playlist] 'Indie rawk' (54 tracks).
[Google Play Music] [Playlist] 'I dare you to listen to this' (8 tracks).
[Google Play Music] [Playlist] 'Fun stuff' (14 tracks).
[Google Play Music] [Playlist] 'Pretty songs' (19 tracks).
[Google Play Music] [Playlist] 'sheer stupid pop songs' (9 tracks).
[Google Play Music] [Playlist] 'the best of the 80's' (63 tracks).
[Google Play Music] [Playlist] 'cheesy AM radio' (15 tracks).
[Google Play Music] [Playlist] 'Best ever songs' (92 tracks).
[Google Play Music] [Playlist] 'Classic ' (18 tracks).
[Google Play Music] [Playlist] 'Urban music' (2 tracks).
[Google Play Music] [Playlist] 'Pull up the Covers' (35 tracks).
[Google Play Music] [Playlist] 'top albums of all time' (94 tracks).
[Google Play Music] [Playlist] 'Dance! Dance! ' (9 tracks).
[Google Play Music] 'Island music' not found (or is empty). Feeling lucky?.
[Google Play Music] Playing 'cheesy AM radio'.
[Google Play Music] [Tracks in queue] '15'.
[Google Play Music] [Connected] : 'dominic.amann@gmail.com'.
[Google Play Music] [Connected] : 'dominic.amann@gmail.com'.
   Fleetwood Mac : Dreams

**Expected behavior:** Plays "Kaiso Newscast" (1st track on Island music playlist).

**Actual behaviour:** Plays a random playlist.

**Reproduces how often:** 100%

### Versions
0.13.0.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

### Installation Method Used

Bintray debs

### Additional Information

Using a Google Family account, the playlists that show up as 0 tracks are only those created by me, and all of my lists show as 0 tracks. My wife's lists have song counts. Yet the credentials for signing in are mine.
![image](https://user-images.githubusercontent.com/1778490/38330779-778de0ec-381f-11e8-984b-174c321a658a.png)

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report this.

Sounds like a genuine issue. Let's try to diagnose it. Would you be able to check which version of the 'gmusicapi' Python module you have installed, like this?:

```
$ pip freeze | grep gmusicapi
```

This should display:
```
gmusicapi==11.0.1
```

After that, try exporting this environment variable on your shell:
```
$ export TIZONIA_GMUSICPROXY_DEBUG=1
```
This will enable some debug logging. Would you be able to repeat the command and copy the output here?

**Comment by tizonia** [comment]
@dimonic: Never mind. I've managed to reproduce it :-). There is a fix now in the 'develop' branch. Should be in a new release in a couple of weeks time.

Thanks again for flagging this issue.
