### ISSUE TITLE
segmentation fault with snap and spotify

### ISSUE THREAD

**Issue by elopio** [tizonia/tizonia-openmax-il#479]
### Description

I'm trying to play a spotify playlist using the tizonia snap in ubuntu 18.04. This results in:
/snap/tizonia/131/bin/tizonia-snap-wrapper.sh: line 22:  2094 Segmentation fault      (core dumped) $SNAP/usr/bin/tizonia "$@"

### Steps to Reproduce

1. `$ tizonia --spotify-playlist "La patchanka"`
2. Enter my password.
3. Crash

**Expected behavior:** [What you expect to happen]
Not crash.

**Actual behaviour:** [What actually happens]
Crashes :)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time

### Versions

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
```
$ tizonia --version
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
```

```
$ tizonia --debug
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v0.7.82]
```

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Installation Method Used

Snap

**Comment by juanrubio** [comment]
Hi!, thanks for reporting this.

Yes, definitely it is a genuine issue. It is only present when Tizonia is installed from the snap package. Will need to investigate when this got broken in the snap.

**Comment by juanrubio** [comment]
Another user has reported it in the tizonia-snap repo:
- https://github.com/tizonia/tizonia-snap/issues/2

I will keep both issues open for now until I know more.

**Comment by juanrubio** [comment]
@elopio 

As said before, this is a snap-specific issue. This crash occurs when tizonia is trying to access /var/tmp/..., and receives an 'apparmor' denial. See the details at:
https://forum.snapcraft.io/t/tizonia-snap-apparmor-denied-suggestion-adjust-program-to-use-tmpdir-or-tmp/4951

I don't know yet what is the standard solution for this problem, so waiting for an answer to my question on the snapcraft forum.
