### ISSUE TITLE
RSS Feed in official Website is broken

### ISSUE THREAD

**Issue by Fake4d** [tizonia/tizonia-openmax-il#480]
### Description

RSS in the html of http://tizonia.org/ is linking to http://tizonia.com/feed.xml
Every article (on the correct http://tizonia.org/feed.xml) is linked with http://tizonia.com

### Steps to Reproduce

1. See the RSS in the offical website

2. Check http://tizonia.org/feed.xml

**Expected behavior:** Correct the links to http://tizonia.org/

### Additional Information

Used the firefox and miniflux to check the rss!

**Comment by tizonia** [comment]
This issue has been fixed. 

Thanks!
