### ISSUE TITLE
Spotify Playlists with Single Quotes in Name Can't Be Found

### ISSUE THREAD

**Issue by tohuw** [tizonia/tizonia-openmax-il#486]
### Description

If a playlist has a `'` character, e.g. `tohuw's playlist`, then it seems there's no way to correctly call it from tizonia.

### Steps to Reproduce

1. Create a playlist in Spotify named "tohuw's playlist"
2. Attempt `tizonia --spotify-playlist "tohuw\'s playlist"`
3. Attempt more variants such as `"tohuw's playlist"`

**Expected behavior:** The named playlist is played

**Actual behaviour:** Finding the playlist fails and the "feeling lucky" sequence starts, or it hangs a long time after the "*n* playlists found" message and starts outputting the name and track count of each playlist if step 3 above is attempted

**Reproduces how often:** 100% reproducible

### Versions

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

v0.14.0 on Ubuntu 18.04 LTS

### Installation Method Used

Snap package

### Additional Information

None

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report this issue.

I believe this is now fixed in 05d734b (develop branch). This commit adds approximate string matching, which was long overdue in the Spotify plugin! Might even fix most of #471.

I will be cutting a new release in 2, maybe 3 weeks.

Thanks!
