### ISSUE TITLE
Spotify: tizonia stalls when trying to open a playlist

### ISSUE THREAD

**Issue by dxlight** [tizonia/tizonia-openmax-il#490]
### Description

When I try to play a playlist from spotify tizonia stalls after connecting to spotify

### Steps to Reproduce

1. tizonia -s --spotify-playlist "playlist"

**Expected behavior:**

tizonia should start playing the playlist

**Actual behaviour:** 

tizonia stalls after the following steps:

[Spotify] [Connecting] : 'user@email.com'.
[Spotify] : Spotify cache location: '/var/tmp/tizonia-root-spotify-user@mail.com'
[Spotify] : 09:55:59.768 I [ap:1752] Connecting to AP ap.spotify.com:4070
[Spotify] : 09:55:59.769 I [user_cache:135] UserCache::initiateGetUsers() will query for 1 users
[Spotify] : 'ldsfdurhnfdushrndiisnwiuhfn' logged in
[Spotify] : 09:55:59.774 I [offline-mgr:2084] Storage has been cleaned
[Spotify] : 09:55:59.795 I [ap:1226] Connected to AP: 104.199.64.94:4070

**Reproduces how often:** 

Always

### Versions

0.13.0
0.14.0

### Installation Method Used

Bintray debs

### Additional Information

Everything worked until a few days ago.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report this issue.

Unfortunately, it looks like a problem that comes from Spotify itself. Tizonia relies on the deprecated 'libspotify', which Spotify stopped maintaining back in 2015. 

Other people are also experiencing the breakage in libspotify's playlist support.
https://github.com/volumio/Volumio2/issues/1552
https://github.com/mopidy/mopidy-spotify/issues/182

Unfortunately, there is not an easy replacement right now. I will keep my eyes open for an alternative. Or perhaps we are lucky and Spotify decides to restore the playlist feature. Fingers crossed!

**Comment by dxlight** [comment]
so this makes tizonia completely broken for spotify, right? :(

**Comment by tizonia** [comment]
That's correct for now, but only (fingers crossed) until a solution is implemented.

That solution appears to exist (https://github.com/kingosticks/mopidy-spotify/pull/1/commits). It seems libspotify is just unable to retrieve the playlist contents anymore. But it's still possible to retrieve a list of tracks in a playlist using the web API (e.g. using https://github.com/plamere/spotipy). Then, each individual track can still be streamed individually using libspotify.

**Comment by tizonia** [comment]
@dxlight : FYI, Tizonia's Spotify capabilities are being restored (and actually augmented). I'm currently using the Spotify Web API to replace the search functionality that appears to be broken now in libspotify.

So the current plan is to add the following new search functions to Tizonia:
```
$ tizonia --spotify-tracks
$ tizonia --spotify-album
$ tizonia --spotify-artist
```
Also, the playlist search capability will be restored (at least partially).
```
$ tizonia --spotify-playlist
```

Let's hope that the audio streaming capabilities in libspotify continue to work for the foreseeable future!

**Comment by tizonia** [comment]
#492 and #493 are tracking the integration of Spotify Web API in Tizonia.

**Comment by tizonia** [comment]
Closing this now. Spotify Web API functionality has now been merged to master.
