### ISSUE TITLE
AUR: missing Libspotify 

### ISSUE THREAD

**Issue by gmata11** [tizonia/tizonia-openmax-il#499]
Hi,

Actually I can't install tizonia on my Manjaro distro. When I tried to install it, I became dependent on the libspotify package. How can I install it?

![image](https://user-images.githubusercontent.com/25740908/41708080-eceb2644-753f-11e8-97c5-e48ffbe391f2.png)

Thanks!

**Comment by tizonia** [comment]
Hi!, thanks for stopping by.

I've also noticed this myself just recently. It looks like the libspotify package has disappeared recently from the AUR. Unfortunately, this is an Arch-specific problem. 

See some discussion about this here:
- https://www.reddit.com/r/archlinux/comments/8q5vle/cant_get_mopidyspotify_to_work_libspotify_is_gone/
- https://github.com/tizonia/tizonia-openmax-il/issues/499

The good news is that you can still install Tizonia on Arch using the snap package. 

See:
- https://github.com/tizonia/tizonia-openmax-il#snap-package
- https://docs.snapcraft.io/core/install-arch-linux
- https://wiki.archlinux.org/index.php/Snapd

Note that Tizonia's configuration file lives in a different place when the software is installed with the snap package:
- https://github.com/tizonia/tizonia-openmax-il#configuration

**Comment by gmata11** [comment]
Hi!

Thanks! I will try it!

**Comment by StoppingBuck** [comment]
@tizonia Has the dependency on libspotify been resolved? Because if we can remove the dependency from the AUR and tizonia will still build successfully then everything will be resolved :)

**Comment by tizonia** [comment]
@StoppingBuck : I believe libspotify is still missing in the AUR. Tizonia can be built without spotify support, which would allow a Tizonia package in the AUR with all the other functionalities.

I think that would be a good solution for now, until someone decides to put libspotify back in the AUR. I'll try to look into that in the next few days.

**Comment by StoppingBuck** [comment]
@tizonia Yup, it's missing, and while [mopidy hosts a legacy libspotify](https://mopidy.github.io/libspotify-archive/), I think a better solution would be to edit the PKGBUILD for tizonia in the AUR to not depend on libspotify. Question is whether that would disable Spotify support or whether you already have achieved Spotify support through other means than the libspotify :)

For me personally, I just want to use tizonia with Plex so it's a bit silly that it's Spotify-related shenanigans preventing me from doing so :stuck_out_tongue:

**Comment by absolutejam** [comment]
This is a working PKGBUILD from an older version of the AUR package if that helps?

[PKGBUILD.txt](https://github.com/tizonia/tizonia-openmax-il/files/2149419/PKGBUILD.txt)

**Comment by tizonia** [comment]
@StoppingBuck , @absolutejam 

I appreciate your interest. The option I'm contemplating right now is updating Tizonia's PKGBUILDs to disable Spotify support, which is an option already supported in Tizonia's build system. Because of that, this is a tiny effort that only affects the Tizonia PKGBUILD packages, and with that, we will have a native version of Tizonia that still works with most of the features on Arch.

For users that still want to use Tizonia with Spotify on Arch, I'm afraid I have to refer them to the Snap package that works really well on Arch and I'm planning support in the future.

If libspotify comes back to the AUR, I will be more than happy to update Tizonia's AUR packages and bring Spotify support back.

**Comment by tizonia** [comment]
@StoppingBuck : thanks, I also noticed it a few days ago. I'll try to find some time to update the packages to the latest version (0.15.0)

**Comment by tohn** [comment]
I don't if this is related, but I also had to install python2-spotipy python-levenshtein to get it working with spotify.

**Comment by tizonia** [comment]
@tohn : Thanks for trying those packages. This is part of the test I need to do before pushing a new version Tizonia's packages in the AUR. So could you please confirm that Spotify playback works fine  Tizonia 0.15.0 using python2-spotipy?

**Comment by tohn** [comment]
@tizonia yes, after I installed this package I could listen to spotify.

**Comment by tizonia** [comment]
OK, I'm closing this issue now. The AUR packages have now been refreshed and currently track v0.15.0. Please make sure you remove the old version of Tizonia's AUR package before upgrading (to avoid the issue documented in #485).

Sorry for the embarrassingly slow response time on this one!
