### ISSUE TITLE
Gmusic-Unlimited Aratelia.audio_source.http:port0 OMX_ErrorInsufficientResources

### ISSUE THREAD

**Issue by thomaslawton91** [tizonia/tizonia-openmax-il#503]
### Description

When attempting to stream from gmusic-unlimited the player hangs for about 30 seconds and then fails with 
```
~ » tizonia --gmusic-unlimited-artist buju                                               sofubi@mbpro
tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>                                     

[Google Play Music] [Connecting] : 'thomaslawton91@gmail.com'.
[Google Play Music] [Authenticating] : 'with cached auth token'
[Google Play Music] [Artist] 'Buju Banton'.
[Google Play Music] [Artist] 'Buju'.
[Google Play Music] [Artist] 'Prince Buju'.
[Google Play Music] [Artist] 'Buju Razor'.
[Google Play Music] [Artist] 'Buju Man'.
[Google Play Music] [Artist] 'Buju Volcov'.
[Google Play Music] [Artist] 'Delly Ranx & Buju Banton'.
[Google Play Music] [Artist] 'Jah Henchman, Buju Banton, Triple D'.
[Google Play Music] [Track] 'Gal Dem Flex' by 'Buju'.
[Google Play Music] [Track] 'Batty Rider' by 'Buju'.
[Google Play Music] [Track] 'Grudge You For' by 'Buju'.
[Google Play Music] [Track] 'Goldspoon' by 'Buju'.
[Google Play Music] [Track] 'Catch a Vibe' by 'Buju'.
[Google Play Music] [Track] 'We Dem Guys' by 'Buju'.
[Google Play Music] [Track] 'A Day in Lagos' by 'Buju'.
[Google Play Music] [Tracks in queue] '7'.
[Google Play Music] (RuntimeError) : maximum recursion depth exceeded in cmp

tizonia exiting (OMX_ErrorInsufficientResources).                                                     

 [OMX.Aratelia.audio_source.http:port:0]                                                              
 [OMX_ErrorInsufficientResources] 
```

### Steps to Reproduce

1. run --gmusic-unlimited-artist Buju 
2. run --gmusic-unlimited-tracks 'Driver A'
3. all --gmusic commands have same result
4. attempted with Soundcloud with no error

**Expected behavior:** [What you expect to happen]
To get streaming audio from GMusic unlimited

**Actual behaviour:** [What actually happens]
Outputs error codes
```
tizonia exiting (OMX_ErrorInsufficientResources).                                                     

 [OMX.Aratelia.audio_source.http:port:0]                                                              
 [OMX_ErrorInsufficientResources]  
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
Happening 100% of the time on this machine although with a near identical setup on another box this works just fine

### Versions
```
~ » tizonia --debug                                                                      sofubi@mbpro
tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]
```
Running on Ubuntu 18.04

### Installation Method Used

Ran installer script for installation

### Additional Information
Again, this is an issue that appears to be isolated to --gmusic commands as --soundcloud and --youtube both work successfully.
It is worth mentioning that I'm installed on a MacOS machine but am single booting so not sure if that could introduce any drivers issues but I'm not experiencing anything specifically sound-wise across the system so I'm assuming this is isolated.

**Comment by thomaslawton91** [comment]
Update to this, I did find another issue that mentions that this could be an issue with credentials. I attempted to create a test app password and use that and the problem has not been solved.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time.

Sounds like some of the Python dependencies in your system might need updating. 

```
sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet && sudo -H pip install git+https://github.com/plamere/spotipy.git --upgrade
```
I normally run this once or twice a week. New versions of the above Python packages are released very frequently by their maintainers.

Let me know if that works for you.

**Comment by thomaslawton91** [comment]
Hey there, this did in fact fix my issue. Thank you so much for the quick response and the awesome project!!
