### ISSUE TITLE
googlemusic settings help

### ISSUE THREAD

**Issue by kaniawave** [tizonia/tizonia-openmax-il#505]
Dear all... I have more like a call for a help. Maybe it's stupid, but I don't know how to configure the `gmusic.device_id`. What should I write there? Where can I find the device id?

I'm on Ubuntu 16.04. 

Thank you guys and the creator for an amazing work! 

Kania

**Comment by tizonia** [comment]
Hi! thanks for getting in touch.

Actually, this is not documented because it is a feature of the underlying gmusiacpi, but you can type some dummy value in there and execute tizonia. When the id is invalid, you can a rather useful message
like this:

```
izonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Google Play Music] [Connecting] : 'user@gmail.com'.
[Google Play Music] [Authenticating] : 'with user credentials'
[Google Play Music] (InvalidDeviceId) : Invalid device_id blahblah.Your valid device IDs are:
<list of your account's device ids>
```

So after that, you just need to copy one of the valid ids returned.

I hope this helps!

**Comment by kaniawave** [comment]
Ok, I get this:
`/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[Google Play Music] [Authenticating] : 'with user credentials'
[Google Play Music] (NotLoggedIn) : 

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
`

**Comment by kaniawave** [comment]
Ok... You were right. I got the device IDs to choose from. Second one worked. 
![image](https://user-images.githubusercontent.com/15866068/43675515-f3e23e46-97e1-11e8-83bf-36302724970b.png)

Thanks again! Great work!
