### ISSUE TITLE
Tizonia can't find my Spotify playlists

### ISSUE THREAD

**Issue by arozans** [tizonia/tizonia-openmax-il#506]
### Description

Tizonia doesn't find Spotify's playlists.

### Steps to Reproduce

1. tizonia --spotify-playlist <playlist-name>

**Expected behavior:**
Tizonia shows playlist search list and plays found playlist.

**Actual behaviour:** [What actually happens]
Tizonia show exactly 51 playlists from my library (without the one I'm asking for)
and then throws:

```
[Spotify] (ValueError) : Playlist not found or no audio tracks in playlist : <playlist-name>

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```

**Reproduces how often:** 
For playlists not showing in search list - always

### Versions

0.15.0

### Installation Method Used

from official site, Ubuntu 16.04

**Comment by tizonia** [comment]
Hi!, thanks for taking the time.

Tizonia is currently only able to play the user's 'public' playlists. If the playlist is private, tizonia can't currently play it.

It is explained in this post:
http://tizonia.org/news/2018/06/15/release-0-15-0/

If you know the owner of a public playlist, tizonia can access the playlist by specifying the owner in addition to the playlist name.

I hope that helps!

**Comment by arozans** [comment]
Thanks, that explains everything. I think this should be mentioned in README. Waiting patiently for the next release with support for private playlists - without that tizonia is much less useful.

**Comment by tizonia** [comment]
Thanks this is a good suggestion. In reality the website is an extension of the README file, mostly to keep the README as short as possible. But I will add a more visible reference to try to draw people's attention to the latest news on the website.

**Comment by tizonia** [comment]
A reference to Tizonia's website has been added to README.md's NEWS section to remind people to also visit the website.
