### ISSUE TITLE
Soundcloud Token problem

### ISSUE THREAD

**Issue by KebabLord** [tizonia/tizonia-openmax-il#512]
[Seems like](https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform) soundcloud oauth token is no longer receivable. Which means soundcloud for new tizonia users is not usable. What to do?

**Comment by tizonia** [comment]
Hi!, Thanks for bringing this up.

Oops! I had no idea. Not sure what is going on but I hope it is only temporary!. I will definitely keep an eye to see how it unfolds.

**Comment by KebabLord** [comment]
It been more than 1 year, it will not come back probably. Old tizonia users got no problem but new users like me who discovered tizonia in 2018 can not use it. Please add an alternative login system, i want to use tizonia with my own soundcloud account ;_;

**Comment by tizonia** [comment]
@KebabLord 

I'm closing this issue. 

Please note that I've just created a new SoundCloud account and I've been able to retrieve an oauth_token using the 'Connect Tizonia with SoundCloud' procedure:
http://www.aratelia.com/index.php/open-source/77-main/88-connect-with-soundcloud#
