### ISSUE TITLE
Tizonia Snap exits with OMX_ErrorInsufficientResources error

### ISSUE THREAD

**Issue by notatamas** [tizonia/tizonia-openmax-il#513]
### Description

Tizonia Snap exits with OMX_ErrorInsufficientResources error:

➜  ~ tizonia --youtube-audio-mix-search "the animals"
tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[YouTube] (IOError) : ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/snap/tizonia/206/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]

### Versions

Ubuntu 18.04.1
Gnome 3.28.2
Tizonia 0.15.0
Pulseaudio 11.1

[Boost 1_58]
[TagLib 1.9.1]
[MediaInfoLib - v0.7.82]

### Installation Method Used

Snap package

**Comment by tizonia** [comment]
Hi!, thanks for reporting this issue.

It looks like this problem occurs when tizonia is installed from the snap. It could be due to a now slightly older version of youtube-dl that comes with it. Not present when Tizonia is installed from deb packages and with up-to-date yotube-dl. 

I am going to refresh the snap package to see if the problem goes away.

**Comment by tizonia** [comment]
Yep, that was the problem. I've just promoted to the 'stable' channel the last automated build that took place a couple of days ago. This version (208, 209, or 210 depending on your architecture) now works fine:

```
sudo snap refresh tizonia
```

Let me know how it goes.

**Comment by notatamas** [comment]
Wow, that was fast. All good now. Thanks.

**Comment by tizonia** [comment]
Thanks to you. Closing this issue now.

**Comment by notatamas** [comment]
I am getting the same error recently.

**Comment by juanrubio** [comment]
Hi @notatamas 

Is it exactly the same error message as reported on the first message in this thread?. If it is different, could you please copy the error log here? Thanks.

**Comment by notatamas** [comment]
It seems to be exactly the same, but I am copying it here anyway:

tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[YouTube] (IOError) : ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/snap/tizonia/212/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]

**Comment by juanrubio** [comment]
Interesting, do you know which version of the snap package is installed on your system?

You could try to force a refresh
```
sudo snap refresh tizonia
```
So the latest published snap versions are:

**armhf** 
Submission date:  2018-11-01
Revision: 213

**amd64** 
Submission date:  2018-11-01
Revision: 212

**i386** 
Submission date:  2018-11-01
Revision: 211

**Comment by notatamas** [comment]
➜  ~ sudo snap refresh tizonia
snap "tizonia" has no updates available
➜  ~ tizonia --version        
tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

**Comment by juanrubio** [comment]
Thanks, I've kicked-off another build of the snaps in Snapcraft. New packages will be in the repos in a few hours. I'll ping here when they are and maybe you can try another refresh.

**Comment by notatamas** [comment]
Thank you. I truly appreciate your work.

**Comment by juanrubio** [comment]
214 (i386) and 215 (amd64) are now in the Snapcraft repos. I hope that brings youtube back.

**Comment by notatamas** [comment]
All good now. Thanks again.

**Comment by tizonia** [comment]
Great!, thanks for flagging the issue.
