### ISSUE TITLE
Question for Debian armhf architecture compatible

### ISSUE THREAD

**Issue by SweetMei25** [tizonia/tizonia-openmax-il#518]
Hello.
I would like to compile this project for armhf architecture.
Is this possible (using your current manual installation guide)?
Please kindly message me.
Thanks

**Comment by tizonia** [comment]
Hi!, thanks for stopping by.

I suppose you are asking if the manual installation guide in https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md contains directions to cross-compile tizonia. The answer to that question is no. BUILDING.md only contains directions for native compilation.

However, in the tools directory, you can find the scripts that are used to create the Debian packages of Tizonia for the various distros supported, which includes Debian armhf distros. The main script to look at is:
- https://github.com/tizonia/tizonia-openmax-il/blob/master/tools/tizonia-qemu-debootstrap-env

The tool has a help message which is fairly up-to-date:

```
/tizonia-qemu-debootstrap-env   
tizonia-qemu-debootstrap-env 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>.

GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Usage : tizonia-qemu-debootstrap-env [-b|--bootstrap] [-c|--chroot] [-d|--deps] [-m|--make] [-p|--publish] [-r|--rootfs] [-t|--update] [-u|--uninstall]
       -b            : Bootstrap the chroot build environment (purges installed tizonia packages, updates chroot deps, deletes old build folders, and transfer a fresh tizonia repo).
       -c            : Enter the chroot environment (for manual work inside the chroot).
       -d            : Install this program's dependencies (only needed the first time this program is run).
       -m            : Build all debian packages (builds the packages, assumes a bootstrapped environment).
       -p            : Publish all debian packages to Bintray (requires Tizonia's Bintray API_KEY and Juan's GPG passphrase).
       -r            : Create the chroot folder, and download and install the rootfs in it.
       -s            : Create a snap package inside the chroot.
       -t            : Refresh the tizonia repo inside the chroot (pulls latest changes into the chroot's repo).
       -u            : Uninstall (purge) all currently installed Tizonia packages in the chroot.



-----------------
 Typical workflow
-----------------
 1.- Install this program's dependencies: 
     $ DISTRO=debian RELEASE=jessie ARCH=armhf ./tizonia-qemu-debootstrap-env --deps
 2.- Download rootfs: 
     $ DISTRO=debian RELEASE=jessie ARCH=armhf ./tizonia-qemu-debootstrap-env --rootfs
 3.- Bootstrap the development environent inside the chroot: 
     $ DISTRO=debian RELEASE=jessie ARCH=armhf ./tizonia-qemu-debootstrap-env --bootstrap
 4.- Build packages: 
     $ DISTRO=debian RELEASE=jessie ARCH=armhf ./tizonia-qemu-debootstrap-env --make
 5.- Publish packages: 
     $ DISTRO=debian RELEASE=jessie ARCH=armhf ./tizonia-qemu-debootstrap-env --publish

 Other actions like '--uninstall', '--update' or '--chroot' are optional.
```

**Comment by SweetMei25** [comment]
Thanks for your quick response!
Much appreciated.
I will follow your guide step by step.
Thanks

**Comment by SweetMei25** [comment]
Hello.
Thanks.
OS: 
Armbian Stretch 
mainline kernel 4.14.y
https://www.armbian.com/orange-pi-zero/
If this system is not supported or I need to install another system, then could you please tell me the supported system?
Much appreciated.
Regards

Sprietsma

**Comment by SweetMei25** [comment]
I just wanted to install the tizonia project on Orange Pi Zero device
Current OS is Armbian Stretch.
Any system is welcome.
Just want to successfully install on Orange Pi Zero device.
Thanks

**Comment by tizonia** [comment]
I see. I'm not familiar myself with Armbian but looking at the Orange Pi website it looks like you could try other distros as well. 

My suggestion would be to install one of the available distros for Orange Pi that is also supported by Tizonia, which would be either Ubuntu, Debian or Arch, and use one of the installation methods available on those distros (rather than trying to cross-compile Tizonia yourself, which is an activity that is orders of magnitude more complex)

If you choose Debian or Ubuntu, have look at this link:
https://github.com/tizonia/tizonia-openmax-il#debian--ubuntu--raspbian

If you choose Arch, follow this:
https://github.com/tizonia/tizonia-openmax-il#arch-user-repository-aur

And in both cases (Debian/Ubuntu or Arch), you could also try to install Tizonia using the Snap package:
https://github.com/tizonia/tizonia-openmax-il#snap-package

**Comment by SweetMei25** [comment]
Great!
Thank you very much.

I will try in this way!
And get back to you with the result soon.

Thank you very much for providing excellent solutions every time.

Regards

Sprietsma
