### ISSUE TITLE
Does not read tizonia.conf file.

### ISSUE THREAD

**Issue by alazyworkaholic** [tizonia/tizonia-openmax-il#521]
I'm having the same problem as jaguero21 in issue 397

I just installed the tizonia snap on ubuntu 18.04 i386. Youtube works fine. gmusic works, but only if I supply the user, password, and device_id on the command line. I used inotifywait -e open ~/.config/tizonia/tizonia.conf to check, and tizonia is definitely NOT reading its config file. I tried specifying $TIZONIA_RC_FILE, putting it in /etc/tizonia/tizonia.conf, but it still won't work. Tizonia 0.15.0

### Description

tizonia does not read ~/.config/tizonia/tizonia.conf

### Steps to Reproduce

1. Copy the default tizonia.conf from /snap/tizonia/current/etc/xdg/tizonia/tizonia.conf to ~/.config/tizonia/tizonia.conf
2. Change gmusic.user .password and .device_id to the appropriate values. No " or whitespace.
3. in a separate terminal, run inotifywait -e open ~/.config/tizonia/tizonia.conf
4. Run tizonia --gmusic-station pop

**Expected behavior:** [What you expect to happen]
A google music playlist should be retrieved and music should play.
The inotifywait terminal should indicate the tizonia.conf file was opened.

**Actual behaviour:** [What actually happens]
Told I need to provide a Google Play Music user name. Tizonia quits.
The inotifywait terminal does not show the conf file was opened (it does if I open the file)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.

### Versions
0.15.0

### Installation Method Used
sudo snap install tizonia
(on ubuntu bionic i386)

### Additional Information
Suggestion: it might be useful to add a --config-file option to view/specify the file.
It works if I provide all gmusic config options at the command line.
Very sure my file is at $HOME/.config/tizonia/tizonia.conf

**Comment by alazyworkaholic** [comment]
Ok, I moved it to the correct location and all works perfectly. I love tizonia.

Nonetheless, I think there's actually 2 issues then.

1. `tizonia --help config` is mostly inaccurate for a snap install. It says an example configuration file can be found in `/snap/tizonia/current/etc/xdg/tizonia/tizonia.conf`, but tells me to put it in `$HOME/.config/tizonia/tizonia.conf`.
If this output didn't suggest a place I might have dug into the docs to find out, but I hardly use/understand snaps, so I didn't think to put it anywhere other than the suggested location. It would be helpful to include the snap path in the documentation you reference in the output of `tizonia --help config`.

2. I tried to specify the file in the earlier location with the first option which is to set `$TIZONIA_RC_FILE`, but that still didn't work.

Maybe there could be a verbose startup option that would log where, among other things, the attempted config path could be logged?

**Comment by tizonia** [comment]
@alazyworkaholic 

You are absolutely right, the help --config message needs fixing. I will update it to reduce the confusion. The message is largely incorrect nowadays. Tizonia has been placing the tizonia.conf file in the right location for one or two releases now, so that the user does not need to bother about that. But it would be a good idea to inform the user of the location of that file. I'll check this too.

**Comment by tizonia** [comment]
Closing this the inital question was answered. I'm creating a new issue for the --help config message: see #523
