### ISSUE TITLE
WTF! Why so dependencies?!

### ISSUE THREAD

**Issue by LinArcX** [tizonia/tizonia-openmax-il#530]
Please follow[ unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy).(Keep The Fucking things simple!) i just want to install a music player not a whole bunch of dependencies.
after 15 minutes and install 9 packages, the installation failed.

**Comment by tizonia** [comment]
Quoting from the issue template:
```
Have you read Tizonia's Code of Conduct? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:
https://github.com/tizonia/tizonia-openmax-il/blob/master/CODE_OF_CONDUCT.md
```

Tizonia is not (only) a music player:
https://github.com/tizonia/tizonia-openmax-il/blob/master/PROJECT.md

Also, if you want a simpler installation method, use the snap package:
https://github.com/tizonia/tizonia-openmax-il#snap-package

or the docker image:
https://hub.docker.com/r/tizonia/docker-tizonia/

Finally, this project also welcomes contributions (that respect the code of conduct):
https://github.com/tizonia/tizonia-openmax-il/blob/master/CONTRIBUTING.md

**Comment by Josh5** [comment]
Well that right there is an unhelpful load of bollocks.
Are you here for a rant or to actually get something fixed?

The "Unix philosophy" is anti monolithic (as stated in your link). It is exactly what you are complaining about, writing code that expands on the work of other projects. You should do some homework before you comment buddy.
