### ISSUE TITLE
docs: document Spotify authentication options

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#539]
See #531 for the discussion.

Issues with Facebook-login Spotify accounts need to be documented in the following places:
- README.md
- tizonia.conf
- Project's official documentation
- Website

**Comment by Justinzobel** [comment]
How do we login with Facebook?

**Comment by tizonia** [comment]
Hi @Justinzobel 

Thanks for your question. Unfortunately, Tizonia does not currently support Facebook logins. 

This requires something like https://github.com/adamcik/oauthclientbridge running on a web server that I can control.

**Comment by Justinzobel** [comment]
Bugger, onto the next Spotify CLI client.

**Comment by tizonia** [comment]
As I recall, you can still use Tizonia. You need to generate a device or (app ?) password. 
I've never done it myself, as I don't have a Spotify login, but I believe other people have done this to use with Tizonia:
https://community.spotify.com/t5/Accounts/Cannot-Create-Device-Password/td-p/1240597
https://www.dummies.com/social-media/spotify/set-a-device-password-to-stream-with-spotifys-hi-fi-partners/

**Comment by tizonia** [comment]
The Tizonia documentation has been updated and contains full details on the current options.
