### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by Sur3** [tizonia/tizonia-openmax-il#540]
Hi I try to get my AMD VCE working using Mesa's OpenMax State Tracker and it seems to need this tizonia-library. I'm a bit confused that I need to build a cloud music player when all I need is the OpenMax library, shouldn't that be separate repositories?!?

Anyway when trying to build this repository I get the following error:

***** autoconf *****
***** PWD: /var/tmp/portage/media-libs/tizonia-9999/work/tizonia-openmax-il-master/libtizplatform
***** autoconf --force

configure.ac:87: error: possibly undefined macro: AM_PATH_LOG4C
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by tizonia** [comment]
Hi, thanks for getting in touch.

I think you should be able to choose which OpenMAX IL implementation you want to use with Mesa's OpenMAX state tracker. Tizonia is OpenMAX IL version 1.2 (the newer, provisional specification from Khronos) and Bellagio is 1.1.2 (the older, stable specification). 

If you have no particular interest in any specific version of OpenMAX IL, then I would suggest you use Bellagio. It will be easier.

If you still want/need to go ahead with OpenMAX IL v1.2 and Tizonia, then you probably will need to understand how to build Tizonia without the cloud player and possibly a few other subprojects that are part of this repository.

Here are the instructions on how to configure the project to remove some of those items:
https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md#conditional-compilation-of-sub-projects

Having said that and to be fair, the current configuration options do not provide enough granularity to remove all the sub-projects that are not needed by someone that requires only the bare OpenMAX IL framework.

**Comment by tizonia** [comment]
> undefined macro: AM_PATH_LOG4C

Sorry, I forgot. I think this is an indication that dev package of log4c is not installed on your system.

**Comment by Sur3** [comment]
Ok think I'll wait for that 0.17.0 milestone then. It's pretty weird AMD implemented OpenMax years ago but no one seems to have used it and VA-API for video-encoding is kinda broken and the newer AMF only became available to Linux three month ago and is therefore even less supported. xD

**Comment by tizonia** [comment]
I'm closing this issue now. Ultimately, #541 will take care of the more specific configuration use cases.
