### ISSUE TITLE
tizgmusicproxy.py: Keep on getting a syntax error (Non-ASCII character '\xe2')

### ISSUE THREAD

**Issue by SolarAquarion** [tizonia/tizonia-openmax-il#542]
File "/usr/lib/python2.7/site-packages/tizgmusicproxy.py", line 1128
SyntaxError: Non-ASCII character '\xe2' in file /usr/lib/python2.7/site-packages/tizgmusicproxy.py on line 1128, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by tizonia** [comment]
Hi!, thanks for reporting this. 

I believe there are a couple of stray bytes in the middle of a comment block.
