### ISSUE TITLE
tizonia exiting (OMX_ErrorComponentNotFound)

### ISSUE THREAD

**Issue by maste9** [tizonia/tizonia-openmax-il#557]
### Description
tizonia doesn't connect to any service and throws exception 

> tizonia exiting (OMX_ErrorComponentNotFound).
> Unable to verify the component list

### Steps to Reproduce

1.  e.g. input `tizonia --spotify-playlist "Best of 2018" `
2. you'll receive the above mentioned exception

**Expected behavior:** Play any music

**Actual behaviour:** application stops with exception

**Reproduces how often:** application didn't work at all yet

### Versions
tizonia 0.17.0

Debug Info:
	    * [Boost 1_65_1]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Installation Method Used
First trial with snap, but when it didn't work (didn't find config file in the diverse places ...) I removed it with 'snap remove tizonia'
Now used the recommended installation method with install.sh

### Additional Information
Tried to use other services than spotify but received exactly the same message.

These are the related libs on my system
> 
> libtizaacdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizalsapcmrnd0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizcastclient0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizchromecast0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizchromecastrnd0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizcore0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizdbus-c++-bin/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizdbus-c++0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizdirble0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizflacdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizfr0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizfw0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizgmusic0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizhttprnd0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizhttpsrc0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizmp3dec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizmp3enc0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizmp3meta0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizmpgdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizoggdmux0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizonia0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizopusdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizopusfiledec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizpcmdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizplatform0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizplex0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizpulsepcmrnd0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizrmproxy0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizsdlivrnd0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizsoundcloud0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizspotify0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizspotifysrc0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizvorbisdec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizvp8dec0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizwebmdmux0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
> libtizyoutube0/bionic,now 0.17.0-1 amd64  [Installiert,automatisch]
>

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues.

Regarding the snap configuration file, this is the location:
```
$HOME/snap/tizonia/current/.config/tizonia/tizonia.conf 
```
Many people get confused about this, but unfortunately, this is how Snaps works with regards config files, etc.

Regarding the Debian installation using `install.sh`, 
```
tizonia exiting (OMX_ErrorComponentNotFound).
Unable to verify the component list
```
this could be an indication that install.sh encounter some issues (e.g. apt-get failed at some point, etc). Did you see any error messages in its output?. You could simply re-run it and post here the whole output, and I'll help you troubleshoot.

Another possibility is this configuration element 
```
component-paths
```
in your $HOME/.config/tizonia/tizonia.conf contains incorrect information. Please post here its contents and we'll have a look.

**Comment by maste9** [comment]
> Another possibility is this configuration element
> 
> ```
> component-paths
> ```
> 
> in your $HOME/.config/tizonia/tizonia.conf contains incorrect information. Please post here its contents and we'll have a look.

Thank you very much! That was the crucial hint!
I seem to have copied the config-file from the snap installation to $HOME/.config/tiziona/tiziona.conf so that component-paths contained a variable instead of
`component-paths = /usr/lib/x86_64-linux-gnu/tizonia0-plugins12;`
After correcting this everything works fine.

I already suspected the snap/native change as a possible cause I would never have checked the config-files spontaneously ^^

So, this problem's solved. Thx for your kind support.
