### ISSUE TITLE
Error with python when trying to search for youtube audios

### ISSUE THREAD

**Issue by Eduruiz** [tizonia/tizonia-openmax-il#566]
### Description
When trying to play youtube audios for the first time (already using spotify to play music) I got the error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tizyoutubeproxy.py", line 32, in <module>
    import pafy
  File "/usr/lib/python2.7/site-packages/pafy/__init__.py", line 14, in <module>
    if "test" not in sys.argv[0]:
AttributeError: 'module' object has no attribute 'argv'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

### Steps to Reproduce
I'm not completly sure, just installed the package from AUR (Arch Linux) and tried to play some youtube with `tizonia --youtube-audio-search "search term"`

**Reproduces how often:**
Everytime

### Versions
tizonia 0.17.0.
* [Boost 1_69]
* [TagLib 1.11.1]
* [MediaInfoLib - v18.12]

Arch Linux - 4.20.8-arch1-1-ARCH

### Installation Method Used
Installed the non git version from AUR with yay.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues.

It looks like you have an old version of 'pafy' running on your system.

The code that your traceback is referring to was removed in Pafy version 0.5.3
See https://github.com/mps-youtube/pafy/issues/162

The latest version is 0.5.4:
```
pip2 show pafy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: pafy
Version: 0.5.4
Summary: Retrieve YouTube content and metadata
Home-page: http://np1.github.io/pafy/
Author: np1
Author-email: np1nagev@gmail.com
License: LGPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Required-by: 
```

**Comment by tizonia** [comment]
Closing this issue now. Please re-open if you think you have the latest pafy.

**Comment by Eduruiz** [comment]
Thanks for pointing it out @tizonia, I'm not on that machine right now, but as I never used pafy before this lead me to think that the AUR package dependencies are outdated, so I checked [tizonia AUR package](https://aur.archlinux.org/packages/tizonia-all/) and it shows the [python2-pafy-git](python2-pafy) as a dependency, that one has version `v0.3.82`, so I think the right dependency would be [python-pafy-git](https://aur.archlinux.org/packages/python-pafy-git/) that is version `0.5.4` as you pointed.

**Comment by tizonia** [comment]
Strange. Tizonia has a dependency on 'python2-pafy', which is (or was) from the official repositories, not an AUR package. The AUR web interface is linking it to pytho2-pafy-git, I don't know why (I'm not a regular Arch user).

See:
https://github.com/tizonia/tizonia-openmax-il/blob/e04790e08c99358e7cc000b01d0c298167f1bf86/pkgbuild/PKGBUILD.tizonia-all#L12

In my Manajaro install, I have pytho2-pafy version 0.5.3.1, so maybe this package has been removed from the official repos?
```
$ pacman -Qs pafy
local/python2-pafy 0.5.3.1-1
    Python API for YouTube
```

I'm not sure python-pafy-git will work since this I believe is a Python 3 package (Tizonia requires Python2)

**Comment by Eduruiz** [comment]
Strange, just after install tizonia I only got this:

```
pacman -Qs pafy
local/python2-pafy-git v0.3.82r1.g061d9b5-1
    Python API for YouTube
```
and I can only find the community version of pafy

I tried `python-pafy-git` but it really not worked (as suspected).
So I end up upgrading python pafy with pip:
```
pip2 install --user pafy -U
```
And now everything works! :tada: 
I asked in the AUR package page if it's really outdated or I'm just missing something, if the maintainer says that this is the intended version I think we should update the dependencies for a new package with the right version, problem is, this package doesn't exist in the AUR and I have no clue on maintaining a package.

**Comment by juanrubio** [comment]
It sounds like python2-pafy has disappeared from the official repositories and 'yay' probably ended up pulling python2-pafy-git while doing some dependency resolution of its own.

I think you did well flagging 'python2-pafy-git' as outdated. If you look at the package history, it seems to be using a very old version of pafy, from 2016:
https://aur.archlinux.org/cgit/aur.git/log/?h=python2-pafy-git

Interestingly, the package has been updated recently (2019-01-16), although the version of pafy being tracked is still the same old 2016 version.

I think we should wait and see if the maintainer pushes another update to upgrade the package to the latest pafy release.

**Comment by NeodarZ** [comment]
Hi, I've re upload the package [python2-pafy](https://aur.archlinux.org/packages/python2-pafy/) and it's up to date. So all work, normally...

**Comment by tizonia** [comment]
@NeodarZ 

Thanks for updating python2-pafy!
