### ISSUE TITLE
Spotify: core dumped with 'tizonia --spotify-album "living on a prayer"

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#569]
### Description

Tizonia crashes with this command

```
 tizonia --spotify-album 'living on a'
```

### Steps to Reproduce

As stated.

**Expected behavior:**

Not crash, some error message.

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

0.17.0

### Installation Method Used

All.

**Comment by tizonia** [comment]
Fixed in the 'develop' branch. Will be merged to master and closed before the next release.
