### ISSUE TITLE
docs: document player shortcuts

### ISSUE THREAD

**Issue by fhchl** [tizonia/tizonia-openmax-il#570]
### Description

I cannot find any documentation for the shortcuts to control next (n), previous track(p), mute(m) etc. 

**Expected behavior:** Section in documentation that describes the players functionality.

**Actual behaviour:** No documentation.

**Comment by fhchl** [comment]
So far I figured out:

- n: next track
- p: previous track
- space: play/pause
- m: mute

How can one skip through a track?

**Comment by fhchl** [comment]
Seems like I jumped a bit too quick here. tizonia -h keyboard documents the shortcuts.

Still, I would suggest documenting them on the docs site.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues.

I'm glad you found the command-line help text

Yes, the official documentation is really out-of-date and currently very insufficient. I would love to receive contributions though. If you are interested, let me know!

**Comment by tizonia** [comment]
Sorry, I forgot to answer:

> How can one skip through a track?

It's not yet implemented, see #438

**Comment by tizonia** [comment]
Closing this issue now. Keyboard Shortcuts are now part of the official docs:
http://docs.tizonia.org/usage/keyboard.html

Thanks for reporting!
