### ISSUE TITLE
[SoundCloud] (UnicodeDecodeError) : 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by StefanBRas** [tizonia/tizonia-openmax-il#574]
### Description

All soundcloud functions will fail with the error :

`[SoundCloud] (UnicodeDecodeError) : 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)`

when the search terms has special characters (like æøå) or characters with accents or tilde-thing (like ñ, é, ö).

Further more these characters are omitted in outputs - for example in song names.

### Steps to Reproduce
To reproduce error resulting in tizonia exiting:
1. Use one of the --sound-* commands where the argument/seach term has a special character in it

To reproduce special characters being omitted in output 
1. run `tizonia --soundcloud-tracks "baby bino hver dag"`
2. See that the song "Blæst Hver Dag (prod. lille hg) : baby bino" is shown as "Blst Hver Dag (prod. lille hg) : baby bino"

**Expected behavior:** 

That Tizonia would not throw an error and exit and that Tizonia would show special characters.

**Actual behaviour:** 

Tizonia throws an error and exit and Tizonia does not show special characters.

**Reproduces how often:**

Everytime.

### Versions

tizonia --debug output:

```
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v0.7.82]
```

On Ubuntu 16.04.6 LTS.

### Installation Method Used

I think i used the suggested installation script.

### Additional Information

It looks like the same error as #130 just with the soundcloud plugin instead of gmusic.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues.

Yes, it is very possible that this issue is present in the soundcloud client code. Will look into it. Thanks!

**Comment by BeMacized** [comment]
Can confirm the same behaviour when using `--plex-audio-tracks` in place of `--soundcloud-tracks`.

**Comment by tizonia** [comment]
@BeMacized 

Thanks!, I have created another issue for the Plex Unicode errors. See #580

**Comment by tizonia** [comment]
I can see the error coming from the official SoundCloud Python package (but one could argue that the issue should be resolved by the calling code).
  
```
[SoundCloud] (UnicodeDecodeError) : 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/joni/temp/lib/python2.7/site-packages/tizsoundcloudproxy.py", line 317, in enqueue_tracks
    filter='streamable')
  File "/usr/local/lib/python2.7/dist-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python2.7/dist-packages/soundcloud/request.py", line 123, in make_request
    data = namespaced_query_string(remove_files_from_dict(params))
  File "/usr/local/lib/python2.7/dist-packages/soundcloud/request.py", line 61, in remove_files_from_dict
    file_free[key] = value.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```

I've googled around and I can see that the following 'hack' fixes the error (at least it does in my own tests with UK or US locales):
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

I'll think about adding this.

**Comment by tizonia** [comment]
@StefanBRas

Would you be able to try this solution in your environment?

I.e. edit `/usr/lib/python2.7/dist-packages/tizsoundcloudproxy.py` to add these three lines as below

```
from operator import itemgetter
from fuzzywuzzy import process

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# For use during debugging
# import pprint

FORMAT = '[%(asctime)s] [%(levelname)5s] [%(thread)d] ' \
         '[%(module)s:%(funcName)s:%(lineno)d] - %(message)s'

```

**Comment by StefanBRas** [comment]
After inserting the three lines I can now search with special characters, however they only show in some of the output.

For example if i run

`tizonia --soundcloud-tracks "blæst hver dag"`

It will play the song but the output to the terminal will be:
```
[SoundCloud] [Connecting] : '1-154538-101723219-1f2d4ad2438a3'.
[SoundCloud] [Track] 'Blst Hver Dag (prod. lille hg).
...
[SoundCloud] [Tracks in queue] '86'.
[SoundCloud] [Connected] : 'blæst hver dag'.
[SoundCloud] [Connected] : 'blæst hver dag'.
   Blst Hver Dag (prod. lille hg) : baby bino
     Year : 2017
     Duration : 2m:03s
     Likes count : 529
     Permalink : https://soundcloud.com/baby-bino/blaest-hver-dag-prod-lille-hog
     License : all-rights-reserved
     Audio Stream : 128 kbit/s, 44100 Hz
     MPEG Layer : III, w/o CRC
     Mode : joint (MS/intensity) stereo, no emphasis
     2 Ch, 44.1 KHz, 16:s:b 
```
Showing that the special character "æ" is omitted in the second line, but not omitted in the "[Connected"] lines. It's then again omitted in the line after.

This is obviously a much less annoying bug than not being able to include the characters in a search.

**Comment by tizonia** [comment]
Thanks for trying that.

Yes, the output you see there is coming from a mix of Python and C/C++ code. To make the entire application unicode-friendly is a larger fix than just making sure that the Python code does not throw annoying exceptions that prevent people from listening to their music.

I will close this issue with the fix that resolves the exception and I will create a separate issue to expose the general unicode problem.

**Comment by tizonia** [comment]
Closing this for now, the code is now in master.
