### ISSUE TITLE
Plex: (UnicodeDecodeError) : 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#580]
### Description

UnicodeDecodeErrors in the Plex client, as reported by user @BeMacized  in https://github.com/tizonia/tizonia-openmax-il/issues/574#issuecomment-484064883

**Comment by nikhiljha** [comment]
Happens for me on Fedora as well. It doesn't like Unicode at all/only takes ASCII or it will error.

```
[me@mypc ~]$ tizonia --plex-audio-album 文明
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Plex] [Connecting] : 'http://redacted/'.
[Plex] [Album search in server] : 'http://redacted'. 
[Plex] (UnicodeDecodeError) : 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by tizonia** [comment]
@nikhiljha  thanks for the feedback. 

Yes, it is a common problem across the Python wrappers in Tizonia that access the various online services. I think we'll make this a priority for the next release.

**Comment by tizonia** [comment]
@BeMacized, @nikhiljha 

Would you be able to try the following solution in your environment?

I.e. edit `/usr/lib/python2.7/dist-packages/tizplexproxy.py` to add three lines as below

```
from fuzzywuzzy import process
from fuzzywuzzy import fuzz

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# For use during debugging
# import pprint

FORMAT = '[%(asctime)s] [%(levelname)5s] [%(thread)d] ' \
         '[%(module)s:%(funcName)s:%(lineno)d] - %(message)s'

```

**Comment by BeMacized** [comment]
Apologies, I completely forgot about this issue and just rediscovered it today.
I have applied the change mentioned above, but it causes a different error to be logged.

When running `tizonia --plex-audio-tracks "ふたりごと"`, the output is as follows:
```
...
[Plex] [Track search in server] : 'https://plex.bemacized.net'. 
[Plex] (KeyError) : u'\u3075'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

**Comment by cwt** [comment]
I just have this problem on spotify and fixed by set the LC_ALL to en_US.UTF-8

@BeMacized what's your current locale settings? could you try this command:
`LC_ALL=en_US.UTF-8 tizonia --plex-audio-tracks "ふたりごと"`
or
`LC_ALL=ja_JP.UTF-8 tizonia --plex-audio-tracks "ふたりごと"`

**Comment by BeMacized** [comment]
@cwt My current locale settings are all set to en_US.UTF-8: 
```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
(Running Manjaro, in case that's relevant)

As for the output of the two commands: 
- The first one outputs the exact same as before (KeyError)
- The second one outputs the same, but with an additional warning:
`sh: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)`
