### ISSUE TITLE
[Suggestion] Shuffle option

### ISSUE THREAD

**Issue by Psycoguana** [tizonia/tizonia-openmax-il#585]
Hey, first of all, thanks a lot for this software. It's really amazing!

There is a feature I'd love to see, and if you could implement it, it would be great!
Is it possible to have a playlists (like a soundcloud playlist) play in shuffle mode?

I think it would improve the experience greatly, when playing big playlists.

And again, thanks a lot for the software already provided!

**Comment by tizonia** [comment]
Hi!, thanks for trying the software and for taking the time to make suggestions

Have you tried the `-s|--shuffle` option? I believe this should work unless something is broken in the SoundCloud module.

```
tizonia --help global 

Global options:
  -h [ --help ] [=arg(=help)] Print a usage message for a specific help topic 
                              (e.g. global, openmax, server, spotify, 
                              googlemusic, soundcloud, etc).
  -v [ --version ]            Print the version information.
  -r [ --recurse ]            Recursively process a given path.
  -s [ --shuffle ]            Shuffle the playlist.
  -d [ --daemon ]             Run in the background.
  -c [ --cast ] arg           Cast to a Chromecast device (arg: device name or 
                              ip address). Available in combination with Google
                              Play Music, SoundCloud, Dirble, YouTube, Plex and
                              HTTP radio stations.
  -b [ --buffer-seconds ] arg Size of the buffer (in seconds) to be used while 
                              downloading streams. Increase in case of cuts in 
                              gmusic, scloud, dirble, youtube or plex.
```

**Comment by Psycoguana** [comment]
Damn, I looked for it, but didn't find the option.
Yes, that works perfectly, thanks!
