### ISSUE TITLE
Cannot render audio on linux mint

### ISSUE THREAD

**Issue by jambo58** [tizonia/tizonia-openmax-il#588]
# Cannot render audio on linux mint

### Description
When attempting to play on linux mint 19.1 (cinnamon DE) i get this error
```
No protocol specified
xcb_connection_has_error() returned true

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]
 [OMX_ErrorInsufficientResources]



```

### Steps to Reproduce

1. tizonia --plex-audio-artist mm9 (flac file)
```
tizonia --plex-audio-artist mm9 
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Plex] [Connecting] : 'http://12.12.12.34:32400'.
[Plex] [Artist search in server] : 'http://12.12.12.34:32400'. 
[Plex] Playing 'MM9'.
[Plex] [Track] 'New Chemistry' [flac].
[Plex] [Track] 'Trains' [flac].
[Plex] [Track] 'Flies and Spiders' [flac].
[Plex] [Track] 'Watch You Fly' [flac].
[Plex] [Track] 'Around My Neck' [flac].
[Plex] [Track] 'Collapsing' [flac].
[Plex] [Track] 'Army of Me' [flac].
[Plex] [Track] 'Talking To Himself' [flac].
[Plex] [Track] 'Living Dumb' [flac].
[Plex] [Track] 'A Devil Once Said' [flac].
[Plex] [Track] 'SOSOS' [flac].
[Plex] [Track] 'Let it Take Over' [flac].
[Plex] [Track] 'Run' [flac].
[Plex] [Track] 'Half A Mind' [flac].
[Plex] [Track] 'They Murder' [flac].
[Plex] [Track] 'Drama Drama' [flac].
[Plex] [Track] 'Celebrate The Failure' [flac].
[Plex] [Track] 'The Colour Fear' [flac].
[Plex] [Track] 'They Murder' [flac].
[Plex] [Track] 'Girls Like Guns' [flac].
[Plex] [Track] 'Trains     Daleese Remix' [flac].
[Plex] [Tracks in queue] '21'.
[Plex] [Connected] : 'mm9'.
[Plex] [Connected] : 'mm9'.
No protocol specified
xcb_connection_has_error() returned true

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]
 [OMX_ErrorInsufficientResources]


```
**Expected behavior:** 
Audio to play
**Actual behaviour:** 
error and no audio output
**Reproduces how often:** 
every time

### Versions
tizonia 0.18.0.
Linux Mint  19.1 (Ubuntu) Cinnamon DE

### Installation Method Used
snap

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.
```
May  5 17:23:40  kernel: [ 5797.097369] audit: type=1400 audit(1557041020.035:130): apparmor="DENIED" operation="open" profile="snap.tizonia.tizonia" name="/proc/13732/mounts" pid=13732 comm="audio_source" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May  5 17:23:40  kernel: [ 5797.101837] audit: type=1400 audit(1557041020.039:131): apparmor="DENIED" operation="connect" profile="snap.tizonia.tizonia" name="/run/uuidd/request" pid=13732 comm="audio_source" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
May  5 17:23:44  kernel: [ 5801.253505] audit: type=1400 audit(1557041024.191:132): apparmor="DENIED" operation="capable" profile="snap.tizonia.tizonia" pid=13732 comm="audio_renderer" capability=2  capname="dac_read_search"
May  5 17:23:44  kernel: [ 5801.253514] audit: type=1400 audit(1557041024.191:133): apparmor="DENIED" operation="capable" profile="snap.tizonia.tizonia" pid=13732 comm="audio_renderer" capability=1  capname="dac_override"
```

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report an issue.

> May  5 17:23:40  kernel: [ 5797.097369] audit: type=1400 audit(1557041020.035:130): apparmor="DENIED" operation="open" profile="snap.tizonia.tizonia" name="/proc/13732/mounts" pid=13732 comm="audio_source" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

I think this is a known problem in the Snap system. It has to do with a confined snap that tries to access Pulseaudio while running on top of some 'non-mainstream' window manager (like Awesome WM in my case, and Cinnamon in your case). This snapd issue is still open, I need to chase it again:

See https://launchpad.net/ubuntu/+source/snapd/+bug/1689539

In the meantime, you should be able to install the Debian version of Tizonia since Mint 19.1 is based on Bionic.
https://github.com/tizonia/tizonia-openmax-il#debian--ubuntu--raspbian

You just need to add 'tessa' to the install script, at this location

https://github.com/tizonia/tizonia-openmax-il/blob/38237636c1b92a10f33a5434984cb7c79f45cbe0/tools/install.sh#L62



Unfortunately, I have not chased this issue hard

**Comment by jambo58** [comment]
thanks that works and additionally i recently tried to run the snap package with a non root user and it worked. great project by the way, looking forward to the plex chromecast support
