### ISSUE TITLE
YouTube: Shuffle option does not work

### ISSUE THREAD

**Issue by Psycoguana** [tizonia/tizonia-openmax-il#592]
Hey! I'm sorry if this has been answered before, I looked and didn't find a thing.

I know it's possible to shuffle songs using `tizonia -s`, but whenever I try `tizonia -s --youtube-audio-playlist PLAYLIST_URL`, it plays it in order. Is there something I'm missing?

The option works just fine with SoundCloud btw.

**Comment by tizonia** [comment]
Hi!, thanks for making the effort of reporting an issue.

Actually, I think this is a bug (weird that I have never noticed!). It should work the same as with SoundCloud or the other services. This should be easy to fix. I will look into this soon but a patch would welcome as well.

Thanks!

**Comment by Psycoguana** [comment]
Great, thanks a lot!
