### ISSUE TITLE
[Feature Request] Add iHeartRadio

### ISSUE THREAD

**Issue by NonaSuomy** [tizonia/tizonia-openmax-il#597]
Add iHeartRadio https://github.com/oldlaptop/iheart-mplayer & http://somafm.com/ https://somafm.com/channels.json

**Comment by tizonia** [comment]
@NonaSuomy 

Thanks a lot for taking the time to request new features. This is always welcome. I am a big fan of Internet radio myself, so iheart and soma would be great additions to Tizonia. I will look into these when I have some time. It would be great also if someone wanted to help with the development.

**Comment by NonaSuomy** [comment]
I was able to hack iHeartRadio into this Arduino/ESP project a long time ago if it helps anyone. I put a lot of detail on how to pull the website apart here [Esp-radio issues/70](https://github.com/Edzelf/Esp-radio/issues/70) and here [Esp-radio issues/82](https://github.com/Edzelf/Esp-radio/issues/82) Not sure if iHeartRadio may use JSON now instead of XML.

**Comment by tizonia** [comment]
@NonaSuomy 

Sorry for overlooking this for such a long time. I'm would love to add iheart to Tizonia. Do you think you could work on this?

**Comment by juanrubio** [comment]
Hi @NonaSuomy 

Good news, iHeartRadio streaming is now implemented in the 'develop' branch. It will be released sometime soon as part of v0.22.0.

I've created #732 for somafm.com

**Comment by juanrubio** [comment]
Closing this now. The release of 0.22.0 is in progress and binaries will be out in the next hours.

**Comment by NonaSuomy** [comment]
Question, I noticed that iHearts website gives country options yet this seems to be locked to the USA is there an option to send the API a country locale?
