### ISSUE TITLE
Support for spotify Songs playlist (https://open.spotify.com/collection/tracks)

### ISSUE THREAD

**Issue by oppsig** [tizonia/tizonia-openmax-il#600]
# Issue Template

### Description

Is it possible to add support for playing spotify "Songs" playlist. 
The playlist which contains songs you have hearth'ed.
The url is: https://open.spotify.com/collection/tracks
I can't get spotify uri on this list like other spotify playlists.

### Steps to Reproduce

1. tizonia --spotify-playlist-id https://open.spotify.com/collection/tracks

**Expected behavior:** Playing spotify Songs playlist

**Actual behaviour:** 
```
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : '****'.
[Spotify] [Playlist id] 'https://open.spotify.com/collection/tracks' (owner: ****).
warning:expected id of type %s but found type %s %s
[Spotify] (SpotifyException) : http status: 404, code:-1 - https://api.spotify.com/v1/users/****/playlists/tracks:
 Invalid playlist Id

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```

**Reproduces how often:** always

### Versions
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v0.7.82]

➜  ~ cat /etc/os-release        
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

### Installation Method Used

Snap

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi @oppsig !

Thanks for reporting this missing feature. Really interesting. 

It seems to be one of those dynamically created playlists, like the daily mixes. They don't seem to have an externally visible playlist id. I will try to dig into this, but I'm afraid I am not very optimistic about it.

**Comment by oppsig** [comment]
Ok, thanks :+1:

**Comment by Kwaadpepper** [comment]
I can't play either spotify's dynamic lists like : 
``` tizonia --spotify-owner="spotify" --spotify-playlist RapCaviar``` **=>** ```[Spotify] (TypeError) : 'NoneType' object is not subscriptable```
or
```tizonia --spotify-owner="spotify" --spotify-playlist-id https://open.spotify.com/playlist/37i9dQZF1DX8GjsySWIS1x``` **=>** ```[Spotify] (ValueError) : PlaylistBut not found : https://open.spotify.com/playlist/37i9dQZF1DX8GjsySWIS1x```
https://open.spotify.com/playlist/37i9dQZF1DX8GjsySWIS1x exists.

**Comment by tizonia** [comment]
Hi @Kwaadpepper / @oppsig 

Good news, the access to private and dynamic playlists is in the works. It will be out in Tizonia 0.22.0.

**Comment by juanrubio** [comment]
Closing this now. The release of 0.22.0 is in progress and binaries will be out in the next hours.
