### ISSUE TITLE
Asks for password every time using spotify

### ISSUE THREAD

**Issue by itaybm2** [tizonia/tizonia-openmax-il#603]
# Asks for password every time using spotify

### Description

when using Spotify through Tizonia, although my password is written in the cfg file as requested, it still demands the password each time i play a song.

### Steps to Reproduce

1. tizonia --spotify-tracks "songname"

**Expected behavior:** [What you expect to happen]
Begins playing without any more input demand. 

**Actual behaviour:** [What actually happens]
asks for "*ACCOUNT_NAME*'s password:"

**Reproduces how often:** [What percentage of the time does it reproduce?]
every time 

### Versions
0.18.0

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used
Bintray debs

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi @itaybm2 !

Sorry for the delayed reply and thanks very much for taking the time to report an issue.

It is strange, it does not happen to me, but I suspect you have an issue somewhere in your config file. Is there a chance that you can copy here the section that contains the password (with a masked password please).

Thanks!

**Comment by itaybm2** [comment]
Sure!

# -*-Mode: conf; -*-
# tizonia-config v0.18.0 configuration file

[ilcore]
# Tizonia OpenMAX IL Core section

# Component plugins discovery
# -------------------------------------------------------------------------
# A comma-separated list of paths to be scanned by the Tizonia IL Core when
# searching for component plugins
component-paths = /usr/lib/x86_64-linux-gnu/tizonia0-plugins12;

# IL Core extension plugins discovery
# -------------------------------------------------------------------------
# A comma-separated list of paths to be scanned by the Tizonia IL Core when
# searching for IL Core extensions (not implemented yet)
extension-paths =


[resource-management]
# Tizonia OpenMAX IL Resource Management (RM) section

# Resource Manager (RM) daemon interface enable/disable switch
# -------------------------------------------------------------------------
# Whether the IL RM functionality is enabled or not
enabled = false

# RM database
# -------------------------------------------------------------------------
# This is the path to the Resource Manager database
rmdb = /usr/share/tizrmd/tizrm.db


[plugins]
# OpenMAX IL Component plugins section

# Each key-value pair represents a list of any data that a
# specific component might need. The entries here must honor the following
# format: OMX.component.name.key = <semi-colon-separated list of items>

# ALSA Audio Renderer
# -------------------------------------------------------------------------
#
# OMX.Aratelia.audio_renderer.alsa.pcm.preannouncements_disabled.port0 = false
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = default
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Master


[tizonia]
# Tizonia player section

# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.pulseaudio.pcm

# MPRIS v2 interface enable/disable switch
# -------------------------------------------------------------------------
# Valid values are: true | false
#
mpris-enabled = false

# Spotify configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment
# and configure accordingly
#
spotify.user     = ####
spotify.password = ####
# spotify.recover_lost_token = false (set to true to continue playback after
#                                     the token has been [spuriously?] lost)
# spotify.allow_explicit_tracks = false (set to true to allow explicit tracks)

# Google Play Music configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure here.
#
# gmusic.user       = user@gmail.com
# gmusic.password   = pass (account password or app-specific password for
#                          2-factor users)
# gmusic.device_id  = deviceid (16 hex digits, e.g. '1234567890abcdef')
# gmusic.buffer_seconds = size of the audio buffer (in seconds) to use while
#                         downloading streams. Default: 720. Increase in
#                         case of cuts.

# SoundCloud configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your SoundCloud OAuth token here.
#
# To obtain your OAuth token, Tizonia needs to be granted access to your
# SoundCloud account. Visit http://tizonia.org/docs/soundcloud/ for the
# details.
#
# soundcloud.oauth_token = X-XXXXXX-XXXXXXXX-XXXXXXXXXXXXXX
# soundcloud.buffer_seconds = size of the audio buffer (in seconds) to use
#                             while downloading streams. Default: 600.
#                             Increase in case of cuts.


# Dirble configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your Dirble Api Key here.
#
# To obtain your Dirble API key, go to https://dirble.com/developer/
#
# dirble.api_key = xxxxxxxxxxxxxx
# dirble.buffer_seconds = size of the audio buffer (in seconds) to use
#                         while downloading streams. Default: 120.
#                         Increase in case of cuts.


# YouTube configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure as needed.
#
# youtube.buffer_seconds = size of the audio buffer (in seconds) to use
#                          while downloading streams. Default: 60.
#                          Increase in case of cuts.


# Plex configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your Plex server and account auth token here.
#
# To find how to obtain a Plex user authentication token, see:
# https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
#
# plex.base_url = xxxxxxxxxxxxxx (e.g. http://plexserver:32400)
# plex.auth_token = xxxxxxxxxxxxxx (e.g. SrPEojhap3H5Qj2DmjhX)
# plex.buffer_seconds = size of the audio buffer (in seconds) to use
#                       while downloading streams. Default: 60.
#                       Increase in case of cuts.


I placed hashes where my username and password were written.

**Comment by tizonia** [comment]
@itaybm2  
Hi!, thanks for uploading that.

Have you noticed that the file you uploaded has two copies of the config in it?

**Comment by itaybm2** [comment]
Hi, that's a separate mistake.
The original file has only a single copy of the config :)

**Comment by beamzer** [comment]
I have the same issue on my ubuntu desktop and tizonia 0.18.0. The strange thing is that it reads the accountname and displays that in de password dialogue (verified that it reads the file with strace). Putting double quotes around username and password doesn't make a differene. Could it be due to special characters in the password?

**Comment by beamzer** [comment]
I just tested my theory and it's indeed a special character in the config from spotify.password. In my case it was '#'. Changed the password and now it works. Best of course to debug the relevant code ;)

**Comment by itaybm2** [comment]
Thanks! solved it for me.
