### ISSUE TITLE
--plex-audio-playlist <arg> returns "A playlist type must be specified."

### ISSUE THREAD

**Issue by artex-files** [tizonia/tizonia-openmax-il#605]
# Issue Template

### Description

searching by artist or by track or album works just fine.  However, when I run `--plex-audio-playlist <arg> `
returns` A playlist type must be specified.`

### Steps to Reproduce

for example: 
1. `tizonia --plex-audio-playlist citypop`
returns 
` A playlist type must be specified.`

**Expected behavior:** Play my plex playlist named "citypop"

**Actual behaviour:** ` A playlist type must be specified.`
**Reproduces how often:** everytime

### Versions
tizonia 0.18.0
Arch Linux 

Boost 1_69
TagLib 1.11.1
MediaInfoLib = v19.04
Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).B

### Installation Method Used
AUR trizonia-all

**Comment by tizonia** [comment]
Hi @artex-files !

Thanks for taking the time to report an issue. Yes, I think you are right. This is a genuine bug. it sounds like a regression introduced at some point. It should not be difficult to fix.

**Comment by tizonia** [comment]
The fix is now in 'develop'. It will be out in the next release of Tizonia (no date yet!).

```
-          + vm_.count ("plex-audio-album") + vm_.count ("pl ex-audio-playlist");
+          + vm_.count ("plex-audio-album") + vm_.count ("plex-audio-playlist");
```
