### ISSUE TITLE
Fast Forward and rewind

### ISSUE THREAD

**Issue by metalerk** [tizonia/tizonia-openmax-il#608]
# Fast Forward and rewind

### Description

Not sure but I can't find a way to fast forward or rewind to listen a specific part of the song.
Is this feature currently available?

### Versions

Tizonia 0.18.0
Debian 9

**Comment by tizonia** [comment]
Hi!, and thanks for taking the time to open an issue. This is always appreciated!

Yes, unfortunately, we don't have seek functionality implemented in Tizonia. This is tracked by #438. 
Please, read through that issue and comment there if you need to.

I am closing this one as a duplicate of #438
