### ISSUE TITLE
Spotify: allow configuration of preferred bitrate settings

### ISSUE THREAD

**Issue by marsch2** [tizonia/tizonia-openmax-il#613]
Hello,
first of all,  I really love this project!
I just wondered if there is a way to change the bitrate settings from the default 320kbit/s to maybe a lower setting?

Thanks in advance!

**Comment by tizonia** [comment]
Hi!, thanks for getting in touch and apologies for the delayed reply!

Yes, this is something that has been asked several times. This configuration option is not exposed at the moment, but it is fairly straightforward to add it as an option in tizonia.conf. 

I will post instructions here on how to do this in case anybody wants to pitch in!

**Comment by tizonia** [comment]
Finally, this is implemented in the following commits (develop branch): 
- efb837fdb0304dc8de6a2cd0ba0218a7e5b347cb
- 421bb83eef78c7746581a7517906997947ea1e69
- cd6a5a02cec34380f4a622dbea9cca969899114f

It will be merged to master soon and released in version 0.19.0

**Comment by tizonia** [comment]
To configure Spotify's bitrate settings, there are two options:

- From command-line
```
  --spotify-preferred-bitrate arg       Preferred Spotify bitrate (kbps) (320, 
                                        160 or 96; default: 320).
```

- or in config file
```
# Spotify configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment
# and configure accordingly
#
# spotify.user     = user
# spotify.password = pass
# spotify.recover_lost_token = false (set to true to continue playback after
#                                     the token has been [spuriously?] lost)
# spotify.allow_explicit_tracks = false (set to true to allow explicit tracks)
# spotify.preferred_bitrate = Three possible values: 96, 160, or 320 ; default: 320

```

**Comment by tizonia** [comment]
Closing this issue for now. The code is now in the master branch. To be released real soon.
