### ISSUE TITLE
PulseAudio volume customized

### ISSUE THREAD

**Issue by matthewarmand** [tizonia/tizonia-openmax-il#620]
### Description

When using `tizonia` on a system with PulseAudio, the output volume of the application in Pulse seems fixed at 75% every time the program starts, regardless of the setting changing at previous runs.  Would it be possible to have this setting be remembered once its changed on a previous run, or maybe be configurable? (Or just default to 100% instead of 75%, which would be my setting) 

### Steps to Reproduce

1. Run tizonia on a system with PulseAudio
2. Observe the application volume setting (either in the system tray or with `pavucontrol` or similar)
3. Quit tizonia
4. Run tizonia again and observe the application volume setting again 

**Expected behavior:** The setting is persisted from one run to the next (alternatively, the default application volume is 100%)

**Actual behaviour:** The setting is 75% for each new run

**Reproduces how often:** 100% of the time

### Versions

```
# tizonia --version
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

# pulseaudio --version
pulseaudio 12.2

# snap --version
snap    2.40-1
snapd   2.40-1
series  16
arch    -
kernel  5.2.9-arch1-1-ARCH

# cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### Installation Method Used

I'm currently using the snap package, although I believe I saw the same behavior with the AUR package (and it seems like a core functionality issue, so I'd imagine probably affects all installation methods)

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues and provide feedback. This is always welcome.

I think your analysis is correct for the most part. Adding a config file option to set a default volume would be easy (and useful). I think this could be implemented quite quickly.

If anyone wants to help, I could provide some easy-to-folow instructions. Otherwise, I'll implement it when I have some time

**Comment by matthewarmand** [comment]
@tizonia feel free to document whatever instructions you feel are necessary here and I'll take a crack at it

**Comment by tizonia** [comment]
@matthewarmand 

I have to apologize. I was meaning to look at the implementation of this and then provide the details here for you to pick up, but I thought it was more work to detail it than to do it.

Please have a look at this commit:
a10d8e2a7948f1c9f54310e29a3ae531e8ea307a

Basically, this adds support for this configuration option:
```
# PulseAudio Audio Renderer
# -------------------------------------------------------------------------
#
# OMX.Aratelia.audio_renderer.pulseaudio.pcm.default_volume = Value from 0
#                                                             to 100 (Default: 75)
```
The specified volume there will be honoured when the application is started. 

It is in the develop, branch. I'm planning to cut a new release in the next few days.

**Comment by matthewarmand** [comment]
No worries at all @tizonia , just glad it hit the roadmap. Thanks for the reference to the commit for context.

>The specified volume there will be honoured when the application is started.

One thing I've noticed is when skipping through a playlist/album using `p` or `n`, the volume resets to 75% even if its previously been adjusted. Will this fix apply to that case as well? Basically, is `set_initial_component_volume` called through that codepath as well or is that effect due to something else?

Thanks again for the enhancement, very much looking forward to it

**Comment by tizonia** [comment]
Wow!, You're absolutely right. The volume was getting reset to its intial value. This commit fixes that:
51a0984b6f93775ed587b31f6699e5b6665f31db

Thank you for your prompt reply!

**Comment by matthewarmand** [comment]
Excellent, thanks so much! No worries at all. I use `tizonia` every day to listen to music at work and am looking forward to this feature getting into a release.

I'll probably leave the Issue open until a release, or you can feel free to close whenever.

Thanks again!

**Comment by tizonia** [comment]
Closing this issue for now. The code is now in the master branch, to be released soon.

**Comment by matthewarmand** [comment]
@tizonia this fix is working great for gmusic, but I notice that with `--youtube` options this config option isn't respected. The behavior there is the same as before, but with 80% as the default setting rather than 75%

**Comment by tizonia** [comment]
Hi @matthewarmand 

Thanks for letting me know about the issue in the youtube graph. I'm re-opening to check that.

**Comment by tizonia** [comment]
@matthewarmand 

I believe I have fixed the youtube volume issue. It should work now. 

This is in the develop branch. Will be merged to master in just a few days.

**Comment by matthewarmand** [comment]
Thanks @tizonia , checked on the new version and it looks good. Thanks again for all your work on this!
