### ISSUE TITLE
Raspbian Buster not supported

### ISSUE THREAD

**Issue by siduxdevil** [tizonia/tizonia-openmax-il#621]
# Issue Template

### Description
Tizonia not installable on Raspbian Buster
[Description of the issue]
Tizonia not installable on Raspbian Buster through curl -kL https://goo.gl/Vu8qGR | bash
### Steps to Reproduce
1. set up RasPi 4 with Raspbian Buster
2. issue the command curl -kL https://goo.gl/Vu8qGR | bash
**Expected behavior:** [What you expect to happenT
Tizonia installs
**Actual behaviour:** [What actually happens]
The install does not take place, instead I get the following output:
curl -kL https://goo.gl/Vu8qGR | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   150  100   150    0     0    219      0 --:--:-- --:--:-- --:--:--   219
100  5130  100  5130    0     0   6396      0 --:--:-- --:--:-- --:--:--  6396
ID=raspbian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
Can't find a supported Raspbian distribution.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used
curl -kL https://goo.gl/Vu8qGR | bash
Bintray debs, Snap package, built from source, other?

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi!, Thanks for taking the time to report this issue. 

It's correct. Only Raspbian Stretch is supported at the moment. The next release of Tizonia will support Raspbian Buster. Note that a new release will not be out for another month or so.

**Comment by siduxdevil** [comment]
Thanks, writing an article about Tizonia on a RasPi 4. I will advise my readers to look out for a new release, as it will take .~ 1 month for the magazine to be published.
