### ISSUE TITLE
Dirble not accessible

### ISSUE THREAD

**Issue by siduxdevil** [tizonia/tizonia-openmax-il#624]
# Issue Template

### Description
It seems that the 'Dirble Internet Radios' service is discontinued, the server is constantly down. Will there be a replacement for this important service?
[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

Bintray debs, Snap package, built from source, other?

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi!, thanks for creating an issue for this.

You're correct. The Dirble Internet radio directory has been down for a while now. It is not clear whether it will ever come back (https://twitter.com/dirbledirectory?lang=en)

Most likely the Dirble functionality will be disabled in the next release of Tizonia.

Regarding future plans, yes I'm currently looking at replacing it with another Internet radio directory source, like the 'tunein' directory at http://opml.radiotime.com/

It may well be ready for the next release of Tizonia, but I can't guarantee it. Certainly, I would like to replace it a soon as possible as I'm a big fan of Internet radios and they are one of my main use cases for using Tizonia.

There is already an application that consumes this directory if you want to have a look (I have not tried it myself):
https://github.com/chronitis/curseradio

**Comment by tizonia** [comment]
Dirble removal is currently in-progress in the python3 branch
https://github.com/tizonia/tizonia-openmax-il/tree/python3

**Comment by tizonia** [comment]
The code changes have been merged to master. Closing this for now.
