### ISSUE TITLE
Spotify: play one song, one time only

### ISSUE THREAD

**Issue by tsaustin** [tizonia/tizonia-openmax-il#625]
# Issue Template

### Description

tizonia --spotify-track-id xxx plays the same song over and over again. How can I just play this one song?

### Steps to Reproduce

launch "tizonia --spotify-track-id xxx " from CLI

**Expected behavior:** [What you expect to happen]

play one track and then exit

**Actual behaviour:** [What actually happens]

repeats the same track over and over again.

**Reproduces how often:** [What percentage of the time does it reproduce?]
all the time

### Versions

tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
            * [Boost 1_58]
            * [TagLib 1.9.1]
            * [MediaInfoLib - v0.7.82]

### Installation Method Used

snap

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to raise an issue. Always appreciated.

This is actually intentional, although there is already an issue to implement the 'non-looped' playback option:
https://github.com/tizonia/tizonia-openmax-il/issues/491#issuecomment-397459429

**Comment by tizonia** [comment]
Please feel free to add any comments on #491. I'm closing this issue as a duplicate.
