### ISSUE TITLE
[YouTube] (ValueError) tizonia installed from script

### ISSUE THREAD

**Issue by strategos81** [tizonia/tizonia-openmax-il#628]
# Issue Template

### Description

When trying to play music using youtube, --youtube-audio-mix 'search string'. Service is returning an error.
[YouTube] (ValueError) : Need 11 character video id or the URL of the video. Got //lata 90

### Steps to Reproduce

1. start tizonia --youtube-audio-mix 'search string'

**Expected behavior:** [What you expect to happen]
music should start playing 
**Actual behaviour:** [What actually happens]
error is returned
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions
0.18.0
Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tina
UBUNTU_CODENAME=bionic

### Installation Method Used
installed from the script
Bintray debs, Snap package, built from source, other?

### Additional Information
I had issues with missing python components, basically, the script couldn't successfully finish the installation. 'fuzzywuzzy', 'spotifyapi', 'youtube-dl' after I resolved those problems tizonia started to work. But not youtube music playing. Spotify is working as intended.
Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues.

Actually, there are two separate commands:

```
$ tizonia --youtube-audio-mix gEPmA3USJdI

(Note the 11 characters from this URL :
https://www.youtube.com/watch?v=gEPmA3USJdI&list=RDv2AC41dglnM&index=3)
```

or

```
tizonia --youtube-audio-mix-search 'thunderstruck'                                  
```
`tizonia --help youtube` has the details.

With regards to the issues you found while using the installation script, I believe this is because you are running 19.2, and this is not supported by the script. I'll get that fixed shortly.

**Comment by tizonia** [comment]
Added support for 19.2 Tina in install.sh (see #629)

**Comment by strategos81** [comment]
Thanks for such a quick response.
