### ISSUE TITLE
Support Debian Bullseye

### ISSUE THREAD

**Issue by Alphare** [tizonia/tizonia-openmax-il#632]
Hi. I'd like to try your software but your install script does not support Debian Bullseye yet.

Are there any issues that I need to be aware of before trying it out myself? Also, upstream support would be nice. 

Thanks

**Comment by tizonia** [comment]
Hi!,

Thanks for taking the time to raise an issue.

There is no issue, as far as I know. Tizonia's binaries for new OS versions of Debian/Raspbian/Ubuntu are usually added when a new release of Tizonia is produced (I'm currently a bit behind schedule with the next release).

So I hope to be adding Bullseye binaries in 0.19.0.

In the meantime, you can try the Buster binaries in Bullseye, I think that will work without issues.

Basically, all you need to do is to download the installation script, and modify the following section:
https://github.com/tizonia/tizonia-openmax-il/blob/c857e9565f0b6b9a7f340ead27551c4cf2492b50/tools/install.sh#L49

```
elif echo "$RELIDS" | grep -E 'buster|kali-rolling'; then
  # NOTE: Kali Linux is based on Debian Testing, which is currently codenamed 'Buster'
  DISTRO="debian" ; RELEASE="buster"
```
and just add 'bullseye' to the grep statement.

Please note that this would be an 'unsupported' way of installing Tizonia in Bullseye.

**Comment by tizonia** [comment]
Closing this now. I'm currently cutting a new release. If all goes well, there will be Debian Bullseye (amd64) binaries very soon.
