### ISSUE TITLE
"A playlist must be specified" when trying to add user details

### ISSUE THREAD

**Issue by Thomas12323** [tizonia/tizonia-openmax-il#635]
Hi guys! When trying to add my username through the provided command I get 

A playlist must be specified.

Cannot find the .config file either...
Appreciate any help!

**Comment by Thomas12323** [comment]
I did find the config file but did try it with my username and email and still have to "provide a username" according to the tool.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to raise an issue.

Credentials for you the various services need to be added to Tizonia's config file using an editor.

Once you do that, you should be able to connect to the service. There are some known issues with passwords that contain unusual characters (see #574), and in those cases, you may find a situation like the one you describe.

If you need more help, I would need more details like the exact command-line that you are typing when you get the error.

**Comment by Thomas12323** [comment]
> Hi!, thanks for taking the time to raise an issue.
> 
> Credentials for the various services need to be added to Tizonia's config file using an editor.
> 
> Once you do that, you should be able to connect to the service. There are some known issues with passwords that contain unusual characters (see #574), and in those cases, you may find a situation like the one you describe.
> 
> If you need more help, I would need more details like the exact command-line that you are typing when you get the error.

Hi! Thanks for getting back to me :) Did configure it and deleted the hashtags to get it running, but when I try to play a song, the following happens:
tizonia --spotify-tracks parents 
Segmentation fault (core dumped)

**Comment by juanrubio** [comment]
Hi, 

> sudo tizonia --spotify-tracks parents
sudo should not need to be used. I think this is an indication that Tizonia is installed incorrectly. Perhaps you used sudo while installing Tizonia? is this a snap install or a debian-based installation via the install.sh script?

**Comment by Thomas12323** [comment]
Installed it through yay on latest manjaro kde

**Comment by Thomas12323** [comment]
Any guidance on how to remove the failed install and install correctly on manjaro?

**Comment by juanrubio** [comment]
I'm not familiar with yay, so I would not be able to recommend anything useful. You might want to check yay's documentation to try to undo the steps originally performed.

Precisely because there may be different trade-offs with the various ways and tools available for installing AUR packages, the recommended way of installing tizonia on Arch is this:
https://github.com/tizonia/tizonia-openmax-il#arch-user-repository-aur

**Comment by Thomas12323** [comment]
Alright, installation worked flawlessly. But if I want to play a track the following occurs: 
tizonia --spotify-tracks parents
fish: 'tizonia --spotify-tracks parents' terminated by signal SIGSEGV (Address boundary error)

**Comment by tizonia** [comment]
@Thomas12323 

Sorry, I had nothing useful to say to your last comment. It still sounded to me like something specific to your environment. 

Any luck with this?

**Comment by tizonia** [comment]
I'm closing this issue for now. Please reopen if you find evidence of an issue in Tizonia.
