### ISSUE TITLE
Stops outputting sound and only responds to <Ctrl-c> with increasing number of songs

### ISSUE THREAD

**Issue by mcurly** [tizonia/tizonia-openmax-il#637]
# Issue Template
### Description

Tizonia stops responding when playing several songs from googlemusic. (Audio stops, although progress bar continues, and stops responding to keyboard input. Only the exit key-combo Ctrl-c works... to stop the process.

### Steps to Reproduce

1. issue (for instance) `tizonia --gmusic-track 'Este Mar by Linda Martini' `
2. wait for the command to pull the relevant tracks from my library (it does eventually list that track I searched for (although it gives out some irrelevant/unrelated tracks)
3. skip that listing up to the desired track (if not playing already the desired one)
4. tizonia stops producing any sound at second #16 (more or less)
5. doesn't respond to any keyboard presses.
6. needs to be broken/interrupted with <Ctrl-c>

**Expected behavior:** 

Normally it should play without issues.

**Actual behaviour:**

The actual undesired behavior depicted above.

**Reproduces how often:** 

Every time I tried with that track (and some others by the same Artist/Band) on gmusic tizonia plugin.

### Versions

 `tizonia --version 
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project `<http://tizonia.org>` 

`tizonia --debug `

` tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org> `

` Debug Info:
            * [Boost 1_71]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v19.09] `

`cat /etc/os-release  "output" `
`PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux `

### Installation Method Used

binaries built from repository source on one server with ArchLinux OS with x86_64 architecture.

issues observed both on the server and on a laptop with the sme ArchLinux OS architecture and version  

packages were built with available PKGBUILD files and makepkg utillity.

they were then installed on both the server and the laptop with every dependency fulfilled and handled either with the trizen pacman wrapper or with the aur sources previously built.

the packages were then tested and the described anomalies happen.

### Additional Information

Own a legitimate Google Play Music account, and behavior not happening with tizonia youtube plugin.

On other devices/platforms (Android or GooglePlayMusicDesktop player) this doesn't happen

P.s.: Thank you to you Juan Rubio for developing an (otherwise) brilliant app.

**Comment by tizonia** [comment]
Hi !, thanks so much for taking the time to raise an issue.

(and thanks for the positive feedback! )

There are couple of things that would provide more information on what is going on.

The first one is this:

```
export TIZONIA_GMUSICPROXY_DEBUG=1
```

The second is the advice in this other issue (see the .log4crc config):
https://github.com/tizonia/tizonia-openmax-il/issues/633#issuecomment-553822160

If you had a chance to try these things out and provide the output here, that would be great.

**Comment by mcurly** [comment]
Hi again @tizonia. I've just seen your message and had trouble recently in the setup machine. These latest problems are not related with your superb app but with a wireless network interface card I recently installed and that I haven't yet figured out.

If I may ask for some more time to report back about the issue and the follow up info that you've requested that would be great.

I'll catch up then ok?

Thanks again and see you later.

**Comment by tizonia** [comment]
@mcurly 

Thanks for getting back to me. I am closing the issue for now, but please reopen if you find evidence of an issue in Tizonia.

**Comment by mcurly** [comment]
Hi again @tizonia !

Sorry for this late comeback. My bits and bobs on the outside of the digital world have been a little hectic.

Well, I've followed your leads on how to capture more info, and I am putting it here.

This was the result of issuing this command:

'~ % tizonia --gmusic-album 'Linda Martini by Linda Martini'  2>&1 | tee (name of log file)'


[Here](http://ix.io/24ua) is the log.

I've removed personal information such as my email address.

Hope that it may be enlightening, somehow

If there's anymore that I can do, feel free to ask. I will try to answer more promptly.

Thank you

**Comment by mcurly** [comment]
Oh and one update, tizonia does respond to "Q" key. Not only to "<Ctrl-c>"

**Comment by tizonia** [comment]
Hi @mcurly 

The tizonia-all AUR package has been updated for 0.19.0 and now Tizonia supports Python 3.

Could you please uninstall 0.18.0 and install 0.19.0 and see if the problem persists?

Thanks

**Comment by mcurly** [comment]
Hi @tizonia ,

Thank you for your continuous interest in this issue and your interesting (actually a lot) software.

Well, actually I've just installed the version you were referring to, and the issue persists.

What is curious is that the tracks causing this issue are present on several recordings from the band.

For instance "Este Mar" has several appearances (both in the band's album from 2018 and in an EP from 2005). Could this be the origin of this sort of issue? And if so wouldn't there be a way to filter more accurately which tracks would one wish to listen to?

All the best!

**Comment by mcurly** [comment]
Update:

@tizonia , I've enrolled (back) with spotify and the same track ("Este Mar") seems to play well. So this issue points to Google own "stuff".

Don't really know what else I could do to help you debug this. (Suggestions accepted though ;) )

I am going to cancel GMusic subscription and hope for the best.
