### ISSUE TITLE
Unable to locate package tizonia-all

### ISSUE THREAD

**Issue by Patatone** [tizonia/tizonia-openmax-il#640]
### Description

root@debian:# ./install.sh --safe
WARNING: Running as root with --safe option; installation continues...
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
VERSION="10 (buster)"
VERSION_CODENAME=buster
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
curl is already the newest version (7.64.0-4).
libffi-dev is already the newest version (3.2.1-9).
libffi-dev set to manually installed.
python-dev is already the newest version (2.7.16-1).
python-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  hicolor-icon-theme imagemagick-6-common imagemagick-6.q16 libdjvulibre-text
  libdjvulibre21 libilmbase23 libjxr-tools libjxr0 liblqr-1-0
  libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6
  libnetpbm10 libopenexr23 libwmf0.2-7 netpbm
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  git-man icu-devtools libcurl3-gnutls liberror-perl libicu-dev libxslt1.1
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-cvs git-mediawiki git-svn icu-doc libssl-doc
The following NEW packages will be installed:
  apt-transport-https git git-man icu-devtools libcurl3-gnutls liberror-perl
  libicu-dev libssl-dev libxml2-dev libxslt1-dev libxslt1.1
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 21.1 MB of archives.
After this operation, 99.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main i386 apt-transport-https all 1.8.2 [149 kB]
Get:2 http://deb.debian.org/debian buster/main i386 libcurl3-gnutls i386 7.64.0-4 [355 kB]
Get:3 http://deb.debian.org/debian buster/main i386 liberror-perl all 0.17027-2 [30.9 kB]
Get:4 http://deb.debian.org/debian buster/main i386 git-man all 1:2.20.1-2 [1,619 kB]
Get:5 http://deb.debian.org/debian buster/main i386 git i386 1:2.20.1-2 [5,878 kB]
Get:6 http://deb.debian.org/debian buster/main i386 icu-devtools i386 63.1-6 [196 kB]
Get:7 http://deb.debian.org/debian buster/main i386 libicu-dev i386 63.1-6 [9,374 kB]
Get:8 http://deb.debian.org/debian buster/main i386 libssl-dev i386 1.1.1d-0+deb10u2 [1,826 kB]
Get:9 http://deb.debian.org/debian buster/main i386 libxml2-dev i386 2.9.4+dfsg1-7+b3 [843 kB]
Get:10 http://deb.debian.org/debian buster/main i386 libxslt1.1 i386 1.1.32-2.2~deb10u1 [248 kB]
Get:11 http://deb.debian.org/debian buster/main i386 libxslt1-dev i386 1.1.32-2.2~deb10u1 [537 kB]
Fetched 21.1 MB in 3s (6,562 kB/s)      
Selecting previously unselected package apt-transport-https.
(Reading database ... 64306 files and directories currently installed.)
Preparing to unpack .../00-apt-transport-https_1.8.2_all.deb ...
Unpacking apt-transport-https (1.8.2) ...
Selecting previously unselected package libcurl3-gnutls:i386.
Preparing to unpack .../01-libcurl3-gnutls_7.64.0-4_i386.deb ...
Unpacking libcurl3-gnutls:i386 (7.64.0-4) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../02-liberror-perl_0.17027-2_all.deb ...
Unpacking liberror-perl (0.17027-2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../03-git-man_1%3a2.20.1-2_all.deb ...
Unpacking git-man (1:2.20.1-2) ...
Selecting previously unselected package git.
Preparing to unpack .../04-git_1%3a2.20.1-2_i386.deb ...
Unpacking git (1:2.20.1-2) ...
Selecting previously unselected package icu-devtools.
Preparing to unpack .../05-icu-devtools_63.1-6_i386.deb ...
Unpacking icu-devtools (63.1-6) ...
Selecting previously unselected package libicu-dev:i386.
Preparing to unpack .../06-libicu-dev_63.1-6_i386.deb ...
Unpacking libicu-dev:i386 (63.1-6) ...
Selecting previously unselected package libssl-dev:i386.
Preparing to unpack .../07-libssl-dev_1.1.1d-0+deb10u2_i386.deb ...
Unpacking libssl-dev:i386 (1.1.1d-0+deb10u2) ...
Selecting previously unselected package libxml2-dev:i386.
Preparing to unpack .../08-libxml2-dev_2.9.4+dfsg1-7+b3_i386.deb ...
Unpacking libxml2-dev:i386 (2.9.4+dfsg1-7+b3) ...
Selecting previously unselected package libxslt1.1:i386.
Preparing to unpack .../09-libxslt1.1_1.1.32-2.2~deb10u1_i386.deb ...
Unpacking libxslt1.1:i386 (1.1.32-2.2~deb10u1) ...
Selecting previously unselected package libxslt1-dev:i386.
Preparing to unpack .../10-libxslt1-dev_1.1.32-2.2~deb10u1_i386.deb ...
Unpacking libxslt1-dev:i386 (1.1.32-2.2~deb10u1) ...
Setting up apt-transport-https (1.8.2) ...
Setting up libcurl3-gnutls:i386 (7.64.0-4) ...
Setting up liberror-perl (0.17027-2) ...
Setting up libssl-dev:i386 (1.1.1d-0+deb10u2) ...
Setting up icu-devtools (63.1-6) ...
Setting up libxslt1.1:i386 (1.1.32-2.2~deb10u1) ...
Setting up git-man (1:2.20.1-2) ...
Setting up libicu-dev:i386 (63.1-6) ...
Setting up libxml2-dev:i386 (2.9.4+dfsg1-7+b3) ...
Setting up git (1:2.20.1-2) ...
Setting up libxslt1-dev:i386 (1.1.32-2.2~deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3137  100  3137    0     0   5134      0 --:--:-- --:--:-- --:--:--  5134
OK
deb http://apt.mopidy.com/ stable main contrib non-free
Setting up Tizonia's Bintray archive for debian:buster
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1706    0  1706    0     0   2512      0 --:--:-- --:--:-- --:--:--  2512
OK
deb https://dl.bintray.com/tizonia/debian buster main
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                            
Hit:3 http://deb.debian.org/debian buster-updates InRelease                    
Ign:5 https://dl.bintray.com/tizonia/debian buster InRelease                   
Get:6 https://dl.bintray.com/tizonia/debian buster Release [1,840 B]
Get:7 https://dl.bintray.com/tizonia/debian buster Release.gpg [183 B]       
Ign:4 http://apt.mopidy.com stable InRelease                                   
Get:8 http://apt.mopidy.com stable Release [37.0 kB]
Get:9 http://apt.mopidy.com stable Release.gpg [833 B]
Get:10 http://apt.mopidy.com stable/main i386 Packages [23.2 kB]
Get:11 http://apt.mopidy.com stable/contrib i386 Packages [5,386 B]            
Get:12 http://apt.mopidy.com stable/non-free i386 Packages [1,006 B]           
Fetched 69.5 kB in 7s (9,824 B/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (18.1-5).
The following packages were automatically installed and are no longer required:
  hicolor-icon-theme imagemagick-6-common imagemagick-6.q16 libdjvulibre-text
  libdjvulibre21 libilmbase23 libjxr-tools libjxr0 liblqr-1-0
  libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6
  libnetpbm10 libopenexr23 libwmf0.2-7 netpbm
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Collecting gmusicapi
  Downloading https://files.pythonhosted.org/packages/9b/8d/acd05b2518ec87fc4634d55dcd70496cb030eca4d966b0a90747cf45600e/gmusicapi-12.1.1.tar.gz (174kB)
    100% |████████████████████████████████| 174kB 736kB/s 
Collecting soundcloud
  Downloading https://files.pythonhosted.org/packages/68/f2/b6ddd262786f3a31db342ad223feebb9774e4809672106b9cfc9b4798d87/soundcloud-0.5.0-py2-none-any.whl
Collecting youtube-dl
  Downloading https://files.pythonhosted.org/packages/58/38/1215e2bae8cd0b1a52621740add46cebfa8bb988a48cd61cf7cccf7c09c6/youtube_dl-2019.11.28-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 98kB/s 
Collecting pafy
  Downloading https://files.pythonhosted.org/packages/74/69/829919eeadff695338f98fa12bb99e45490761a2010c8d688d88b6df194a/pafy-0.5.5-py2.py3-none-any.whl
Collecting pycountry
  Downloading https://files.pythonhosted.org/packages/16/b6/154fe93072051d8ce7bf197690957b6d0ac9a21d51c9a1d05bd7c6fdb16f/pycountry-19.8.18.tar.gz (10.0MB)
    100% |████████████████████████████████| 10.0MB 17kB/s 
Collecting titlecase
  Downloading https://files.pythonhosted.org/packages/3b/78/5b9faa7b9288c9fa5a4fdb6989f5e675744511ab6cff0489a0c7744a4f6b/titlecase-0.12.0.tar.gz
Collecting pychromecast
  Downloading https://files.pythonhosted.org/packages/33/c1/c46e030426edc7d6126d7fd9d243c593e7a0310681656e8ee66380350829/PyChromecast-4.1.0-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 827kB/s 
Collecting plexapi
  Downloading https://files.pythonhosted.org/packages/16/85/54fa59b0b6dc42a3d0b7280adbfe4b452df57e4755a50b092be2c9885c3c/PlexAPI-3.3.0.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 1.1MB/s 
Collecting fuzzywuzzy
  Downloading https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
Collecting eventlet
  Downloading https://files.pythonhosted.org/packages/ef/01/83454d11bac9015f34e93cf11efcae169390ddf2df97cb73ca86de6465ed/eventlet-0.25.1-py2.py3-none-any.whl (222kB)
    100% |████████████████████████████████| 225kB 649kB/s 
Collecting python-Levenshtein
  Downloading https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 1.1MB/s 
Collecting MechanicalSoup>=0.4.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/0b/fe/4f871ec3379080c5979815bfec3266871e555eebf4879f551a7e5dee4766/MechanicalSoup-0.12.0-py2.py3-none-any.whl
Collecting appdirs>=1.1.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting decorator>=3.3.1 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting future (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 107kB/s 
Collecting gpsoauth>=0.2.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/96/a1/2b366c602ee081def4dd80624581dfa8eb23d20c5a51f8a2591c40fa8d41/gpsoauth-0.4.1.tar.gz
Collecting mock>=0.7.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting mutagen>=1.34 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/08/34/e68d377ab1375af21feef9226d778ed3e6618b2f572538a85fc7c8ae9a4b/mutagen-1.43.0-py2.py3-none-any.whl (212kB)
    100% |████████████████████████████████| 215kB 646kB/s 
Requirement already satisfied, skipping upgrade: oauth2client>=1.1 in /usr/local/lib/python2.7/dist-packages (from gmusicapi) (4.1.3)
Collecting proboscis>=1.2.5.1 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/3c/c8/c187818ab8d0faecdc3c16c1e0b2e522f3b38570f0fb91dcae21662019d0/proboscis-1.2.6.0.tar.gz
Collecting protobuf>=3.0.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/4e/26/1517e42a81de4f28ed0f3cdadb628c1b72f3a28f38323a05e251f5df0a29/protobuf-3.11.1-py2.py3-none-any.whl (434kB)
    100% |████████████████████████████████| 440kB 368kB/s 
Collecting python-dateutil!=2.0,>=1.3 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 594kB/s 
Collecting requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 946kB/s 
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/lib/python2.7/dist-packages (from gmusicapi) (1.12.0)
Collecting validictory!=0.9.2,>=0.8.0 (from gmusicapi)
  Downloading https://files.pythonhosted.org/packages/4f/ca/80c04ee324233dacca3258153e7c71fc667fe032e0b21bae788f83fe4103/validictory-1.1.2-py2.py3-none-any.whl
Collecting fudge>=1.0.3 (from soundcloud)
  Downloading https://files.pythonhosted.org/packages/65/71/f44731d536a9b146c5d9a4eb9d3bacd8aae7dbb3597382f3f9bd3d015577/fudge-1.1.1.tar.gz (87kB)
    100% |████████████████████████████████| 92kB 1.2MB/s 
Collecting simplejson>=2.0 (from soundcloud)
  Downloading https://files.pythonhosted.org/packages/98/87/a7b98aa9256c8843f92878966dc3d8d914c14aad97e2c5ce4798d5743e07/simplejson-3.17.0.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 1.2MB/s 
Collecting zeroconf>=0.17.7 (from pychromecast)
  Downloading https://files.pythonhosted.org/packages/35/1a/63df0e17b10f55d5e352048705ba6d4a2a8afb622914441b98b6f966743f/zeroconf-0.24.0.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 1.0MB/s 
Collecting casttube>=0.2.0 (from pychromecast)
  Downloading https://files.pythonhosted.org/packages/54/d1/8edc98ef2aa08eed8dd72e2ef31b6658ba222ea8d228a4c2c3e73a58991a/casttube-0.2.0.tar.gz
Collecting tqdm (from plexapi)
  Downloading https://files.pythonhosted.org/packages/71/b0/6d63e33dbf5935dccd334ee2b83cc4d3828817de6faaa3a3f7f5b8cc5141/tqdm-4.40.1-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 1.1MB/s 
Collecting websocket-client (from plexapi)
  Downloading https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 693kB/s 
Requirement already satisfied, skipping upgrade: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from eventlet) (1.1.6)
Collecting dnspython>=1.15.0 (from eventlet)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 743kB/s 
Collecting greenlet>=0.3 (from eventlet)
  Downloading https://files.pythonhosted.org/packages/f8/e8/b30ae23b45f69aa3f024b46064c0ac8e5fcb4f22ace0dca8d6f9c8bbe5e7/greenlet-0.4.15.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 1.1MB/s 
Collecting monotonic>=1.4 (from eventlet)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python2.7/dist-packages (from python-Levenshtein) (40.8.0)
Collecting beautifulsoup4>=4.4 (from MechanicalSoup>=0.4.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/f9/d9/183705a87492249b212d88eef740995f55076195bcf45ed59306c146e42d/beautifulsoup4-4.8.1-py2-none-any.whl (102kB)
    100% |████████████████████████████████| 102kB 1.1MB/s 
Collecting lxml (from MechanicalSoup>=0.4.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/06/70/1fe9b1872406b98498affe41dc261b75ccb3e38762de3c718be5e981bbcd/lxml-4.4.2-cp27-cp27mu-manylinux1_i686.whl (5.4MB)
    100% |████████████████████████████████| 5.4MB 33kB/s 
Collecting pycryptodomex>=3.0 (from gpsoauth>=0.2.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/be/2c/75a4c4151fb079b07116916f838fcd925df1f9631e7b93025ed968d29a8a/pycryptodomex-3.9.4-cp27-cp27mu-manylinux1_i686.whl (9.7MB)
    100% |████████████████████████████████| 9.7MB 18kB/s 
Collecting funcsigs>=1; python_version < "3.3" (from mock>=0.7.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi) (0.4.8)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi) (0.2.7)
Requirement already satisfied, skipping upgrade: httplib2>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi) (0.14.0)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi) (4.0)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 986kB/s 
Collecting certifi>=2017.4.17 (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 843kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 950kB/s 
Collecting idna<2.9,>=2.5 (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.1MB/s 
Collecting ifaddr (from zeroconf>=0.17.7->pychromecast)
  Downloading https://files.pythonhosted.org/packages/9f/54/d92bda685093ebc70e2057abfa83ef1b3fb0ae2b6357262a3e19dfe96bb8/ifaddr-0.1.6.tar.gz
Collecting typing (from zeroconf>=0.17.7->pychromecast)
  Downloading https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4>=4.4->MechanicalSoup>=0.4.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: ipaddress in /usr/lib/python2.7/dist-packages (from ifaddr->zeroconf>=0.17.7->pychromecast) (1.0.17)
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4>=4.4->MechanicalSoup>=0.4.0->gmusicapi)
  Downloading https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Building wheels for collected packages: gmusicapi, pycountry, titlecase, plexapi, python-Levenshtein, future, gpsoauth, proboscis, fudge, simplejson, zeroconf, casttube, greenlet, ifaddr
  Running setup.py bdist_wheel for gmusicapi ... done
  Stored in directory: /root/.cache/pip/wheels/2e/35/80/495bfdd474304bf353f66aa4431e616a45cd1f1fcce02da316
  Running setup.py bdist_wheel for pycountry ... done
  Stored in directory: /root/.cache/pip/wheels/a2/98/bf/f0fa1c6bf8cf2cbdb750d583f84be51c2cd8272460b8b36bd3
  Running setup.py bdist_wheel for titlecase ... done
  Stored in directory: /root/.cache/pip/wheels/9f/fb/8f/4d61939e2447b1b8c13f6ceeca035383c14d4228e88b174402
  Running setup.py bdist_wheel for plexapi ... done
  Stored in directory: /root/.cache/pip/wheels/13/56/b1/99aa82f86b66f61ca0298af61a0636186595497801037a8f6f
  Running setup.py bdist_wheel for python-Levenshtein ... done
  Stored in directory: /root/.cache/pip/wheels/de/c2/93/660fd5f7559049268ad2dc6d81c4e39e9e36518766eaf7e342
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
  Running setup.py bdist_wheel for gpsoauth ... done
  Stored in directory: /root/.cache/pip/wheels/a2/14/fc/0754368beb9f2fc1515b7974c23261eac42bd305ff94c6ea4e
  Running setup.py bdist_wheel for proboscis ... done
  Stored in directory: /root/.cache/pip/wheels/8c/c9/82/8aa441245194f414659baab25a4f6b3b0d604822c0aff8fb7c
  Running setup.py bdist_wheel for fudge ... done
  Stored in directory: /root/.cache/pip/wheels/36/c8/c1/587018b4a2e09736369e20f1c58736f6bbb7472167e756fceb
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/86/c0/83/dcd0339abb2640544bb8e0938aab2d069cef55e5647ce6e097
  Running setup.py bdist_wheel for zeroconf ... done
  Stored in directory: /root/.cache/pip/wheels/f9/4c/34/e124bc1d73bf187972bacf2278f013a823c5316e5c68c5ee44
  Running setup.py bdist_wheel for casttube ... done
  Stored in directory: /root/.cache/pip/wheels/b1/67/2f/479590159263135896ea98461bda264df8420f60a477ba69de
  Running setup.py bdist_wheel for greenlet ... done
  Stored in directory: /root/.cache/pip/wheels/cc/28/5a/2687513046a61b17dd78be058a43a069c271f5d7b7623f3dfd
  Running setup.py bdist_wheel for ifaddr ... done
  Stored in directory: /root/.cache/pip/wheels/1a/78/2c/a5bbe977f6d91039ddc1d657e780cb55a493aa5d2c0b64637a
Successfully built gmusicapi pycountry titlecase plexapi python-Levenshtein future gpsoauth proboscis fudge simplejson zeroconf casttube greenlet ifaddr
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, lxml, urllib3, certifi, chardet, idna, requests, MechanicalSoup, appdirs, decorator, future, pycryptodomex, gpsoauth, funcsigs, mock, mutagen, proboscis, protobuf, python-dateutil, validictory, gmusicapi, fudge, simplejson, soundcloud, youtube-dl, pafy, pycountry, titlecase, ifaddr, typing, zeroconf, casttube, pychromecast, tqdm, websocket-client, plexapi, fuzzywuzzy, dnspython, greenlet, monotonic, eventlet, python-Levenshtein
Successfully installed MechanicalSoup-0.12.0 appdirs-1.4.3 backports.functools-lru-cache-1.6.1 beautifulsoup4-4.8.1 casttube-0.2.0 certifi-2019.11.28 chardet-3.0.4 decorator-4.4.1 dnspython-1.16.0 eventlet-0.25.1 fudge-1.1.1 funcsigs-1.0.2 future-0.18.2 fuzzywuzzy-0.17.0 gmusicapi-12.1.1 gpsoauth-0.4.1 greenlet-0.4.15 idna-2.8 ifaddr-0.1.6 lxml-4.4.2 mock-3.0.5 monotonic-1.5 mutagen-1.43.0 pafy-0.5.5 plexapi-3.3.0 proboscis-1.2.6.0 protobuf-3.11.1 pychromecast-4.1.0 pycountry-19.8.18 pycryptodomex-3.9.4 python-Levenshtein-0.12.0 python-dateutil-2.8.1 requests-2.22.0 simplejson-3.17.0 soundcloud-0.5.0 soupsieve-1.9.5 titlecase-0.12.0 tqdm-4.40.1 typing-3.7.4.1 urllib3-1.25.7 validictory-1.1.2 websocket-client-0.56.0 youtube-dl-2019.11.28 zeroconf-0.24.0
Collecting git+https://github.com/plamere/spotipy.git
  Cloning https://github.com/plamere/spotipy.git to /tmp/pip-req-build-xYMnCV
Requirement already satisfied, skipping upgrade: requests>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from spotipy==2.4.4) (2.22.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from spotipy==2.4.4) (1.12.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4) (1.25.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4) (2019.11.28)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4) (2.8)
Building wheels for collected packages: spotipy
  Running setup.py bdist_wheel for spotipy ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-ttmtMJ/wheels/98/31/d8/02e824694a8c8e6f3451008196487ba388f623657b47c04a93
Successfully built spotipy
Installing collected packages: spotipy
Successfully installed spotipy-2.4.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  hicolor-icon-theme imagemagick-6-common imagemagick-6.q16 libdjvulibre-text
  libdjvulibre21 libilmbase23 libjxr-tools libjxr0 liblqr-1-0
  libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickwand-6.q16-6
  libnetpbm10 libopenexr23 libwmf0.2-7 netpbm
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libspotify12
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 973 kB of archives.
After this operation, 2,102 kB of additional disk space will be used.
Get:1 http://apt.mopidy.com stable/non-free i386 libspotify12 i386 12.1.51-1 [973 kB]
Fetched 973 kB in 2s (506 kB/s)      
Selecting previously unselected package libspotify12.
(Reading database ... 65836 files and directories currently installed.)
Preparing to unpack .../libspotify12_12.1.51-1_i386.deb ...
Unpacking libspotify12 (12.1.51-1) ...
Setting up libspotify12 (12.1.51-1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tizonia-all
Oops. Something went wrong!

### Steps to Reproduce

1. Execute this script:
https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh

**Expected behavior:** The correct installation

**Actual behaviour:** Oops. Something went wrong!

**Reproduces how often:** Always

### Versions
The last taken from the script.

### Installation Method Used
I used the sh script.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report an issue.

Sorry to hear that you are experiencing problems. I believe that you are trying to install Tizonia on an i386 version of Debian Buster. Unfortunately, there are only amd64 Debian packages of Tizonia for Buster.

See the Debian-based OS support matrix here:
- https://github.com/tizonia/tizonia-openmax-il#debian--ubuntu--raspbian

You can try the Snap package. There are i386 versions of the Snap of Tizonia that will work on your machine.

I hope that helps.

**Comment by dominikhaid** [comment]
I have the same issue on bullseye 64 bit version.
