### ISSUE TITLE
[Feature Request] Pressing "?" during playback should bring up --help commands

### ISSUE THREAD

**Issue by tcaddy** [tizonia/tizonia-openmax-il#641]
### Description
[Feature Request] Pressing "?" (and/or "h") during playback should bring up `tizonia --help keyboard` content

### Steps to Reproduce
Press "?" during playback

**Expected behavior:**
Display helpful message similar to output of `tizonia --help keyboard`

**Actual behavior:**
Nothing

**Reproduces how often:**
100%

### Versions
v0.18.0 on Ubuntu 19.10

### Installation Method Used
Snap

### Additional Information
n/a

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to suggest a new feature.

This is is useful. It would be good is someone could contribute some time to get it implemented. As things stand, I have too much in my plate at the moment. I will be more than happy to provide guidance if needed.

**Comment by juanrubio** [comment]
Closing this now. The implementation is now in the master branch. The release of 0.22.0 is in progress and binaries will be out in the next hours.
