### ISSUE TITLE
Error 404 on bintray raspbian buster 0.19

### ISSUE THREAD

**Issue by sonicyouch** [tizonia/tizonia-openmax-il#645]
Hi !
First of all thanks for your job on that project :)

Reporting issue : 
The apt source  ‘https://dl.bintray.com/tizonia/raspbian buster main’ doesn’t work.
Bintray returns a 404 not found error.

Thanks  in advance for fixing it :)

**Comment by tizonia** [comment]
Hi!, thanks for stopping by.

v0.19.0 was released on Friday, and Debian packages are not yet uploaded to the Bintray repositories. They will be ready very soon. I'll ping you here when they are in the repos.

**Comment by sonicyouch** [comment]
Hi!
okay, got it:)
I'll be patient so!
thanks for your quick answer

**Comment by tizonia** [comment]
Hi @sonicyouch 

Raspbian buster 0.19.0 is now in the Bintray repos. Please run the installation script to get it.
