### ISSUE TITLE
AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by Zamlet** [tizonia/tizonia-openmax-il#647]
### Description

Tizonia will not run correctly on my system.  It generates an AttributeError every time.

### Steps to Reproduce

1. Upgrade from Tizonia 0.18 to 0.19. (not sure if this is relevant)
2. Attempt to run Tizonia in terminal. Below error results.
3. Install Python modules 'plexapi' and 'fuzzywuzzy'.  (I made sure to use pip3 since Tizonia now uses python3.  After first installing module 'wheel', both of these modules appear to have installed correctly.)
4. See step 2.

--------------------
**Expected behavior:** [What you expect to happen]

Tizonia searches Plex server for requested music, finds it, and plays it.

--------------------
**Actual behaviour:** [What actually happens]

$ tizonia --plex-audio-album 'Dark Side of the Moon'
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Plex] [Connecting] : 'http://IP_ADDR:32400'.
Traceback (most recent call last):
  File "&lt;string&gt;", line 2, in &lt;module&gt;
AttributeError: module 'importlib' has no attribute 'util'

Python modules 'plexapi' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
$ _

Note: I have successfully installed both modules 'plexapi' and 'fuzzywuzzy'. If either of these modules requires further configuration, I do not know what to do.

--------------------
**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

$ tizonia --debug
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_65_1]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]

$ cat /etc/os-release
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tina
UBUNTU_CODENAME=bionic

### Installation Method Used

Upgrade from tizonia 18.0 using apt-get with repository at:
deb https://dl.bintray.com/tizonia/ubuntu bionic main

### Additional Information

1. Added new line to ~/.config/tizonia/tizonia.conf (0.18 version, since no new one was supplied with version 0.19) reading:
plex.music.section = Modern
(This is the only change I made to the 0.18 .conf file.  Commenting out this line makes no difference - same error.)

2. Also, while poking around trying to work around this on my own, I stumbled upon the following page: https://hg.python.org/cpython/file/tip/Lib/importlib/__init__.py. Since I cannot tell if this source is for Python 2 or Python 3, I do not know how relevant the comments from line 6 through 11 might or might not be.  But I thought I'd include the information anyway.

**Comment by tizonia** [comment]
Hi!, @Zamlet , thanks for reporting this.

The upgrade to 0.19.0 needs re-installation of the Python dependencies, to make sure all the Python 3 deps are available in the system when you run 0.19.0.

The easiest way of doing that would be to re-run the installation script:
```
$ curl -kL https://goo.gl/Vu8qGR | bash
```
Could you please let me know if this would fix it for you?

Thanks

**Comment by Zamlet** [comment]
Well, that did indeed fix this problem.  tizonia seems to be working now!  We can close this issue, but there are a couple of strange side effects that I'd like to know about first (we can take this offline if you prefer):
1) It still left the old v 0.18 tizonia.conf file behind.  The new option for specifying the music section (see #610) does not seem to work when added to this .conf file, but perhaps reading it from there hasn't been implemented yet, or perhaps I'm just doing it wrong due to lack of documentation.
2) During the re-installation process, the installation script uninstalled a program on my system called "thonny" and did not re-install it.  I am trying to learn Python and I like this program.  Does some dependency of Tizonia have a conflict with it?  Is there any reason I shouldn't re-install it?

**Comment by tizonia** [comment]
Hi! @Zamlet 

Glad to hear that Tizonia is working now. I'll close this item for now.

> old v 0.18 tizonia.conf file behind

This is correct. Tizonia will not overwrite your existing configuration file. But you can add the new configuration items manually is you need to. That always works fine unless there is a bug somewhere else. Try with the command-line switch `--plex-music-section arg` to see if the functionality works for you. If it doesn't, please open another issue and will fix it there.

>  the installation script uninstalled "thonny"

Are you sure this was removed from your system by the installation script?. That's odd. I can't really think that would happen. Tizonia's installation script does however re-install one package. This is 'python3-pip'. The reason is that in some systems, pip3 is not found unless the package is reinstalled.
See: https://superuser.com/questions/769920/python3-pip-installed-but-pip3-command-not-found. It happened to my in a couple of my systems, so I decided to add this workaround in the script. But I believe that should not uninstall any other program on your system. 

I'll do some verifications.

**Comment by Zamlet** [comment]
The command-line option definitely works.  I've tried it with several different music libraries on my Plex server, and it accesses them without any problem.  Thanks!

As for the .conf file, my concern was that I wasn't getting the latest version that take into account other changes elsewhere in the program, like perhaps Google Music options that have changed, in case I ever decide to use it.  Old configuration files tend to cause problems down the road.  I'd rather the script backed up my old config file then copied the new one into place, and advised me that it had done so so that I could manually copy my changed options over to the newer file.

And yes, I'm 100% certain that something in the installation script caused thonny to be uninstalled, probably by apt-get.  I watched it happen.  I'm sorry I didn't save any record of it for you, but it was roughly the same point in the script that pip3 got uninstalled and re-installed.  I'm still unclear whether it's safe to re-install it myself or not.

**Comment by Zamlet** [comment]
For whatever it's worth, I re-installed thonny and both it and Tizonia seem to be co-existing without any problem.  I'm not sure why it needed to be uninstalled in the first place, and apt-get isn't talking... :}

**Comment by tizonia** [comment]
@Zamlet 

Thanks a lot for your feedback. This is super useful. Please keep it coming! 

Let me try to answer your questions:

I can't really find any logical connection between thonny being uninstalled and the installation of TIzonia. But I am not saying that this is impossible. I will do some testing on my end.

Regarding the old vs new config files. Automated updates of a config file that already exits in the user's home directory is a more complex task than it would seem at first sight (maybe one day...). To avoid having to introduce that kind of complexity, I always make sure the new config options are completely backguard-compatible. So far, in 19 releases, there has been no need to amend an existing configuration file to make it compatible with a newer release of the software. 

On the other hand, manually adding the new config options is an easy enough task. The most recent configuration file template is always installed under /etc/xdg/tizonia/tizonia.conf. So observing the differences between the official template for the currently installed version and the user's local file is a reasonable compromise IMO.

As for the documentation, you are absolutely right, there is a need to document the additions that take place in each release. I always try to do this in Tizonia's web site:
http://tizonia.org/news/2019/03/17/release-0-18-0/

I'm still in the process of updating the Tizonia news section to provide information on the new config options that appeared in 0.19.0.

I hope that helps

**Comment by Zamlet** [comment]
Thanks for the information.

re: thonny: it's definitely not impossible!  I watched it happen.  My guess would be that the version of thonny that I had was dependent on some python module or other executable (pip3, perhaps?) that your script uninstalled and re-installed in order to get the latest version, and that for apt-get to uninstall this other thing, it felt it had to uninstall thonny as well.  It may not be trivial to reproduce.  But I am not a system guru and do not really understand what happens with apt-get in the background, so this is just a guess.

I wouldn't really expect an automatic update (diff and/or merger) of the configuration file - that would indeed be a non-trivial task, prone to error, and really not necessary at this stage of development, if ever.  But at the same time, it's a bit unnerving for me personally to have a configuration file that does not match the version of the software it pertains to.  I've seen too many problems result from this in the past.

Perhaps a compromise during installation: check if there is a newer version of the .conf file that could be installed, then ask the user what his/her preference is: 1) rename the old .conf file and copy the new one into place as-is (to take effect upon next launch), or 2) leave the old .conf file untouched and copy the new one into the same directory (*) with a different name (so that the old one remains in effect).

Now that I can actually make tizonia work with my music collection (I never did reconfigure my library to work with 0.18), I find it quite handy.  I've already written a wrapper script to make it easier to access the various options.  I can't wait to see what it develops into over the next year or two!  I assume that if I have ideas for new features, etc., that I should post them as new issues, so that we can finally lay poor #647 here to rest.

----------------
* - not just somewhere like /etc/xdg/tizonia/tizonia.conf where I suspect that most users, myself included, would never in a million years think to look for it! :)

**Comment by tizonia** [comment]
There is a config help in the tool. Although most people have not seen it. I think it is a good place to warn the users to update their config files to the latest version. Maybe someone would like to contribute a simple script that can warn the user of what things are not present in their old configs, and perhaps even update those things on demand.

```
tizonia --help config
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Configuration file: 'tizonia.conf'

Tizonia creates its config file in one of the following locations when it
first starts (add your user credentials here):
    - Debian or AUR packages: $HOME/.config/tizonia/tizonia.conf
    - Snap package: $HOME/snap/tizonia/current/.config/tizonia/tizonia.conf

Example configuration files may also be found at 
    - /etc/xdg/tizonia/tizonia.conf or 
    - /snap/tizonia/current/etc/xdg/tizonia/tizonia.conf.
```
