### ISSUE TITLE
Using Tizonia in Cron jobs

### ISSUE THREAD

**Issue by suonimusicaidee** [tizonia/tizonia-openmax-il#651]
### Description

Calling Tizonia from Crontab does not give any result

### Steps to Reproduce

1. Edit your Crontab with crontab -e
2. Add a Tizonia command to be reproduced at a certain time, this is what I've used for test (every minute):
* * * * * tizonia --spotify-playlist-id 1Sr0qSlojHmWQaP70ZqdK9
3. Wait till the end of the world, nothing happens 😭

**Expected behavior:**
The playlist should start again every minute

**Actual behaviour:**
Nothing

**Reproduces how often:**
100%

### Versions

tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_67]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v18.12]

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Installation Method Used

$ curl -kL https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh | bash

### Additional Information

Needed to install Pulse, version 12.2 installed.

**Comment by suonimusicaidee** [comment]
Solved: just needed to put the command in a script and execute it within a terminal, with the right options. In my case:
0 19 * * * lxterminal -l -e '/path-to/script.sh '

**Comment by tizonia** [comment]
@suonimusicaidee 

Good to hear that you managed to solve that issue.

Thanks for trying the software
