### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by pickfire** [tizonia/tizonia-openmax-il#655]
# Issue Template

### Description

It would be nice to read `tizonia` help with `man tizonia` like other man pages. Everything in one page and render nicely in less pager based on the user man page settings.

### Installation Method Used

Should be packaged along with source.

### Additional Information

Man pages could possibly get input from command line.

**Comment by tizonia** [comment]
Hi @pickfire !

Thanks for taking the time to suggest new features and improvements.

This is obviously useful. I will keep it open in case someone wants to help to produce the man pages.

**Comment by tizonia** [comment]
A man page has been added now and will be installed as part of the Debian/AUR/Snap installations.
