### ISSUE TITLE
Mopidy APT source is dead (404)

### ISSUE THREAD

**Issue by marsch2** [tizonia/tizonia-openmax-il#670]
### Description

The Mopidy source seems to be dead and give me a 404 when apt updating.

### Steps to Reproduce

1. Running the install script on my machine (Ubuntu 18.04)

Mopidy source for libspotify gives a 404 when calling apt update

What fixed it for me was using:
`sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list`
instead of 
`echo "deb http://apt.mopidy.com/ stable main contrib non-free" | sudo tee -a /etc/apt/sources.list`
as stated on http://docs.mopidy.com/en/release-2.3/installation/debian/

**Comment by tizonia** [comment]
Hi @marsch2 !

thanks for reporting this issue and more importantly, the solution!

I noticed this a few days ago, but I did not have a chance to look for a resolution.

**Comment by tizonia** [comment]
Closing this now
