### ISSUE TITLE
Improve tizonia.org security by using HTTPS/SSL

### ISSUE THREAD

**Issue by mclang** [tizonia/tizonia-openmax-il#672]
### Tizonia home page should use HTTPS

It's 2020 and there is Let's Encrypt - there is no reason to keep using plain HTTP web pages. Or if there is, it should be stated somewhere.

**Comment by tizonia** [comment]
Hi @mclang !

Thanks a lot for the reminder. 

Please check now. The web site is now available over https.

**Comment by mclang** [comment]
Nice :+1: 

Sorry for the late response...
