### ISSUE TITLE
I can not compile tizonia-openmax-il-0.19.0

### ISSUE THREAD

**Issue by semsv** [tizonia/tizonia-openmax-il#680]
alesya@alsy:~/Downloads/tizonia-openmax-il-0.19.0$ sudo autoreconf -ifs
configure.ac:18: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/src/tools/autoconf-2.69.tar.xz/bin/autoconf failed with exit status: 1

**Comment by semsv** [comment]
alesya@alsy:~/Downloads/tizonia-openmax-il-0.16.0$ automake --version
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
alesya@alsy:~/Downloads/tizonia-openmax-il-0.16.0$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
alesya@alsy:~/Downloads/tizonia-openmax-il-0.16.0$ m4 --version
m4 (GNU M4) 1.4.18
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.

**Comment by tizonia** [comment]
Hi!, thanks for stopping by.

Please follow the instructions for building from source. Note that these assume a Ubuntu/Debian compatible system:
https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md

**Comment by semsv** [comment]
Hello! Thank you for the answer, but I would like to compile their sources using the traditional method:

The traditional method
Alternatively, from the top of Tizonia's repo, one can also do the familiar:

     $ autoreconf -ifs
     $ ./configure # or ./configure --disable-player to disable the command-line player program
     $ make
     $ make install

If of course this is possible?!Thanks!

**Comment by tizonia** [comment]
> I would like to compile their sources using the traditional method

Of course, you can do it that way. But before issuing those commands, you need to install the development dependencies. I think that is what's missing for you.

```
Setup the following environment variables
    $ export TIZONIA_REPO_DIR=/path/to/tizonia/repo # (e.g. /home/user/tizonia-openmax-il)
    $ export TIZONIA_INSTALL_DIR=/path/to/install/dir # (e.g. /usr or /home/user/temp)
    $ export PATH=$TIZONIA_REPO_DIR/tools:$PATH

    Set the PYTHONPATH accordingly (replace X to match the python version on your system)
    $ export PYTHONPATH=$TIZONIA_INSTALL_DIR/lib/python3.X/site-packages:$PYTHONPATH

    Now install everything that is required to build Tizonia from source (Debian derivative assumed)
    $ tizonia-dev-build --deps
```

**Comment by tizonia** [comment]
Closing this issue for now. Please add a comment here if this is still an issue for you.
