### ISSUE TITLE
"AttributeError: module 'importlib' has no attribute 'util'" on Raspberrian 

### ISSUE THREAD

**Issue by peterfroehlich** [tizonia/tizonia-openmax-il#681]
### Description
Tizonia fails to install correctly on a fresh install of Raspberrian Stretch on a Raspberry Pi 3 installed via the 'curl' method.

```
$> tizonia --youtube-audio-search fail
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'

Python modules 'pafy', 'youtube-dl' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

### Steps to Reproduce

1. Fresh Stretch install on Raspberry 
2. Use 'curl' install method (curl -kL https://goo.gl/Vu8qGR | bash)
3. Watch Installation complete successfully 
4. Try 'tizonia --youtube-audio-search fail' (other play commands fail as well)

**Reproduces how often:** 
Tried 3 times, once with manual Python 3 installation and activation as default.

### Versions

```
$ tizonia --debug
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_62]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v0.7.91]

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ python --version
Python 3.5.3
```

### Installation Method Used

curl -kL https://goo.gl/Vu8qGR | bash

**Comment by tizonia** [comment]
Hi @peterfroehlich, sorry to hear that you are experiencing issues.

> VERSION="9 (stretch)"
> Python 3.5.3

Have you perhaps used `update-alternatives` to make Python 3 the default Python installation? 
A fresh Raspbian Stretch should have come with default Python version 2.7.x (if I'm not mistaken).

The Tizonia install script assumes your default Python in Stretch is version 2:
https://github.com/tizonia/tizonia-openmax-il/blob/eed901e408ffcb9ab2527ce37670fcf4bd0439fe/tools/install.sh#L51

So all the Python dependencies are installed for Python 2. You should be able to fix this by installing the Python 3 versions, like this:

```
sudo apt-get -y remove python3-pip \
        && sudo apt-get -y install python3-dev python3-pip \
        && sudo -H pip3 install --upgrade \
                gmusicapi \
                soundcloud \
                youtube-dl \
                pafy \
                pycountry \
                titlecase \
                pychromecast \
                plexapi \
                fuzzywuzzy \
                eventlet \
                python-Levenshtein \
        && sudo -H pip3 install git+https://github.com/plamere/spotipy.git --upgrade
```

Perhaps the installation script should detect the default Python installation....

**Comment by peterfroehlich** [comment]
Thanks for the fast answer! 

I tried 2 times with Python 2.7 as default, literally running the curl command on a fresh, and updated Raspberrian with the only change being the wifi setup. 

The error stayed the same, with Python 2 or 3 as default...

**Comment by tizonia** [comment]
I think the Python environment in your system is slightly broken and Tizonia is running under the wrong Python interpreter ('wrong' for Tizonia 0.19.0 means Python version 2).

If you run this simple script, you will see different results in Python 2 vs Python 3.
```
import importlib
spec = importlib.util.find_spec('pafy')
if not spec:
    raise ValueError
else:
    print("Success!")
```

E.g.:

```
➜   python3 importlib-test.py 
Success!
➜   python2 importlib-test.py
Traceback (most recent call last):
  File "importlib-test.py", line 2, in <module>
    spec = importlib.util.find_spec('pafy')
AttributeError: 'module' object has no attribute 'util'
```

**Comment by peterfroehlich** [comment]
Hm. I experimented a bit: I failed to reproduce your example. 
If I use exactly your script, it fails with both python2.7 and python3 (python 3.7.3 to be exact). 

It works when I change "import importlib" to "import importlib.util". 
It seems importing the package does not import all the submodules (anymore).

```
import importlib.util

spec = importlib.util.find_spec('pafy')
if not spec:
    raise ValueError
else:
    print("Success!")
```

I've looked into the __init__.py of the importlib package on my system and the version in git ([1]), util is not explicitly referenced in __all__. 

According to this link ([2]) the behaviour of the python3 import system changed a few times over the last versions, maybe this broke something implicit that worked before.

[1]: https://github.com/python/cpython/blob/master/Lib/importlib/__init__.py
[2]: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

**Comment by tizonia** [comment]
I've got two RPis, a Pi3 running Stretch and a Pi4 with Buster and both are running the Bintray binaries of Tizonia, with no issues. So I'm pretty sure your issue is environment-related.

Can you paste here the result of running these two commands?

```
$ export TIZONIA_YOUTUBEPROXY_DEBUG=1
$ tizonia --youtube-audio-mix-search 'metallica'
```

**Comment by peterfroehlich** [comment]
Here is the output of the commands:
```
pi@raspberrypi:~ $ export TIZONIA_YOUTUBEPROXY_DEBUG=1
pi@raspberrypi:~ $ tizonia --youtube-audio-mix-search 'metallica'
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'

Python modules 'pafy', 'youtube-dl' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

But I think I found it: 
I tried the install script on a blank Docker container (based on debian:stretch). That worked fine. 
I looked for differences and noticed that the script installs Version 0.18.0, not 0.19.0 like on the Pi. 
I found your [update instructions] and after running Step2 for 0.19.0 it works. 

Thanks for you help!

[update instructions]: https://github.com/tizonia/tizonia-openmax-il#upgrade-debian--ubuntu--raspbian

**Comment by tizonia** [comment]
Excellent! Happy to hear that you got it working.
