### ISSUE TITLE
New build system based on Meson (phase I)

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#685]
The idea is to have Meson replace Autotools as the primary build system of Tizonia. Meson will drastically reduce the time to build Tizonia.

The idea is to keep Meson and Autotools coexisting for at least 1-2 release cycles. In an initial stage, the Meson build system will be released in 'preview' mode and will not be used for Debian packaging. In a second stage, Debian files will be migrated to Meson and at that point, Autotools deprecation will be announced.

**Comment by tizonia** [comment]
@lgbaldoni delivered this feature with PRs #657, #658, #659, #661, #662, #663, #664, #665, #666, #671, #673, #674, #676)

**Comment by lgbaldoni** [comment]
Sorry about the docs, I've been rather busy with personal matters of late and I'm kind of stuck halfway through it.

**Comment by tizonia** [comment]
Hi Luigi, absolutely no worries!

The docs site really needed a good shake up and that really was on me. After the docs site was updated, the man page was easy.

I would like to fix the macOS port. It would be great to have your help with that. Maybe when you are free.
