### ISSUE TITLE
 OMX_ErrorInsufficientResources on LXDE and Raspbian 10

### ISSUE THREAD

**Issue by ixolius** [tizonia/tizonia-openmax-il#704]
# OMX_ErrorInsufficientResources on LXDE

### Description

When trying tizonia on Raspian 10, I get a OMX_ErrorInsufficientResources, if I try tp play spotify-playlists. It may be related to #501 , but I can not be sure about it.

### Steps to Reproduce

1. Play a playlist on spotify, like
`tizonia --spotify-playlist-id coolSpotifyPlaylist --spotify-owner NiceDJ`

**Expected behavior:** tizonia makes spotify find the playlist and plays it

**Actual behaviour:** The playlist is found and the tracks are loaded, but tizonia suddently exits with:
```
[OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```

**Reproduces how often:** Always

### Versions

Tizonia Version: 0.21.0
Debug Info:
```
	    * [Linux@4.19.97-v7+-#1294 SMP Thu Jan 30 13:15:58 GMT 2020]
	    * [Boost 1_67]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v18.12]
```
OS: Raspbian 10 (buster)
DE: LXDE
Pulseaudio: version 12

### Installation Method Used

Curl + install script, added bintray rep, but installation was from the script.

### Additional Information

As I said, it might be the same problem as #501 , but I'm not sure. Thanks in advance for help to figure it out.

**Comment by tizonia** [comment]
Hi @ixolius !

Thanks for taking the time to report issues in the bug tracker. That's always useful.

Please have a look at the docs here:
https://docs.tizonia.org/manual/raspberrypi.html

I believe that if you use the Alsa audio renderer, it will work fine.

**Comment by ixolius** [comment]
Ok, that did it. Sorry, I looked at the docs but totally oversaw the PI section. I use I3 as DE on my other PCs, so I thought it's the same issue. Works fine now. Thank you very much for the quick response.
