### ISSUE TITLE
meson build fails: regression introduced in Meson v0.54.0

### ISSUE THREAD

**Issue by tizonia** [tizonia/tizonia-openmax-il#705]
Just for documentation purposes:

Tizonia's meson builds currently fail with the latest version of Meson (0.54.0). This has been reported in the Meson project:
https://github.com/mesonbuild/meson/issues/6844

```
Run-time dependency Boost (modules: chrono, filesystem, program_options, python3, system, thread) found: NO 

meson.build:2:0: ERROR: Dependency "boost" not found
```
A fix is already available in Meson (hopefully to be released soon)

**Comment by tizonia** [comment]
The workaround for now is to force v0.53.0
```
pip3 uninstall --yes meson && pip3 install meson==0.53.0
```

**Comment by juanrubio** [comment]
Not really a bug in Tizonia. So closing this now.
