### ISSUE TITLE
tizyoutubeproxy  enqueue_audio_search "query" undefined bug

### ISSUE THREAD

**Issue by ddelazerda** [tizonia/tizonia-openmax-il#706]
# Issue Template

### Description

tizyoutubeproxy  enqueue_audio_search "query" undefined bug

### Steps to Reproduce

1. `TIZONIA_YOUTUBEPROXY_DEBUG=1 tizonia --youtube-api-key "MyApiKey" --youtube-audio-search "anything you want to search for"`

**Expected behavior:** 
Start playing songs from the search result

**Actual behaviour:** I get the following error:
`
[YouTube] (NameError) : name 'query' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tizyoutubeproxy.py", line 534, in enqueue_audio_search
    query["pageToken"] = wdata2["nextPageToken"]
NameError: name 'query' is not defined
`

**Reproduces how often:** 
Always

### Versions

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
```
$ tizonia --version
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>
$ tizonia --debug
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

Debug Info:
            * [Linux@5.3.0-42-generic-#34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020]
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]
```

### Installation Method Used

apt-get

### Additional Information

This seems to fix the problem:

```
diff -r /usr/lib/python3/dist-packages/tizyoutubeproxy.py /tmp/tizyoutubeproxy.py
521c521,522
<             wdata = yt_dt_search("search", generate_search_query(arg, self.api_key))
---
>             query = generate_search_query(arg, self.api_key)
>             wdata = yt_dt_search("search", query)
```

**Comment by tizonia** [comment]
Hi @ddelazerda !

Thanks for taking the time to report an issue. That's really useful.

Yes, you're absolutely right. That's a bug, and I believe your solution should work. Would you like to submit a PR with the patch?
