### ISSUE TITLE
[YouTube] (NameError) : name 'query' is not defined, [OMX_ErrorInsufficientResources]

### ISSUE THREAD

**Issue by TokyoTurtle** [tizonia/tizonia-openmax-il#709]
# Issue Template

### Description

Hi, 

I'm having trouble getting started with Tizonia (only just installed this evening for the first time). When I try and do a test search of YouTube, I get a list of results following by:

[YouTube] (NameError) : name 'query' is not defined
tizonia exiting (OMX_ErrorInsufficientResources).
 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]

I installed version 0.21.0 via the install script. I'm running on Raspbian Buster. All Python and Raspbian packages are up to date (AFAIK). I got a log4crc config from a previous GitHub issue and ran with that. The results are in the attached file.
[tizonia_log.zip](https://github.com/tizonia/tizonia-openmax-il/files/4464532/tizonia_log.zip)

### Steps to Reproduce

1. Run tizonia --youtube-audio-search "search term"
2. View list of results and error message.

**Expected behavior:**
I'd hope that the program would play the first song in the result list.

**Actual behaviour:**
As above, an error message is printed and the program exits.

**Reproduces how often:**
100%

#### Tizonia version:
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

Debug Info:
            * [Linux@4.19.97-v7+-#1294 SMP Thu Jan 30 13:15:58 GMT 2020]
            * [Boost 1_67]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v18.12]

#### OS release info:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Installation Method Used
Bintray debs, I think. At least, I copied and pasted "curl -kL https://goo.gl/Vu8qGR | bash" and rode the wave.

### Additional Information
None that I can think of.

**Comment by tizonia** [comment]
Hi!, thanks for taking the time to report issues. That's always useful.

This issue has already been fixed in #706 but not yet released. It will be released soon when version 0.22.0 is out.

Thanks!

**Comment by TokyoTurtle** [comment]
Thank you for the quick response, and my apologies for taking up your time on a duplicate issue like this (I really should have checked the closed issue list better).

**Comment by tizonia** [comment]
No issues, I rather have a duplicate than a new real issue ;-)
