### ISSUE TITLE
Issue with tizonia-remote playstatus

### ISSUE THREAD

**Issue by ebanDev** [tizonia/tizonia-openmax-il#713]
Hi, sorry to open an issue again 😁. 
I have a problem, I tried to run the command: "tizonia-remote playstatus" from php but the problem is that I get the error 
```

> Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
D-Bus per-session daemon address is: unix:abstract=/tmp/dbus-YlFkCTO4kP,guid=66ec796e3e4b2aab372688ab5e95b4ee
D-Bus per-session daemon PID is: 1316.

``` 
I get the same error when I am running the tizonia-remote playstatus command as a su
I've tried several solutions but nothing works...
Thanks again for this wonderful project !

**Comment by juanrubio** [comment]
Hi Eban

`tizonia-remote` works for me when used from the terminal:

```
$ tizonia-remote playstatus
"Playing"
```

But please note that this is a tool that is meant to be used from the terminal. It assumes that an active DBUS user session exists and that the DBUS_SESSION_BUS_ADDRESS environment variable exists and has been correctly initialised (usually this is the case when using your usual Linux desktop environment).

```
$ env | grep DBUS
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-oTIHBTY0Ru,guid=31f70991e827ae3148a7c8935e89ee79
```

So for talking to Tizonia using the DBUS MPRIS interface programatically, let's say, with php, you should perhaps look at talking to DBUS using some existing php api or library.

**Comment by ebanDev** [comment]
Okay Thank you very much for taking the time to answer me!

**Comment by juanrubio** [comment]
Closing this now. I believe this works well when the user's DBUS session is active.
