### ISSUE TITLE
ModuleNotFoundError: No module named 'tizsoundcloudproxy'

### ISSUE THREAD

**Issue by ZaxonXP** [tizonia/tizonia-openmax-il#718]
### Description

Below error is displayed after running tizonia builded from sources:
```
$ tizonia --soundcloud-user-stream
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[SoundCloud] [Connecting] : '3-154538-156120355-6S6AEVwVKtxCoe'.
ModuleNotFoundError: No module named 'tizsoundcloudproxy'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]

```

### Steps to Reproduce

1.Downloaded GIT master repo
2. Compiled following the [guide](https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md)
3. Compiled and installed using the traditional method.

**Expected behavior:**
The player will stream the music

**Actual behaviour:** 
The above mentioned error occurs.

**Reproduces how often:**
Always.

### Versions
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

            * [Linux@4.19.0-6-amd64-#1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)]
            * [Boost 1_67]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v18.12]

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Installation Method Used

built from source

### Additional Information

Please guide me what else can I provide in order to solve this issue.

**Comment by tizonia** [comment]
Hi @ZaxonXP ,

I think the problem is that you need to set your PYTHONPATH correctly. See this section:
https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md#dependencies

You would need to set you PYTHONPATH like this:
```
export PYTHONPATH=/usr/lib/pythonX.Y/site-packages
```
replacing X.Y to the version of Python 3 in your system (I believe 3.7 in Debian Buster)

**Comment by ZaxonXP** [comment]
Thanks for the info.

I checked what I had set before compilation as it was suggested on the building manual and here what it was:
```
export TIZONIA_REPO_DIR=/home/user/zzz_temp/tizonia/tizonia-openmax-il # (e.g. /home/user/tizonia-openmax-il)
export TIZONIA_INSTALL_DIR=/usr # (e.g. /usr or /home/user/temp)
export PATH=$TIZONIA_REPO_DIR/tools:$PATH

# Set the PYTHONPATH accordingly (replace X to match the python version on your system)
export PYTHONPATH=$TIZONIA_INSTALL_DIR/lib/python3.7/site-packages:$PYTHONPATH

# Now install everything that is required to build Tizonia from source (Debian derivative assumed)
tizonia-dev-build --deps
```
Later on I checked the `/usr/lib/python3.7/site-packages` directory, but I found it is empty.
Any reason for this?

**Comment by tizonia** [comment]
During the installation step, the logs will tell you where the Python modules are installed. I suggest looking into that. That will give you the answer.

**Comment by tizonia** [comment]
e.g. when building Tizonia with Meson on Ubuntu Focal:

```
Installing /home/juan/work/tizonia-develop/clients/soundcloud/soundcloudproxy/tizsoundcloudproxy.py to /usr/lib/python3.8/site-packages
```

**Comment by ZaxonXP** [comment]
OK. I found these packages and updated the PYTHONPATH. Now I can play soundcloud. Thank you @tizonia ! :)
