### ISSUE TITLE
Soundcloud: Playlist is not found.

### ISSUE THREAD

**Issue by ZaxonXP** [tizonia/tizonia-openmax-il#719]
### Description

Below error is displayed after running tizonia builded from sources:
```
$ tizonia --soundcloud-user-playlist "Songs based on The Silmarillion"
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[SoundCloud] [Connecting] : '3-xxx'.
[SoundCloud] (RuntimeError) : SoundCloud did not return any playlists.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

### Steps to Reproduce

1.Downloaded GIT master repo
2. Compiled following the [guide](https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md)
3. Compiled and installed using the traditional method.
4.Run the search for playlist for SoundCloud as in the example above.

**Expected behavior:**
The player will find the playlist and stream the music

**Actual behaviour:** 
The above mentioned error occurs.

**Reproduces how often:**
Always.

### Versions
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

            * [Linux@4.19.0-6-amd64-#1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)]
            * [Boost 1_67]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v18.12]

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Installation Method Used

built from source

### Additional Information

When the same search is done using soundcloud web interface the playlist is found.

**Comment by tizonia** [comment]
Hi @ZaxonXP 

It works with playlists that you own, not with playlists that you have liked. I don't think there is a way to get those other playlists. Unfortunately, the Soundcloud Python api has not been updated since 2015, so there are few chances that we can get those other playlists to show up here.

https://github.com/soundcloud/soundcloud-python/commits/master

```
➜  ~  tizonia --soundcloud-user-playlist "metal"
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[SoundCloud] [Connecting] : '1-xxx'.
[SoundCloud] [Playlist] 'Other metal'.
[SoundCloud] [Playlist] 'metal'.
[SoundCloud] [Track] 'We Came As Romans - I Knew You You Were Trouble'.
[SoundCloud] [Track] 'All That Remains - This Probably Won't End Well'.
[SoundCloud] [Track] 'Demi Lovato - Let It Go - Frozen (Djent Cover) by Giox Producer'.
[SoundCloud] [Track] 'Mother Earth'.
[SoundCloud] [Track] 'Light Years Away'.
[SoundCloud] [Track] 'A Door Into Summer'.
[SoundCloud] [Track] 'Cool #9 [Alternate Version]'.
[SoundCloud] [Track] 'Joe Satriani - Love Thing'.
[SoundCloud] [Track] 'Joe Satriani - If i Could Fly'.
[SoundCloud] [Tracks in queue] '9'.
[SoundCloud] [Connected] : 'metal'.
   We Came As Romans - I Knew You You Were Trouble : Fearless Records
     Duration : 3m:38s
     Likes count : 0
     Permalink : https://soundcloud.com/fearlessrecords/we-came-as-romans-i-knew-you-you-were-trouble
     License : all-rights-reserved
     Audio Stream : 128 kbit/s, 44100 Hz
     MPEG Layer : III, w/o CRC
     Mode : joint (MS/intensity) stereo, no emphasis
     2 Ch, 44.1 KHz, 16:s:b

  
   0%   10   20   30   40   50   60   70   80   90   100%
0s |----|----|----|----|----|----|----|----|----|----| 3m:38s
```

**Comment by ZaxonXP** [comment]
Then it is pity they did not update the API. Thanks for clarifying.
