### ISSUE TITLE
Play icecast stream or play from mounted hard drive

### ISSUE THREAD

**Issue by thepyguy** [tizonia/tizonia-openmax-il#729]
# Issue Template

### Description
I have tried to play my icecast stream and it appears to connect but I am unable to get sound. When I direct tizonia to a mounted hard drive to play my library I get permission denied. Perhaps I need to add my user to tizonia group? I have tried switching to alsa driver and also to pulseaudio driver. I am using a USB interface focusrite scarlett solo.

### Steps to Reproduce

1. tizonia http://pyni.xyz:8000/psybient.mp3

**Expected behavior:** Stream to play

**Actual behaviour:** Stream connects but does not play

**Reproduces how often:** 100%

### Versions
Ubuntu 18.04 LTS Bionic Beaver
tizonia 0.18.0

Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v0.7.82]

### Installation Method Used
snap

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

j -*-Mode: conf; -*-
# tizonia-config v0.18.0 configuration file

[ilcore]
# Tizonia OpenMAX IL Core section

# Component plugins discovery
# -------------------------------------------------------------------------
# A comma-separated list of paths to be scanned by the Tizonia IL Core when
# searching for component plugins
component-paths = $TIZONIA_PLUGINS_DIR

# IL Core extension plugins discovery
# -------------------------------------------------------------------------
# A comma-separated list of paths to be scanned by the Tizonia IL Core when
# searching for IL Core extensions (not implemented yet)
extension-paths =

[resource-management]
# Tizonia OpenMAX IL Resource Management (RM) section

# Resource Manager (RM) daemon interface enable/disable switch
# -------------------------------------------------------------------------
# Whether the IL RM functionality is enabled or not
enabled = false

# RM database
# -------------------------------------------------------------------------
# This is the path to the Resource Manager database
rmdb = $TIZONIA_PLUGINS_DIR/usr/share/tizrmd/tizrm.db

[plugins]
# OpenMAX IL Component plugins section

# Each key-value pair represents a list of any data that a
# specific component might need. The entries here must honor the following
# format: OMX.component.name.key = <semi-colon-separated list of items>

# ALSA Audio Renderer
# -------------------------------------------------------------------------
#
# OMX.Aratelia.audio_renderer.alsa.pcm.preannouncements_disabled.port0 = false
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = default
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Master

[tizonia]
# Tizonia player section

# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.pulseaudio.pcm

# MPRIS v2 interface enable/disable switch
# -------------------------------------------------------------------------
# Valid values are: true | false
#
mpris-enabled = false

# Spotify configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment
# and configure accordingly
#
# spotify.user     = user
# spotify.password = pass
# spotify.recover_lost_token = false (set to true to continue playback after
#                                     the token has been [spuriously?] lost)
# spotify.allow_explicit_tracks = false (set to true to allow explicit tracks)

# Google Play Music configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure here.
#
# gmusic.user       = user@gmail.com
# gmusic.password   = pass (account password or app-specific password for
#                          2-factor users)
# gmusic.device_id  = deviceid (16 hex digits, e.g. '1234567890abcdef')
# gmusic.buffer_seconds = size of the audio buffer (in seconds) to use while
#                         downloading streams. Default: 720. Increase in
#                         case of cuts.

# SoundCloud configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your SoundCloud OAuth token here.
#
# To obtain your OAuth token, Tizonia needs to be granted access to your
# SoundCloud account. Visit http://tizonia.org/docs/soundcloud/ for the
# details.
#
# soundcloud.oauth_token = X-XXXXXX-XXXXXXXX-XXXXXXXXXXXXXX
# soundcloud.buffer_seconds = size of the audio buffer (in seconds) to use
#                             while downloading streams. Default: 600.
#                             Increase in case of cuts.

# Dirble configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your Dirble Api Key here.
#
# To obtain your Dirble API key, go to https://dirble.com/developer/
#
# dirble.api_key = xxxxxxxxxxxxxx
# dirble.buffer_seconds = size of the audio buffer (in seconds) to use
#                         while downloading streams. Default: 120.
#                         Increase in case of cuts.

# YouTube configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure as needed.
#
 youtube.buffer_seconds = 40

# Plex configuration
# -------------------------------------------------------------------------
# To avoid passing this information on the command line, uncomment and
# configure your Plex server and account auth token here.
#
# To find how to obtain a Plex user authentication token, see:
# https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
#
# plex.base_url = xxxxxxxxxxxxxx (e.g. http://plexserver:32400)
# plex.auth_token = xxxxxxxxxxxxxx (e.g. SrPEojhap3H5Qj2DmjhX)
# plex.buffer_seconds = size of the audio buffer (in seconds) to use
#                       while downloading streams. Default: 60.
#                       Increase in case of cuts.

**Comment by juanrubio** [comment]
Hi @thepyguy!

Thanks for trying the software.

Unfortunately, the version you are running is quite old (v0.18.0, the snap package is in need of a maintainer). Since you are running Tizonia on Ubuntu 18.04, you can install the debian packages, that will get you the latest and greatest which is 0.21.0.

**Comment by thepyguy** [comment]
No apt package "tizonia", but there is a snap with that name.
Try "snap install tizonia"

E: Unable to locate package tizonia

**Comment by thepyguy** [comment]
otherwise i'd never used this stupid snap thing :(

**Comment by juanrubio** [comment]
:-)

Tizonia is not in the official Ubuntu or Debian repositories. It's on Bintray.

See the installation instructions:
https://tizonia.org/docs/debian/

Make sure you uninstall the snap package.
