### ISSUE TITLE
[Feature Request] Add Deezer support from python API

### ISSUE THREAD

**Issue by rcandelu** [tizonia/tizonia-openmax-il#747]
Hi, I suggest adding Deezer support. Maybe It could help the python API library already developed on https://deezer-python.readthedocs.io/en/latest/index.html

Thank you.
Regards

**Comment by juanrubio** [comment]
Hi @rcandelu !

Thanks for taking the time to suggest new features. That's always welcome!

Please have a look at #498, it discusses Deezer support for Tizonia.

I've got the impression that deezer-python does not support audio streaming, only querying of song/album/artist metadata, am I right? I.e. with deezer-python you can't get URLs to the Mp3 files stored in the Deezer servers.

There used to be an official 'Deezer native SDK' that would allow an application to query metadata as well as stream audio from Deezer, but that was discontinued. See #498 for a discussion on this.

Based on this, I'm closing this issue. Please use #498 to continue the discussion if you know of a way to retrieve MP3 URLs using deezer-python.
