### ISSUE TITLE
[YouTube] (GdataError) : Youtube Error 403: The request did not specify any referer.

### ISSUE THREAD

**Issue by CendaCZ** [tizonia/tizonia-openmax-il#749]
### Description

After arbitrary --youtube-arbitrary-search with provided personal API key the the following error rises every time:

### Steps to Reproduce
1. do any `tizonia --youtube-audio-search` (given that you provided custom API key)

**Expected behavior:**
continue

**Actual behaviour:**
break after "_[YouTube] [Audio search] :_"
`[YouTube] (GdataError) : Youtube Error 403: The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions.`

**Reproduces how often:**
100% - every time when custom API key is provided

### Versions

```
* [Boost 1_72]
* [TagLib 1.11.1]
* [MediaInfoLib - v20.03]
* [gmusicapi 13.0.0 ]
* [soundcloud 0.5.0 ]
* [youtube-dl 2020.6.6 ]
* [pafy 0.5.5 ]
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application

Python module pycountry not found. Please use pip3 to install it.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'titlecase' distribution was not found and is required by the application

Python module titlecase not found. Please use pip3 to install it.
* [pychromecast 6.0.0 ]
* [plexapi 4.0.0 ]
* [spotipy 2.12.0 ]
* [fuzzywuzzy 0.18.0 ]
* [eventlet 0.25.1 ]
* [python-Levenshtein 0.12.0 ]
* [joblib 0.14.1 ]

System Info:

Linux@5.6.15-arch1-1-#1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### Installation Method Used

AUR (yay/pacman)

### Additional Information
My personal API key was created 1 or 2 years ago and is by default limited to google.com, youtube.com, youtu.be domain. For security reasons I do not want to open this restriction. Providing (here) or giving ability to change URL scheme used during fetching this should solve this.

Thank you for your time.
Cenda

**Comment by juanrubio** [comment]
Hi @CendaCZ !

Thanks for taking the time to raise an issue.

It looks like the problem is with your API key. I had problems myself with an old API key. The thing is that you don't need to change your existing key. You can simply create a new one. I think a new key will fix your problem.

This tutorial might help:
https://www.slickremix.com/docs/get-api-key-for-youtube/

**Comment by CendaCZ** [comment]
Yes, it solved the problem, thank you. It seems loosening restrictions in the old Google CP project didn't help.
