### ISSUE TITLE
iHeartRadio and TuneIn - OMX_ErrorInsufficientResources

### ISSUE THREAD

**Issue by darthmooguy** [tizonia/tizonia-openmax-il#755]
# Issue

### Description

I can't use iHeartRadio or TuneIn on my Raspberry Pi Zero, I get the OMX_ErrorInsufficientResources. I have followed the guide to enable dbus and change the output from Pulse to Alsa. Streaming using YouTube works correctly.

### Steps to Reproduce

1. Run a tizonia command with the iHeartRadio search flag, ex: `tizonia --iheart-search "power 105.1"`
2. It finds the appropriate station
3. Fails when it tries to start streaming.

**Expected behavior:**

The station starts playing.

**Actual behaviour:**

The app exits.

**Reproduces how often:**

Every time.

### Versions

<pre>
pi@raspberrypi:~ $ tizonia --debug
tizonia 0.22.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

Dependency Info:

* [Boost 1_67]
* [TagLib 1.11.1]
* [MediaInfoLib - v18.12]
* [gmusicapi 13.0.0 ]
* [soundcloud 0.5.0 ]
* [youtube-dl 2020.7.28 ]
* [pafy 0.5.5 ]
* [pycountry 20.7.3 ]
* [titlecase 1.1.1 ]
* [pychromecast 7.2.0 ]
* [plexapi 4.0.0 ]
* [spotipy 2.13.0 ]
* [fuzzywuzzy 0.18.0 ]
* [eventlet 0.26.1 ]
* [python-Levenshtein 0.12.0 ]
* [joblib 0.16.0 ]

System Info:

Linux@5.4.51+-#1327 Thu Jul 23 10:53:06 BST 2020
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
</pre>

### Installation Method Used

The install script for Debian.

### Additional Information

Here is the output:

<pre>
pi@raspberrypi:~ $ tizonia --iheart-search "power 105.1"
tizonia 0.22.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[iHeart] [iHeart search] : 'power 105.1'. 
[iHeart] [station] [#1] 'Power 105.1' [New York's Hip-Hop and R&B ] (New York, NY).
[iHeart] [Stations in queue] '1'.
[iHeart] [Streaming] : 'power 105.1'.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.alsa.pcm:port:0]
 [OMX_ErrorInsufficientResources]
</pre>

**Comment by juanrubio** [comment]
@darthmooguy 

Thanks for taking the time to report an issue.

If youtube works but iheart does not, then it must be something with the Alsa renderer, I'm thinking the sample format used by the Tizonia Alsa renderer is not accepted by the hardware on your Rpi zero.

Are you using a USB DAC perhaps?

**Comment by darthmooguy** [comment]
Yes, I have a USB DAC! Maybe it's that, because TuneIn works with Mopidy! (That uses Gstreamer I think)

**Comment by juanrubio** [comment]
Tizonia's Alsa renderer does not perform sample format conversions prior to giving the samples to ALSA. The expectation is that the ALSA device is capable of doing the necessary conversions.

I believe I

**Comment by darthmooguy** [comment]
I have a similar config in my /etc/asound.conf, but without the `type hw` parts:

```
defaults.ctl.card 1
defaults.pcm.card 1
```

However, I had to uninstall tizonia because libspotify was conflicting with [raspotify](https://github.com/dtcooper/raspotify)'s librespot.
