### ISSUE TITLE
Playing audio with youtube runs into HTTP error and OMX insufficient resources

### ISSUE THREAD

**Issue by m-GDEV** [tizonia/tizonia-openmax-il#770]
# Issue

### Description

Unable to play youtube audio due to this error: 

```
[Youtube] [Connecting] : 'https://www.youtube.com/watch?v=HzZ_urpj4As'.
[YouTube] [Audio stream] : 'https://www.youtube.com/watch?v=HzZ_urpj4As'. 
ERROR: HTTP is not supported.
[YouTube] (OSError) : ERROR: HTTP is not supported.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources] 
```

### Steps to Reproduce

1. ```tizonia --youtube-audio-stream https://www.youtube.com/watch?v=HzZ_urpj4As```
2. Wait...
3. Error occurs while trying to play audio

**Expected behavior:**

I expected the audio to play.

**Actual behaviour:**

Program runs into error and does not play the audio.

**Reproduces how often:**

I've only just found this program but this seems to be happening to the few videos i've tried it with.

### Versions

Dependency Info:
```
* [Boost 1_65_1]
* [TagLib 1.11.1]
* [MediaInfoLib - v17.12]
* [gmusicapi 13.0.0 ]
* [soundcloud 0.5.0 ]
* [youtube-dl 2019.5.20 ]
* [pafy 0.5.4 ]
* [pycountry 20.7.3 ]
* [titlecase 2.0.0 ]
* [pychromecast 9.1.1 ]
* [plexapi 4.4.0 ]
* [spotipy 2.17.1 ]
* [fuzzywuzzy 0.18.0 ]
* [eventlet 0.30.2 ]
* [python-Levenshtein 0.12.2 ]
* [joblib 0.17.0 ]

System Info:

Linux@5.4.0-65-generic-#73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021
NAME="Peppermint"
VERSION="10 (Ten)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Peppermint Ten"
VERSION_ID="10"
HOME_URL="http://peppermintos.com/"
SUPPORT_URL="http://forum.peppermintos.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/~peppermintos/"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Installation Method Used

I used the curl installition script on the website, https://tizonia.org/docs/debian/

### Additional Information

N/A

**Comment by juanrubio** [comment]
Hi @m-GDEV 

Thanks for taking the time to report an issue.

I've just tried it and I can't find the error. I've noticed that you are running Peppermint OS. Have you noticed any issues during installation, like missing dependencies or the like?


```
➜  ~  t --youtube-audio-stream https://www.youtube.com/watch\?v\=HzZ_urpj4As                                             
tizonia 0.22.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[Youtube] [Connecting] : 'https://www.youtube.com/watch?v=HzZ_urpj4As'.
[YouTube] [Audio stream] : 'https://www.youtube.com/watch?v=HzZ_urpj4As'. 
[YouTube] [Stream] [#1] 'Michael Jackson - The Way You Make Me Feel (Official Video)'.
[YouTube] [Streams in queue] '1'.
[Youtube] [Streaming] : 'https://www.youtube.com/watch?v=HzZ_urpj4As'.
   michaeljacksonVEVO : Michael Jackson - The Way You Make Me Feel (Official Video)  (1 of 1)
     Description : Official Video for “The Way You Make Me Feel” by Michael JacksonListen to Michael Jackson: https://MichaelJac
     Published : 2009-10-03 04:48:18Z
     View Count : 375586512
     YouTube Id : https://youtu.be/https://www.youtube.com/watch?v=HzZ_urpj4As
     File Format : webm
     Bitrate : 126.62k
     Size : 6 MiB
     Duration : 06m:44s
     Opus Stream : 2 Ch, 48000 Hz
     2 Ch, 48 KHz, 16:s:l

  
   0%   10   20   30   40   50   60   70   80   90   100%
0s |----|----|----|----|----|----|----|----|----|----| 6m:44s
                         2m:42s
```

**Comment by juanrubio** [comment]
Looking around, I've found this thread:
https://github.com/mps-youtube/mps-youtube/issues/986#issuecomment-573104715

It looks like your system may have an old version of pafy installed.

This command should install the latest version of the Python modules required by Tizonia:

```
sudo -H pip3 install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi spotipy fuzzywuzzy eventlet python-Levenshtein
```

**Comment by m-GDEV** [comment]
> Looking around, I've found this thread:
> [mps-youtube/mps-youtube#986 (comment)](https://github.com/mps-youtube/mps-youtube/issues/986#issuecomment-573104715)
> 
> It looks like your system may have an old version of pafy installed.
> 
> This command should install the latest version of the Python modules required by Tizonia:
> 
> ```
> sudo -H pip3 install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi spotipy fuzzywuzzy eventlet python-Levenshtein
> ```

Hey, thanks for your response! 
First of all, thanks so much for making this amazing utility!

Funny enough, when I ran you command in the terminal I was given "requirement for x is already satisfied" for every pip3 package. Nothing extra was installed or updated. It is very possible that the terminal instance was older and had not recognized the new packages installed by pip.

Thanks for your response!
