### ISSUE TITLE
Login attempt failed. User need premium. I have premium.

### ISSUE THREAD

**Issue by alazyworkaholic** [tizonia/tizonia-openmax-il#796]
# Issue Cannot use premium Spotify account.

### Description
Tizonia connects to Spotify and retrieves a list of tracks but then ends with 

```
Spotify] [Cache]: '/var/tmp/tizonia-alan-spotify-alazyworkaholic@gmail.com'
[Spotify] [FATAL] Login attempt failed. User needs premium.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```
I do have a premium account and my e-mail and password are definitely correct.

### Steps to Reproduce

1. Download tizonia install script
2. Change 'focal' on line 81 to 'focal|impish' to allow install for later version of Ubuntu
3. Execute `bash install.sh`
4. Insert account & password into tizonia.conf
5. run tizonia --spotify-user-liked-tracks

**Expected behavior:**
Spotify plays music

**Actual behaviour:**
Spotify tells me my account isn't premium, although it is.

**Reproduces how often:**
Every time

### Versions
tizonia 0.22.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

Dependency Info:

* [Boost 1_71]
* [TagLib 1.11.1]
* [MediaInfoLib - v21.03]
* [gmusicapi 13.0.0 ]
* [soundcloud 0.5.0 ]
* [youtube-dl 2021.4.1 ]
* [pafy 0.5.5 ]
* [pycountry 20.7.3 ]
* [titlecase 2.0.0 ]
* [pychromecast 9.1.1 ]
* [plexapi 4.5.1 ]
* [spotipy 2.17.1 ]
* [fuzzywuzzy 0.18.0 ]
* [eventlet 0.30.2 ]
* [python-Levenshtein 0.12.2 ]
* [joblib 1.0.1 ]

System Info:

Linux@5.13.0-48-generic-#54-Ubuntu SMP Wed Jun 1 20:38:48 UTC 2022
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

### Installation Method Used
Ran install.sh script from website, with one modification.
Change 'focal' on line 81 to 'focal|impish' to allow install for later version of Ubuntu

### Additional Information

**Comment by jgieseler** [comment]
Yes, same for me. [According to the tizonia chat](https://gitter.im/tizonia/Lobby) the problem seem to exist at least for two weeks (haven't tried myself in a while)... :cry:

**Comment by alazyworkaholic** [comment]
Looks like [libspotify is dead, ](https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/) and tizonia is a zombie. I just realized there has been no development for 2 years now.

**Comment by jgieseler** [comment]
I'm wondering if it would be an option to migrate to https://developer.spotify.com/documentation/web-playback-sdk/?
